BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Comparator Class Reference
brics_3d::Comparator Class Reference
The class handles all the calculations and plotting related to comparing the algorithms.
#include <Comparator.h>
Public Member Functions
Comparator ()
virtual ~Comparator ()
bool isInitialised ()
Check if the comparator object is properly initialized or not.
void compare ()
Performs the comparison of set methods.
string getGtMetricsBaseName () const
void setPath (string path)
Setting folder path to the metric files to be used for comparison.
bool getInitialiseStatus () const
Get the initialization status of the comparator.
vector< string > getMethods () const
string getMsMetricsBaseName () const
string getOverlapBaseName () const
void setGtMetricsBaseName (string GtMetricsBaseName)
void setMethods (vector< string > methods)
void setMsMetricsBaseName (string MsMetricsBaseName)
void setOverlapBaseName (string overlapBaseName)
Private Member Functions
void generateGTPlots (vector< string > *vecMetrics, int noOfMetrics, vector< string > metricNames, string regionType, string nameOfFile)
private method for generating the plots for GT metric and MS metric based comparison
void generateParametericPlots (vector< string > *vecMetrics, int noOfMetrics, vector< string > metricNames, string nameOfFile)
double calculateMean (double *values, int sizeOfArray)
Calculate and return the mean of an array of double values.
double calculateMedian (double *values, int sizeOfArray)
Calculate and return the median of an array of double values.
double calculateVariance (double *values, int sizeOfArray)
Calculate and return the variance of an array of double values.
double calculateStdDeviation (double *values, int sizeOfArray)
Calculate and return the standard deviation of an array of double values.
Private Attributes
bool initialiseStatus
vector< string > vecMethodNames
string overlapBaseName
string GtMetricsBaseName
string MsMetricsBaseName
string path
Detailed Description
The class handles all the calculations and plotting related to comparing the algorithms.
Definition at line 30 of file Comparator.h.
Constructor & Destructor Documentation
brics_3d::Comparator::Comparator ()
Definition at line 33 of file Comparator.cpp.
brics_3d::Comparator::~Comparator () [virtual]
Definition at line 380 of file Comparator.cpp.
Member Function Documentation
double brics_3d::Comparator::calculateMean (double * values, int sizeOfArray) [private]
Calculate and return the mean of an array of double values.
Definition at line 268 of file Comparator.cpp.
double brics_3d::Comparator::calculateMedian (double * values, int sizeOfArray) [private]
Calculate and return the median of an array of double values.
Definition at line 281 of file Comparator.cpp.
double brics_3d::Comparator::calculateStdDeviation (double * values, int sizeOfArray) [private]
Calculate and return the standard deviation of an array of double values.
Definition at line 320 of file Comparator.cpp.
double brics_3d::Comparator::calculateVariance (double * values, int sizeOfArray) [private]
Calculate and return the variance of an array of double values.
Definition at line 304 of file Comparator.cpp.
void brics_3d::Comparator::compare ()
Performs the comparison of set methods.
Definition at line 96 of file Comparator.cpp.
References brics_3d::FileReader::toStringVector().
void brics_3d::Comparator::generateGTPlots (vector< string > * vecMetrics, int noOfMetrics, vector< string > metricNames, string regionType, string nameOfFile) [private]
private method for generating the plots for GT metric and MS metric based comparison
Definition at line 325 of file Comparator.cpp.
References Gnuplot::cmd(), Gnuplot::reset_all(), Gnuplot::reset_plot(), Gnuplot::savetops(), Gnuplot::set_grid(), Gnuplot::set_legend(), Gnuplot::set_title(), Gnuplot::set_xlabel(), and Gnuplot::set_ylabel().
void brics_3d::Comparator::generateParametericPlots (vector< string > * vecMetrics, int noOfMetrics, vector< string > metricNames, string nameOfFile) [private]
Definition at line 171 of file Comparator.cpp.
References Gnuplot::cmd(), Gnuplot::reset_all(), Gnuplot::reset_plot(), Gnuplot::savetops(), Gnuplot::set_grid(), Gnuplot::set_legend(), Gnuplot::set_title(), and Gnuplot::set_xlabel().
string brics_3d::Comparator::getGtMetricsBaseName () const
Definition at line 45 of file Comparator.cpp.
bool brics_3d::Comparator::getInitialiseStatus () const
Get the initialization status of the comparator.
Definition at line 50 of file Comparator.cpp.
vector< string > brics_3d::Comparator::getMethods () const
Definition at line 55 of file Comparator.cpp.
string brics_3d::Comparator::getMsMetricsBaseName () const
Definition at line 60 of file Comparator.cpp.
string brics_3d::Comparator::getOverlapBaseName () const
Definition at line 65 of file Comparator.cpp.
bool brics_3d::Comparator::isInitialised ()
Check if the comparator object is properly initialized or not.
Definition at line 92 of file Comparator.cpp.
void brics_3d::Comparator::setGtMetricsBaseName (string GtMetricsBaseName)
Definition at line 70 of file Comparator.cpp.
void brics_3d::Comparator::setMethods (vector< string > methods)
Definition at line 75 of file Comparator.cpp.
void brics_3d::Comparator::setMsMetricsBaseName (string MsMetricsBaseName)
Definition at line 81 of file Comparator.cpp.
void brics_3d::Comparator::setOverlapBaseName (string overlapBaseName)
Definition at line 86 of file Comparator.cpp.
void brics_3d::Comparator::setPath (string path)
Setting folder path to the metric files to be used for comparison.
Definition at line 41 of file Comparator.cpp.
Member Data Documentation
string brics_3d::Comparator::GtMetricsBaseName [private]
Definition at line 35 of file Comparator.h.
bool brics_3d::Comparator::initialiseStatus [private]
Definition at line 32 of file Comparator.h.
string brics_3d::Comparator::MsMetricsBaseName [private]
Definition at line 36 of file Comparator.h.
string brics_3d::Comparator::overlapBaseName [private]
Definition at line 34 of file Comparator.h.
string brics_3d::Comparator::path [private]
Definition at line 37 of file Comparator.h.
vector<string> brics_3d::Comparator::vecMethodNames [private]
Definition at line 33 of file Comparator.h.
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/evaluation/Comparator.h
src/brics_3d/algorithm/segmentation/evaluation/Comparator.cpp