BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::Transform Class Reference
brics_3d::rsg::Transform Class Reference
Scenegraph
A node that expresses a geometric transformation between its parents and children.
#include <Transform.h>
Public Types
typedef boost::shared_ptr
< rsg::Transform > TransformPtr
typedef boost::shared_ptr
< rsg::Transform const > TransformConstPtr
Public Member Functions
Transform ()
virtual ~Transform ()
void insertTransform (IHomogeneousMatrix44::IHomogeneousMatrix44Ptr newTransform, TimeStamp timeStamp)
Add a new transform to the history.
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr getTransform (TimeStamp timeStamp)
Retrieve a transform in the history cache whose time stamp matches best a given stamp.
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr getLatestTransform ()
Retrieve the latest/newest transform.
TimeStamp getMaxHistoryDuration ()
Getter for maxHistoryDuration.
void setMaxHistoryDuration (TimeStamp maxHistoryDuration)
Setter for maxHistoryDuration.
unsigned int getCurrentHistoryLenght ()
Returns the number of elements that are stored in the history cache.
TimeStamp getLatestTimeStamp ()
Get the latest time stamp that is in the history cache.
TimeStamp getOldestTimeStamp ()
Get the oldest time stamp that is in the history cache.
unsigned int getUpdateCount ()
Get the counter for how often this transform node has been updated.
void accept (INodeVisitor *visitor)
void deleteOutdatedTransforms (TimeStamp latestTimeStamp)
Delete all data from the history/cache that is older than the latestTimeStamp minus the duration of maxHistoryDuration.
Private Member Functions
HistoryIterator getClosestTransform (TimeStamp timeStamp)
Determine the position in the history cache whose time stamp matches best a given stamp.
Private Attributes
vector< pair
< IHomogeneousMatrix44::IHomogeneousMatrix44Ptr,
TimeStamp > > history
History of transforms. Each transform has an associated time stamp.
HistoryIterator historyIterator
Iterator for the history data.
TimeStamp maxHistoryDuration
Maximum duration of storing the history of transforms.
unsigned int updateCount
Counter for how often this transform node has been updated via insertTransform.
Static Private Attributes
static const long double dafaultMaxHistoryDuration = 10000.0
10s in [ms] in case that the brics_3d::Timer is used, otherwise this number has no real meaning and should just serve as a default.
Detailed Description
A node that expresses a geometric transformation between its parents and children.
The transform node can cache transform data over a certain period of time. Typically one wants to get the most recent transform. This can be done with the getLatestTransform() function. More advanced queries will have to invoke the getTransform(TimeStamp timeStamp) function. See further details at the description of that function.
Definition at line 67 of file Transform.h.
Member Typedef Documentation
typedef boost::shared_ptr<rsg::Transform const> brics_3d::rsg::Transform::TransformConstPtr
Definition at line 72 of file Transform.h.
typedef boost::shared_ptr<rsg::Transform> brics_3d::rsg::Transform::TransformPtr
Definition at line 71 of file Transform.h.
Constructor & Destructor Documentation
brics_3d::rsg::Transform::Transform ()
Definition at line 86 of file Transform.cpp.
References history.
brics_3d::rsg::Transform::~Transform () [virtual]
Definition at line 94 of file Transform.cpp.
References history.
Member Function Documentation
void brics_3d::rsg::Transform::accept (INodeVisitor * visitor) [virtual]
Reimplemented from brics_3d::rsg::Group.
Definition at line 246 of file Transform.cpp.
References brics_3d::rsg::Node::accept(), brics_3d::rsg::INodeVisitor::downwards, brics_3d::rsg::Group::getChild(), brics_3d::rsg::INodeVisitor::getDirection(), brics_3d::rsg::Group::getNumberOfChildren(), brics_3d::rsg::Node::getNumberOfParents(), brics_3d::rsg::Node::getParent(), brics_3d::rsg::INodeVisitor::upwards, and brics_3d::rsg::INodeVisitor::visit().
void brics_3d::rsg::Transform::deleteOutdatedTransforms (TimeStamp latestTimeStamp)
Delete all data from the history/cache that is older than the latestTimeStamp minus the duration of maxHistoryDuration.
Parameters:
latestTimeStamp The time stamp the defines the "current" time. To this stamp the maximim duration will relate. Plase note that in case that you do not pass the timeStamp from the history cache via getLatestTimeStamp() the complete history might get earased! Use the function outside the scope of this class with care.
Definition at line 138 of file Transform.cpp.
References history, and maxHistoryDuration.
Referenced by insertTransform().
HistoryIterator brics_3d::rsg::Transform::getClosestTransform (TimeStamp timeStamp) [private]
Determine the position in the history cache whose time stamp matches best a given stamp.
Parameters:
timeStamp Time stamp to wich the temporal closest data shall be found.
Returns:
Iterator to the transform with closest time stamp. In case timeStamp is exactly in between two times stamps of the cache the latest of both will be taken.
Definition at line 148 of file Transform.cpp.
References getCurrentHistoryLenght(), and history.
Referenced by getTransform().
unsigned int brics_3d::rsg::Transform::getCurrentHistoryLenght ()
Returns the number of elements that are stored in the history cache.
Definition at line 220 of file Transform.cpp.
References history.
Referenced by getClosestTransform().
TimeStamp brics_3d::rsg::Transform::getLatestTimeStamp ()
Get the latest time stamp that is in the history cache.
Returns:
The latest time stamp or 0.0 in case of an empty history cache.
Definition at line 224 of file Transform.cpp.
References brics_3d::rsg::Node::getId(), history, historyIterator, and LOG.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr brics_3d::rsg::Transform::getLatestTransform ()
Retrieve the latest/newest transform.
Returns:
Shared pointer to the transform. It will be null in case that no transform is found.
Definition at line 198 of file Transform.cpp.
References brics_3d::rsg::Node::getId(), history, historyIterator, and LOG.
Referenced by brics_3d::rsg::getGlobalTransformAlongPath(), and brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
TimeStamp brics_3d::rsg::Transform::getMaxHistoryDuration ()
Getter for maxHistoryDuration.
Definition at line 212 of file Transform.cpp.
References maxHistoryDuration.
TimeStamp brics_3d::rsg::Transform::getOldestTimeStamp ()
Get the oldest time stamp that is in the history cache.
Returns:
The oldest time stamp or 0.0 in case of an empty history cache.
Definition at line 233 of file Transform.cpp.
References brics_3d::rsg::Node::getId(), history, historyIterator, and LOG.
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr brics_3d::rsg::Transform::getTransform (TimeStamp timeStamp)
Retrieve a transform in the history cache whose time stamp matches best a given stamp.
Parameters:
timeStamp Time stamp to wich the temporal closest transform shall be found.
Returns:
Shared pointer to the transform. It will be null in case that no transform is found.
Definition at line 184 of file Transform.cpp.
References getClosestTransform(), brics_3d::rsg::Node::getId(), history, and LOG.
unsigned int brics_3d::rsg::Transform::getUpdateCount ()
Get the counter for how often this transform node has been updated.
Definition at line 242 of file Transform.cpp.
References updateCount.
void brics_3d::rsg::Transform::insertTransform (IHomogeneousMatrix44::IHomogeneousMatrix44Ptr newTransform, TimeStamp timeStamp)
Add a new transform to the history.
Parameters:
newTransform The transform to be added.
timeStamp The times stamp that is associated with the transform.
Definition at line 102 of file Transform.cpp.
References deleteOutdatedTransforms(), history, historyIterator, and updateCount.
void brics_3d::rsg::Transform::setMaxHistoryDuration (TimeStamp maxHistoryDuration)
Setter for maxHistoryDuration.
Definition at line 216 of file Transform.cpp.
References maxHistoryDuration.
Member Data Documentation
const long double brics_3d::rsg::Transform::dafaultMaxHistoryDuration = 10000.0 [static, private]
10s in [ms] in case that the brics_3d::Timer is used, otherwise this number has no real meaning and should just serve as a default.
Definition at line 161 of file Transform.h.
vector< pair<IHomogeneousMatrix44::IHomogeneousMatrix44Ptr, TimeStamp> > brics_3d::rsg::Transform::history [private]
History of transforms. Each transform has an associated time stamp.
Definition at line 152 of file Transform.h.
Referenced by deleteOutdatedTransforms(), getClosestTransform(), getCurrentHistoryLenght(), getLatestTimeStamp(), getLatestTransform(), getOldestTimeStamp(), getTransform(), insertTransform(), Transform(), and ~Transform().
HistoryIterator brics_3d::rsg::Transform::historyIterator [private]
Iterator for the history data.
Definition at line 155 of file Transform.h.
Referenced by getLatestTimeStamp(), getLatestTransform(), getOldestTimeStamp(), and insertTransform().
TimeStamp brics_3d::rsg::Transform::maxHistoryDuration [private]
Maximum duration of storing the history of transforms.
Definition at line 158 of file Transform.h.
Referenced by deleteOutdatedTransforms(), getMaxHistoryDuration(), and setMaxHistoryDuration().
unsigned int brics_3d::rsg::Transform::updateCount [private]
Counter for how often this transform node has been updated via insertTransform.
Definition at line 164 of file Transform.h.
Referenced by getUpdateCount(), and insertTransform().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/Transform.h
src/brics_3d/worldModel/sceneGraph/Transform.cpp