BRICS_RN_Robust_Navigation_Library(BRICS_RN): TrajectoryAdapterNodeState Class Reference
TrajectoryAdapterNodeState Class Reference
Public Types
enum State { IDLING, PLANNING, COLLISION_CHECKING }
Public Member Functions
TrajectoryAdapterNodeState ()
TrajectoryAdapterNodeState (const TrajectoryAdapterNodeState &orig)
void set (State state)
State get () const
Private Attributes
State state
Detailed Description
Definition at line 61 of file TrajectoryAdapterNode.cpp.
Member Enumeration Documentation
enum TrajectoryAdapterNodeState::State
Enumerator:
IDLING
PLANNING
COLLISION_CHECKING
Definition at line 64 of file TrajectoryAdapterNode.cpp.
Constructor & Destructor Documentation
TrajectoryAdapterNodeState::TrajectoryAdapterNodeState () [inline]
Definition at line 68 of file TrajectoryAdapterNode.cpp.
TrajectoryAdapterNodeState::TrajectoryAdapterNodeState (const TrajectoryAdapterNodeState & orig) [inline]
Definition at line 72 of file TrajectoryAdapterNode.cpp.
References get().
Member Function Documentation
State TrajectoryAdapterNodeState::get () const [inline]
Definition at line 80 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and TrajectoryAdapterNodeState().
void TrajectoryAdapterNodeState::set (State state) [inline]
Definition at line 76 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), goalCallback(), and main().
Member Data Documentation
State TrajectoryAdapterNodeState::state [private]
Definition at line 86 of file TrajectoryAdapterNode.cpp.
The documentation for this class was generated from the following file:
navigation_trajectory_planner/src/TrajectoryAdapterNode.cpp