BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ColorSpaceConvertor Class Reference
brics_3d::ColorSpaceConvertor Class Reference
#include <ColorSpaceConvertor.h>
Public Member Functions
ColorSpaceConvertor ()
virtual ~ColorSpaceConvertor ()
void rgbToHsv (int red, int green, int blue, double *hue, double *sat, double *val)
R, G and B are scaled to fit 0..1 range.
void rgb24bitToRGB (int rgb_val, uint8_t *r, uint8_t *g, uint8_t *b)
Calculates R, G, B value for rgb-24 bit encoding.
void rgbToRGB24Bit (float *rgb24Bit, unsigned char r, unsigned char g, unsigned char b)
Calculates rgb-24 bit encoding for R, G, B values.
Private Member Functions
double minVal (double a, double b, double c)
Finds the minimum out of three double values.
double maxVal (double a, double b, double c)
Finds the maximum out of three double values.
Private Attributes
double epsilon
Minumum error to compare double-values.
Detailed Description
Definition at line 28 of file ColorSpaceConvertor.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d core ColorSpaceConvertor cpp brics_3d::ColorSpaceConvertor::ColorSpaceConvertor ()
Definition at line 28 of file ColorSpaceConvertor.cpp.
brics_3d::ColorSpaceConvertor::~ColorSpaceConvertor () [virtual]
Definition at line 33 of file ColorSpaceConvertor.cpp.
Member Function Documentation
double brics_3d::ColorSpaceConvertor::maxVal (double a, double b, double c) [inline, private]
Finds the maximum out of three double values.
Parameters:
a
b
c
Returns:
The maximum value
Definition at line 69 of file ColorSpaceConvertor.h.
double brics_3d::ColorSpaceConvertor::minVal (double a, double b, double c) [inline, private]
Finds the minimum out of three double values.
Parameters:
a
b
c
Returns:
The minimum value
Definition at line 43 of file ColorSpaceConvertor.h.
void brics_3d::ColorSpaceConvertor::rgb24bitToRGB (int rgb_val, uint8_t * r, uint8_t * g, uint8_t * b)
Calculates R, G, B value for rgb-24 bit encoding.
Parameters:
rgb24Bit
r
g
b
Definition at line 79 of file ColorSpaceConvertor.cpp.
Referenced by brics_3d::PCLTypecaster::convertToBRICS3DDataType().
void brics_3d::ColorSpaceConvertor::rgbToHsv (int red, int green, int blue, double * hue, double * sat, double * val)
R, G and B are scaled to fit 0..1 range.
V <- max(R,G,B) S <- (V-min(R,G,B))/V if V≠0, 0 otherwise
(G - B)*60/S, if V=R H <- 180+(B - R)*60/S, if V=G 240+(R - G)*60/S, if V=B
if H<0 then H<-H+360
Parameters:
r red-value
g green-value
b blue-value
h corresponding hue
s corresponding saturation
v corresponding intensity value
Definition at line 36 of file ColorSpaceConvertor.cpp.
Referenced by brics_3d::ColorBasedROIExtractorHSV::filter().
void brics_3d::ColorSpaceConvertor::rgbToRGB24Bit (float * rgb24Bit, unsigned char r, unsigned char g, unsigned char b)
Calculates rgb-24 bit encoding for R, G, B values.
Parameters:
rgb24Bit
r
g
b
Definition at line 88 of file ColorSpaceConvertor.cpp.
Referenced by brics_3d::PCLTypecaster::convertToPCLDataType().
Member Data Documentation
double brics_3d::ColorSpaceConvertor::epsilon [private]
Minumum error to compare double-values.
Definition at line 34 of file ColorSpaceConvertor.h.
The documentation for this class was generated from the following files:
src/brics_3d/core/ColorSpaceConvertor.h
src/brics_3d/core/ColorSpaceConvertor.cpp