BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Evaluator Class Reference
brics_3d::Evaluator Class Reference
#include <Evaluator.h>
Public Member Functions
Evaluator ()
virtual ~Evaluator ()
void setGtBaseName (std::string baseName)
std::string getGtBaseName ()
void setMsBaseName (std::string baseName)
std::string getMsBaseName ()
void setFileExt (std::string ext)
std::string getFileExt ()
void setCountGt (int count)
int getCountGt ()
void setCountMs (int count)
int getCountMs ()
void setRegionCorrespondence (std::string regCorres)
std::string getRegionCorrespondence ()
void setImageSize (int size)
int getImageSize ()
void Initialize ()
Initialize the vectors by reading the required GT and MS files.
bool IsInitialized ()
Public Attributes
vector< std::string > * vectorGt
vector< std::string > * vectorMs
Private Attributes
std::string gtBaseName
std::string msBaseName
std::string fileExt
int countGt
int countMs
std::string regionCorrespondence
int imageSize
bool initializationStatus
Detailed Description
Definition at line 32 of file Evaluator.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d algorithm segmentation evaluation Evaluator cpp brics_3d::Evaluator::Evaluator ()
Definition at line 27 of file Evaluator.cpp.
brics_3d::Evaluator::~Evaluator () [virtual]
Definition at line 38 of file Evaluator.cpp.
Member Function Documentation
int brics_3d::Evaluator::getCountGt ()
Definition at line 44 of file Evaluator.cpp.
Referenced by brics_3d::MetricCalculator::calculateGtMetrics(), brics_3d::MetricCalculator::calculateMetrics(), brics_3d::MetricCalculator::calculateMsMetrics(), and brics_3d::MetricCalculator::calculateOverlap().
int brics_3d::Evaluator::getCountMs ()
Definition at line 51 of file Evaluator.cpp.
Referenced by brics_3d::MetricCalculator::calculateGtMetrics(), brics_3d::MetricCalculator::calculateMetrics(), brics_3d::MetricCalculator::calculateMsMetrics(), and brics_3d::MetricCalculator::calculateOverlap().
string brics_3d::Evaluator::getFileExt ()
Definition at line 58 of file Evaluator.cpp.
string brics_3d::Evaluator::getGtBaseName ()
Definition at line 65 of file Evaluator.cpp.
int brics_3d::Evaluator::getImageSize ()
Definition at line 87 of file Evaluator.cpp.
Referenced by brics_3d::MetricCalculator::calculateGtMetrics(), brics_3d::MetricCalculator::calculateMetrics(), and brics_3d::MetricCalculator::calculateMsMetrics().
string brics_3d::Evaluator::getMsBaseName ()
Definition at line 72 of file Evaluator.cpp.
string brics_3d::Evaluator::getRegionCorrespondence ()
Definition at line 79 of file Evaluator.cpp.
Referenced by brics_3d::MetricCalculator::calculateOverlap().
void brics_3d::Evaluator::Initialize ()
Initialize the vectors by reading the required GT and MS files.
Definition at line 92 of file Evaluator.cpp.
References fileExt, gtBaseName, brics_3d::FileReader::toStringVector(), and vectorGt.
bool brics_3d::Evaluator::IsInitialized ()
Definition at line 120 of file Evaluator.cpp.
Referenced by brics_3d::MetricCalculator::calculateMetrics().
void brics_3d::Evaluator::setCountGt (int count)
Definition at line 41 of file Evaluator.cpp.
void brics_3d::Evaluator::setCountMs (int count)
Definition at line 48 of file Evaluator.cpp.
void brics_3d::Evaluator::setFileExt (std::string ext)
Definition at line 55 of file Evaluator.cpp.
void brics_3d::Evaluator::setGtBaseName (std::string baseName)
Definition at line 62 of file Evaluator.cpp.
void brics_3d::Evaluator::setImageSize (int size)
Definition at line 83 of file Evaluator.cpp.
void brics_3d::Evaluator::setMsBaseName (std::string baseName)
Definition at line 69 of file Evaluator.cpp.
void brics_3d::Evaluator::setRegionCorrespondence (std::string regCorres)
Definition at line 76 of file Evaluator.cpp.
Member Data Documentation
int brics_3d::Evaluator::countGt [private]
Definition at line 37 of file Evaluator.h.
int brics_3d::Evaluator::countMs [private]
Definition at line 38 of file Evaluator.h.
std::string brics_3d::Evaluator::fileExt [private]
Definition at line 36 of file Evaluator.h.
Referenced by Initialize().
std::string brics_3d::Evaluator::gtBaseName [private]
Definition at line 34 of file Evaluator.h.
Referenced by Initialize().
int brics_3d::Evaluator::imageSize [private]
Definition at line 40 of file Evaluator.h.
bool brics_3d::Evaluator::initializationStatus [private]
Definition at line 41 of file Evaluator.h.
std::string brics_3d::Evaluator::msBaseName [private]
Definition at line 35 of file Evaluator.h.
std::string brics_3d::Evaluator::regionCorrespondence [private]
Definition at line 39 of file Evaluator.h.
vector<std::string>* brics_3d::Evaluator::vectorGt
Definition at line 43 of file Evaluator.h.
Referenced by brics_3d::MetricCalculator::calculateOverlap(), and Initialize().
vector<std::string>* brics_3d::Evaluator::vectorMs
Definition at line 44 of file Evaluator.h.
Referenced by brics_3d::MetricCalculator::calculateOverlap().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/evaluation/Evaluator.h
src/brics_3d/algorithm/segmentation/evaluation/Evaluator.cpp