BRICS_RN (Robust Navigation Library): DouglasPeuckerApproximation Class Reference
DouglasPeuckerApproximation Class Reference
Implementation of path approximation algorithm.
#include <DouglasPeuckerApproximation.h>
Public Member Functions
DouglasPeuckerApproximation ()
Constructor.
DouglasPeuckerApproximation (const DouglasPeuckerApproximation &orig)
Copy constructor.
virtual ~DouglasPeuckerApproximation ()
Destructor.
void approximate (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out)
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
void approximate (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out, double epsilon)
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
Private Member Functions
void douglasPeucker (const std::vector< FrameWithId > &pointList, std::vector< FrameWithId > &resultList, int &counter, double epsilon)
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
Detailed Description
Implementation of path approximation algorithm.
Ramer–Douglas–Peucker algorithm is an algorithm for reducing the number of points in a curve that is approximated by a series of points.
Definition at line 55 of file DouglasPeuckerApproximation.h.
Constructor & Destructor Documentation
DouglasPeuckerApproximation::DouglasPeuckerApproximation ()
Constructor.
Definition at line 50 of file DouglasPeuckerApproximation.cpp.
DouglasPeuckerApproximation::DouglasPeuckerApproximation (const DouglasPeuckerApproximation & orig)
Copy constructor.
Definition at line 53 of file DouglasPeuckerApproximation.cpp.
DouglasPeuckerApproximation::~DouglasPeuckerApproximation () virtual
Destructor.
Definition at line 56 of file DouglasPeuckerApproximation.cpp.
Member Function Documentation
void DouglasPeuckerApproximation::approximate (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out) virtual
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
The epsilon parameter of the algorithm defaults to 0.1.
Parameters
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting smoothed path.
Implements IPathApproximation.
Definition at line 59 of file DouglasPeuckerApproximation.cpp.
Referenced by controlLoop().
void DouglasPeuckerApproximation::approximate (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out, double epsilon)
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
Parameters
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting path with reduced number of points.
epsilon - minimum distance between points.
Definition at line 64 of file DouglasPeuckerApproximation.cpp.
References douglasPeucker(), Stopwatch::getElapsedTime(), LOG, Stopwatch::start(), and Stopwatch::stop().
void DouglasPeuckerApproximation::douglasPeucker (const std::vector< FrameWithId > & pointList, std::vector< FrameWithId > & resultList, int & counter, double epsilon) private
Reduces the number of points of an input path by Ramer–Douglas–Peucker algorithm.
Parameters
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting path with reduced number of points.
counter - internal number of operations' counter.
epsilon - minimum distance between points.
Definition at line 87 of file DouglasPeuckerApproximation.cpp.
References utilities::perpendicularDistance().
Referenced by approximate().
The documentation for this class was generated from the following files:
navigation_trajectory_planner/include/navigation_trajectory_planner/DouglasPeuckerApproximation.h
navigation_trajectory_planner/src/DouglasPeuckerApproximation.cpp