BRICS_RN (Robust Navigation Library): Odometry Class Reference
Odometry Class Reference
Class represents odometry data, which is an aggregation of Twist2D and Pose2D.
#include <Odometry.h>
Public Member Functions
Odometry ()
Constructor.
Odometry (const Pose2D &pose, const Twist2D &twist)
Constructor.
Odometry (const Pose2D &pose)
Constructor.
Odometry (const Twist2D &twist)
Constructor.
Odometry (const Odometry &orig)
Copy constructor.
const Odometry & operator= (const Odometry &orig)
Assignment operator.
const Pose2D & getPose2D () const
Class represents an odometry data.
void setPose2D (const Pose2D &twist)
Class represents an odometry data.
const Twist2D & getTwist2D () const
Class represents an odometry data.
void setTwist2D (const Twist2D &twist)
Class represents an odometry data.
virtual ~Odometry ()
Class represents an odometry data.
Private Attributes
Pose2D pose
Class represents an odometry data.
Twist2D twist
Class represents an odometry data.
Detailed Description
Class represents odometry data, which is an aggregation of Twist2D and Pose2D.
Definition at line 49 of file Odometry.h.
Constructor & Destructor Documentation
Odometry::Odometry ()
Constructor.
Definition at line 42 of file Odometry.cpp.
Odometry::Odometry (const Pose2D & pose, const Twist2D & twist)
Constructor.
Parameters
[in] pose - initial 2D pose.
[in] twist - initial 2D twist.
Definition at line 46 of file Odometry.cpp.
Odometry::Odometry (const Pose2D & pose)
Constructor.
Parameters
[in] pose - initial pose.
Definition at line 50 of file Odometry.cpp.
Odometry::Odometry (const Twist2D & twist)
Constructor.
Parameters
[in] twist - initial twist.
Definition at line 54 of file Odometry.cpp.
Odometry::Odometry (const Odometry & orig)
Copy constructor.
Definition at line 58 of file Odometry.cpp.
Odometry::~Odometry () virtual
Class represents an odometry data.
Definition at line 68 of file Odometry.cpp.
Member Function Documentation
const Pose2D & Odometry::getPose2D () const
Class represents an odometry data.
Definition at line 72 of file Odometry.cpp.
References pose.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator=(), publishOdometry(), and OmniDrivePositionController::targetReached().
const Twist2D & Odometry::getTwist2D () const
Class represents an odometry data.
Definition at line 80 of file Odometry.cpp.
References twist.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator=(), and publishOdometry().
const Odometry & Odometry::operator= (const Odometry & orig)
Assignment operator.
Definition at line 62 of file Odometry.cpp.
References getPose2D(), getTwist2D(), pose, and twist.
void Odometry::setPose2D (const Pose2D & twist)
Class represents an odometry data.
Definition at line 76 of file Odometry.cpp.
References pose.
void Odometry::setTwist2D (const Twist2D & twist)
Class represents an odometry data.
Definition at line 84 of file Odometry.cpp.
References twist.
Referenced by OmniDrivePositionController::computeNewOdometry().
Member Data Documentation
Pose2D Odometry::pose private
Class represents an odometry data.
Definition at line 116 of file Odometry.h.
Referenced by getPose2D(), operator=(), and setPose2D().
Twist2D Odometry::twist private
Class represents an odometry data.
Definition at line 121 of file Odometry.h.
Referenced by getTwist2D(), operator=(), and setTwist2D().
The documentation for this class was generated from the following files:
navigation_trajectory_follower/src/omnidrive_controller/Odometry.h
navigation_trajectory_follower/src/omnidrive_controller/Odometry.cpp