BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelPlaneFromLines Class Reference
brics_3d::ObjectModelPlaneFromLines Class Reference
Segmentation
Finds a plane model from two 3D line segments in the data.
#include <ObjectModelPlaneFromLines.h>
Classes
struct line
Public Member Functions
bool contains (const line &line, Point3D &point)
Checks if a line contains a point or not.
void crossProduct3D (const std::vector< double > &v0, const std::vector< double > &v1, std::vector< double > &v_out)
Computes the cross product of two 3D vectors, returning a vector normal to both.
ObjectModelPlaneFromLines ()
virtual ~ObjectModelPlaneFromLines ()
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXf &model_coefficients)
void computeRandomModel (int &iterations, Eigen::VectorXf &model_coefficients, bool &isDegenerate, bool &modelFound)
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Static Protected Attributes
static const double geometryEpsilon = 1e-3
Used to check if a number is small enough to be considered to be 0.
Detailed Description
Finds a plane model from two 3D line segments in the data.
Note:
The implementation is reusing the object model implementation in MRPT
Definition at line 31 of file ObjectModelPlaneFromLines.h.
Constructor & Destructor Documentation
brics_3d::ObjectModelPlaneFromLines::ObjectModelPlaneFromLines () [inline]
Definition at line 85 of file ObjectModelPlaneFromLines.h.
virtual brics_3d::ObjectModelPlaneFromLines::~ObjectModelPlaneFromLines () [inline, virtual]
Definition at line 86 of file ObjectModelPlaneFromLines.h.
Member Function Documentation
bool brics_3d::ObjectModelPlaneFromLines::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXf & model_coefficients)
Definition at line 139 of file ObjectModelPlaneFromLines.cpp.
References contains(), crossProduct3D(), brics_3d::ObjectModelPlaneFromLines::line::director, geometryEpsilon, brics_3d::PointCloud3D::getPointCloud(), brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), brics_3d::IObjectModel::inputPointCloud, brics_3d::ObjectModelPlaneFromLines::line::pbase, and brics_3d::x.
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelPlaneFromLines cpp void brics_3d::ObjectModelPlaneFromLines::computeRandomModel (int & iterations, Eigen::VectorXf & model_coefficients, bool & isDegenerate, bool & modelFound)
Definition at line 25 of file ObjectModelPlaneFromLines.cpp.
bool brics_3d::ObjectModelPlaneFromLines::contains (const line & line, Point3D & point) [inline]
Checks if a line contains a point or not.
Definition at line 47 of file ObjectModelPlaneFromLines.h.
References brics_3d::ObjectModelPlaneFromLines::line::director, geometryEpsilon, brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), and brics_3d::ObjectModelPlaneFromLines::line::pbase.
Referenced by computeModelCoefficients().
void brics_3d::ObjectModelPlaneFromLines::crossProduct3D (const std::vector< double > & v0, const std::vector< double > & v1, std::vector< double > & v_out) [inline]
Computes the cross product of two 3D vectors, returning a vector normal to both.
It uses the simple implementation:
Definition at line 74 of file ObjectModelPlaneFromLines.h.
Referenced by computeModelCoefficients().
int brics_3d::ObjectModelPlaneFromLines::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Reimplemented from brics_3d::ObjectModelPlane.
Definition at line 90 of file ObjectModelPlaneFromLines.h.
void brics_3d::ObjectModelPlaneFromLines::getSamples (int & iterations, std::vector< int > & samples)
Reimplemented from brics_3d::ObjectModelPlane.
Definition at line 52 of file ObjectModelPlaneFromLines.cpp.
Member Data Documentation
const double brics_3d::ObjectModelPlaneFromLines::geometryEpsilon = 1e-3 [static, protected]
Used to check if a number is small enough to be considered to be 0.
Definition at line 34 of file ObjectModelPlaneFromLines.h.
Referenced by computeModelCoefficients(), and contains().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelPlaneFromLines.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelPlaneFromLines.cpp