BRICS_RN_Robust_Navigation_Library(BRICS_RN): OmniDriveKinematicsModel Class Reference
OmniDriveKinematicsModel Class Reference
#include <OmniDriveKinematicsModel.h>
Public Member Functions
OmniDriveKinematicsModel ()
OmniDriveKinematicsModel (const OmniDriveKinematicsModel &orig)
virtual ~OmniDriveKinematicsModel ()
void convertToLocalReferenceFrame (const Odometry &globalFrame, Odometry &localFrame)
void convertToGlobalReferenceFrame (const Odometry &localFrame, Odometry &globalFrame)
Private Member Functions
void convert (const double &x1, const double &y1, const double &theta, double &x2, double &y2, bool inverse)
Detailed Description
Definition at line 47 of file OmniDriveKinematicsModel.h.
Constructor & Destructor Documentation
OmniDriveKinematicsModel::OmniDriveKinematicsModel ()
Definition at line 45 of file OmniDriveKinematicsModel.cpp.
OmniDriveKinematicsModel::OmniDriveKinematicsModel (const OmniDriveKinematicsModel & orig)
Definition at line 48 of file OmniDriveKinematicsModel.cpp.
OmniDriveKinematicsModel::~OmniDriveKinematicsModel () [virtual]
Definition at line 51 of file OmniDriveKinematicsModel.cpp.
Member Function Documentation
void OmniDriveKinematicsModel::convert (const double & x1, const double & y1, const double & theta, double & x2, double & y2, bool inverse) [private]
Definition at line 54 of file OmniDriveKinematicsModel.cpp.
Referenced by convertToGlobalReferenceFrame(), and convertToLocalReferenceFrame().
void OmniDriveKinematicsModel::convertToGlobalReferenceFrame (const Odometry & localFrame, Odometry & globalFrame) [virtual]
Implements IKinematicsModel.
Definition at line 88 of file OmniDriveKinematicsModel.cpp.
References convert(), Odometry::getPose2D(), Twist2D::getTheta(), Pose2D::getTheta(), Odometry::getTwist2D(), Twist2D::getX(), Pose2D::getX(), Twist2D::getY(), and Pose2D::getY().
void OmniDriveKinematicsModel::convertToLocalReferenceFrame (const Odometry & globalFrame, Odometry & localFrame) [virtual]
Implements IKinematicsModel.
Definition at line 62 of file OmniDriveKinematicsModel.cpp.
References convert(), Odometry::getPose2D(), Twist2D::getTheta(), Pose2D::getTheta(), Odometry::getTwist2D(), Twist2D::getX(), Pose2D::getX(), Twist2D::getY(), and Pose2D::getY().
Referenced by OmniDrivePositionController::computeNewOdometry().
The documentation for this class was generated from the following files:
navigation_trajectory_follower/src/omnidrive_controller/OmniDriveKinematicsModel.h
navigation_trajectory_follower/src/omnidrive_controller/OmniDriveKinematicsModel.cpp