BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelPlaneFromLineAndPoint Class Reference
brics_3d::ObjectModelPlaneFromLineAndPoint Class Reference
Segmentation
#include <ObjectModelPlaneFromLineAndPoint.h>
Classes
struct line
Public Member Functions
ObjectModelPlaneFromLineAndPoint ()
virtual ~ObjectModelPlaneFromLineAndPoint ()
bool contains (const line &line, Point3D &point)
Checks if a line contains a point or not.
void crossProduct3D (const std::vector< double > &v0, const std::vector< double > &v1, std::vector< double > &v_out)
Computes the cross product of two 3D vectors, returning a vector normal to both.
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXf &model_coefficients)
void computeRandomModel (int &iterations, Eigen::VectorXf &model_coefficients, bool &isDegenerate, bool &modelFound)
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Static Protected Attributes
static const double geometryEpsilon = 1e-3
Used to check if a number is small enough to be considered to be 0.
Detailed Description
Note:
The implementation is reusing the object model implementation in MRPT
Definition at line 31 of file ObjectModelPlaneFromLineAndPoint.h.
Constructor & Destructor Documentation
brics_3d::ObjectModelPlaneFromLineAndPoint::ObjectModelPlaneFromLineAndPoint () [inline]
Definition at line 39 of file ObjectModelPlaneFromLineAndPoint.h.
virtual brics_3d::ObjectModelPlaneFromLineAndPoint::~ObjectModelPlaneFromLineAndPoint () [inline, virtual]
Definition at line 40 of file ObjectModelPlaneFromLineAndPoint.h.
Member Function Documentation
bool brics_3d::ObjectModelPlaneFromLineAndPoint::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXf & model_coefficients)
Definition at line 120 of file ObjectModelPlaneFromLineAndPoint.cpp.
References brics_3d::ObjectModelPlaneFromLineAndPoint::line::director, geometryEpsilon, brics_3d::PointCloud3D::getPointCloud(), brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), brics_3d::IObjectModel::inputPointCloud, and brics_3d::ObjectModelPlaneFromLineAndPoint::line::pbase.
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelPlaneFromLineAndPoint cpp void brics_3d::ObjectModelPlaneFromLineAndPoint::computeRandomModel (int & iterations, Eigen::VectorXf & model_coefficients, bool & isDegenerate, bool & modelFound)
Definition at line 26 of file ObjectModelPlaneFromLineAndPoint.cpp.
bool brics_3d::ObjectModelPlaneFromLineAndPoint::contains (const line & line, Point3D & point) [inline]
Checks if a line contains a point or not.
Definition at line 49 of file ObjectModelPlaneFromLineAndPoint.h.
References brics_3d::ObjectModelPlaneFromLineAndPoint::line::director, geometryEpsilon, brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), and brics_3d::ObjectModelPlaneFromLineAndPoint::line::pbase.
void brics_3d::ObjectModelPlaneFromLineAndPoint::crossProduct3D (const std::vector< double > & v0, const std::vector< double > & v1, std::vector< double > & v_out) [inline]
Computes the cross product of two 3D vectors, returning a vector normal to both.
It uses the simple implementation:
Definition at line 76 of file ObjectModelPlaneFromLineAndPoint.h.
int brics_3d::ObjectModelPlaneFromLineAndPoint::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Reimplemented from brics_3d::ObjectModelPlane.
Definition at line 91 of file ObjectModelPlaneFromLineAndPoint.h.
void brics_3d::ObjectModelPlaneFromLineAndPoint::getSamples (int & iterations, std::vector< int > & samples)
Reimplemented from brics_3d::ObjectModelPlane.
Definition at line 53 of file ObjectModelPlaneFromLineAndPoint.cpp.
Member Data Documentation
const double brics_3d::ObjectModelPlaneFromLineAndPoint::geometryEpsilon = 1e-3 [static, protected]
Used to check if a number is small enough to be considered to be 0.
Definition at line 34 of file ObjectModelPlaneFromLineAndPoint.h.
Referenced by computeModelCoefficients(), and contains().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelPlaneFromLineAndPoint.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelPlaneFromLineAndPoint.cpp