BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::NormalEstimation Class Reference
brics_3d::NormalEstimation Class Reference
#include <NormalEstimation.h>
Public Member Functions
NormalEstimation ()
~NormalEstimation ()
INearestPoint3DNeighbor * getNNSearchMethod ()
Get the nearst neighborhood search method.
void setSearchMethod (INearestPoint3DNeighbor *nnSearchMethod)
Set the nearst neighborhood search method.
void setInputCloud (PointCloud3D *cloud)
Provide a pointer to the input dataset.
PointCloud3D * getInputCloud ()
Get a pointer to the input point cloud dataset.
void setkneighbours (int kNeighbours)
Set the number of nearest neighbours to be used.
int getkneighbours ()
Get the number of nearest neighbours to be used.
void compute4DCentroid (PointCloud3D *cloud, Eigen::Vector4d &centroid)
Compute the 3D (X-Y-Z) centroid of a set of points using their indices and return it as a 3D vector.
void setViewPoint (double vpx, double vpy, double vpz)
Set the viewpoint.
void getViewPoint (double &vpx, double &vpy, double &vpz)
Get the viewpoint.
void computeFeature (NormalSet3D *normalSet)
Estimate normals for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
void flipNormalTowardsViewpoint (Point3D &point, double vp_x, double vp_y, double vp_z, Normal3D &normal)
Flip (in place) the estimated normal of a point towards a given viewpoint.
Private Attributes
double vpx
Values describing the viewpoint ("pinhole" camera model assumed).
double vpy
double vpz
int k_neighbours
Number of k-nearest neighbours to be used.
PointCloud3D * inputPointCloud
Represents the point-cloud to be processed.
INearestPoint3DNeighbor * nnSearchMethod
Nearest neighbour searching method.
Detailed Description
Definition at line 31 of file NormalEstimation.h.
Constructor & Destructor Documentation
brics_3d::NormalEstimation::NormalEstimation () [inline]
Definition at line 48 of file NormalEstimation.h.
References k_neighbours, vpx, vpy, and vpz.
brics_3d::NormalEstimation::~NormalEstimation () [inline]
Definition at line 56 of file NormalEstimation.h.
Member Function Documentation
void brics_3d::NormalEstimation::compute4DCentroid (PointCloud3D * cloud, Eigen::Vector4d & centroid) [inline]
Compute the 3D (X-Y-Z) centroid of a set of points using their indices and return it as a 3D vector.
Parameters:
cloud the input point cloud
indices the point cloud indices that need to be used
centroid the output centroid
Definition at line 109 of file NormalEstimation.h.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::x.
void brics_3d::NormalEstimation::computeFeature (NormalSet3D * normalSet) [inline]
Estimate normals for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Note:
In situations where not enough neighbors are found, the normal and curvature values are set to -1.
Parameters:
output the resultant point cloud model dataset that contains surface normals and curvatures
Definition at line 162 of file NormalEstimation.h.
References brics_3d::NormalSet3D::addNormal(), brics_3d::computePointNormal(), brics_3d::INearestPoint3DNeighbor::findNearestNeighbors(), flipNormalTowardsViewpoint(), brics_3d::NormalSet3D::getNormals(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), inputPointCloud, k_neighbours, nnSearchMethod, brics_3d::INearestPoint3DNeighbor::setData(), brics_3d::Vector3D::setX(), brics_3d::Vector3D::setY(), brics_3d::Vector3D::setZ(), vpx, vpy, and vpz.
void brics_3d::NormalEstimation::flipNormalTowardsViewpoint (Point3D & point, double vp_x, double vp_y, double vp_z, Normal3D & normal) [inline]
Flip (in place) the estimated normal of a point towards a given viewpoint.
Parameters:
point a given point
vp_x the X coordinate of the viewpoint
vp_y the X coordinate of the viewpoint
vp_z the X coordinate of the viewpoint
normal the plane normal to be flipped
Definition at line 215 of file NormalEstimation.h.
References brics_3d::Vector3D::getX(), brics_3d::Point3D::getX(), brics_3d::Vector3D::getY(), brics_3d::Point3D::getY(), brics_3d::Vector3D::getZ(), brics_3d::Point3D::getZ(), brics_3d::Vector3D::setX(), brics_3d::Vector3D::setY(), and brics_3d::Vector3D::setZ().
Referenced by computeFeature().
PointCloud3D* brics_3d::NormalEstimation::getInputCloud () [inline]
Get a pointer to the input point cloud dataset.
Definition at line 86 of file NormalEstimation.h.
References inputPointCloud.
int brics_3d::NormalEstimation::getkneighbours () [inline]
Get the number of nearest neighbours to be used.
Definition at line 99 of file NormalEstimation.h.
References k_neighbours.
INearestPoint3DNeighbor* brics_3d::NormalEstimation::getNNSearchMethod () [inline]
Get the nearst neighborhood search method.
Definition at line 61 of file NormalEstimation.h.
References nnSearchMethod.
void brics_3d::NormalEstimation::getViewPoint (double & vpx, double & vpy, double & vpz) [inline]
Get the viewpoint.
Definition at line 147 of file NormalEstimation.h.
References vpx, vpy, and vpz.
void brics_3d::NormalEstimation::setInputCloud (PointCloud3D * cloud) [inline]
Provide a pointer to the input dataset.
Parameters:
cloud the const boost shared pointer to a PointCloud message
Definition at line 80 of file NormalEstimation.h.
References inputPointCloud.
void brics_3d::NormalEstimation::setkneighbours (int kNeighbours) [inline]
Set the number of nearest neighbours to be used.
Parameters:
k_neighbours,: The number of neighbours to be used
Definition at line 92 of file NormalEstimation.h.
References k_neighbours.
void brics_3d::NormalEstimation::setSearchMethod (INearestPoint3DNeighbor * nnSearchMethod) [inline]
Set the nearst neighborhood search method.
Definition at line 69 of file NormalEstimation.h.
References inputPointCloud, nnSearchMethod, and brics_3d::INearestPoint3DNeighbor::setData().
void brics_3d::NormalEstimation::setViewPoint (double vpx, double vpy, double vpz) [inline]
Set the viewpoint.
Parameters:
vpx the X coordinate of the viewpoint
vpy the Y coordinate of the viewpoint
vpz the Z coordinate of the viewpoint
Definition at line 137 of file NormalEstimation.h.
References vpx, vpy, and vpz.
Member Data Documentation
PointCloud3D* brics_3d::NormalEstimation::inputPointCloud [private]
Represents the point-cloud to be processed.
Definition at line 43 of file NormalEstimation.h.
Referenced by computeFeature(), getInputCloud(), setInputCloud(), and setSearchMethod().
int brics_3d::NormalEstimation::k_neighbours [private]
Number of k-nearest neighbours to be used.
Definition at line 40 of file NormalEstimation.h.
Referenced by computeFeature(), getkneighbours(), NormalEstimation(), and setkneighbours().
INearestPoint3DNeighbor* brics_3d::NormalEstimation::nnSearchMethod [private]
Nearest neighbour searching method.
Definition at line 46 of file NormalEstimation.h.
Referenced by computeFeature(), getNNSearchMethod(), and setSearchMethod().
double brics_3d::NormalEstimation::vpx [private]
Values describing the viewpoint ("pinhole" camera model assumed).
For per point viewpoints, inherit from NormalEstimation and provide your own computeFeature (). By default, the viewpoint is set to 0,0,0.
Definition at line 37 of file NormalEstimation.h.
Referenced by computeFeature(), getViewPoint(), NormalEstimation(), and setViewPoint().
double brics_3d::NormalEstimation::vpy [private]
Definition at line 37 of file NormalEstimation.h.
Referenced by computeFeature(), getViewPoint(), NormalEstimation(), and setViewPoint().
double brics_3d::NormalEstimation::vpz [private]
Definition at line 37 of file NormalEstimation.h.
Referenced by computeFeature(), getViewPoint(), NormalEstimation(), and setViewPoint().
The documentation for this class was generated from the following file:
src/brics_3d/algorithm/segmentation/features/NormalEstimation.h