BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::TriangleMeshImplicit Class Reference
brics_3d::TriangleMeshImplicit Class Reference
Implicit triangle mesh representation.
#include <TriangleMeshImplicit.h>
Public Member Functions
TriangleMeshImplicit ()
Standard constructor.
virtual ~TriangleMeshImplicit ()
Standard destructor.
std::vector< Point3D > * getVertices ()
Get the pointer to the vertices To get access to the vertices of the mesh, prefer getTriangleVertex(), as that function is more generic and complies to the ITriangleMesh interface.
void setVertices (std::vector< Point3D > *vertices)
Set the pointer to the vertices.
std::vector< int > * getIndices ()
Get the pointer to the vertex indices To get access to the vertices of the mesh, prefer getTriangleVertex(), as that function is more generic and complies to the ITriangleMesh interface.
void setIndices (std::vector< int > *indices)
Set the pointer to the indices.
int getSize ()
Get the number of triangles in the mesh.
int getNumberOfVertices ()
Get the number of vertices in the mesh.
Point3D * getTriangleVertex (int triangleIndex, int vertexIndex)
Get a vertex that belongs to a triangle.
int addTriangle (Point3D vertex1, Point3D vertex2, Point3D vertex3)
Add a new triangle to the mesh.
void removeTriangle (int triangleIndex)
Remove a triangle from the mesh NOTE: depending on the implementation of the triangle mesh, this might be a costly operation, as indices list might have to be updated.
void homogeneousTransformation (IHomogeneousMatrix44 *transformation)
Applies a homogeneous transformation to the mesh.
Protected Attributes
std::vector< Point3D > * vertices
Pointer to vector with vertices.
std::vector< int > * indices
Pointer to vector with indices.
Private Member Functions
void read (std::istream &inStream)
Helper function for streaming input.
void write (std::ostream &outStream)
Helper function for streaming output.
Detailed Description
Implicit triangle mesh representation.
Definition at line 31 of file TriangleMeshImplicit.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d core TriangleMeshImplicit cpp brics_3d::TriangleMeshImplicit::TriangleMeshImplicit ()
Standard constructor.
Definition at line 26 of file TriangleMeshImplicit.cpp.
brics_3d::TriangleMeshImplicit::~TriangleMeshImplicit () [virtual]
Standard destructor.
Definition at line 34 of file TriangleMeshImplicit.cpp.
References vertices.
Member Function Documentation
int brics_3d::TriangleMeshImplicit::addTriangle (Point3D vertex1, Point3D vertex2, Point3D vertex3) [virtual]
Add a new triangle to the mesh.
NOTE: The semantics on how a triangle is inserted depends on the actual implementation of this interface.
Parameters:
vertex1 First vertex that represents the triangle
vertex2 Second vertex that represents the triangle
vertex3 Third vertex that represents the triangle
Returns:
Returns the triangle index where it is stored
Implements brics_3d::ITriangleMesh.
Definition at line 91 of file TriangleMeshImplicit.cpp.
std::vector< int > * brics_3d::TriangleMeshImplicit::getIndices ()
Get the pointer to the vertex indices To get access to the vertices of the mesh, prefer getTriangleVertex(), as that function is more generic and complies to the ITriangleMesh interface.
Returns:
Pointer to indices
Definition at line 60 of file TriangleMeshImplicit.cpp.
Referenced by brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh().
int brics_3d::TriangleMeshImplicit::getNumberOfVertices () [virtual]
Get the number of vertices in the mesh.
Returns:
Returns the number of vertices in the mesh. The output depends on the underlying representation!
Implements brics_3d::ITriangleMesh.
Definition at line 79 of file TriangleMeshImplicit.cpp.
Referenced by brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh().
int brics_3d::TriangleMeshImplicit::getSize () [virtual]
Get the number of triangles in the mesh.
Implements brics_3d::ITriangleMesh.
Definition at line 74 of file TriangleMeshImplicit.cpp.
Referenced by brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh().
Point3D * brics_3d::TriangleMeshImplicit::getTriangleVertex (int triangleIndex, int vertexIndex) [virtual]
Get a vertex that belongs to a triangle.
Parameters:
triangleIndex The index of a triangle. The fist triangle has index 0, the second has 1 and so on... The valid range is [0, getSize()]
vertexIndex The index of a vertex the belongs to the triangle, specified by the triangleIndex. The valid range is [0, 2]
Returns:
Returns a pointer to the vertex
Implements brics_3d::ITriangleMesh.
Definition at line 83 of file TriangleMeshImplicit.cpp.
std::vector< Point3D > * brics_3d::TriangleMeshImplicit::getVertices ()
Get the pointer to the vertices To get access to the vertices of the mesh, prefer getTriangleVertex(), as that function is more generic and complies to the ITriangleMesh interface.
Returns:
Pointer to vertices
Definition at line 46 of file TriangleMeshImplicit.cpp.
Referenced by brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh().
void brics_3d::TriangleMeshImplicit::homogeneousTransformation (IHomogeneousMatrix44 * transformation) [virtual]
Applies a homogeneous transformation to the mesh.
Parameters:
[in] transformation The homogeneous transformation matrix that will be applied
Implements brics_3d::ITriangleMesh.
Definition at line 111 of file TriangleMeshImplicit.cpp.
void brics_3d::TriangleMeshImplicit::read (std::istream & inStream) [private, virtual]
Helper function for streaming input.
This function enforces that streaming functionality is implemented in derived classes. This is necessaray as the operator>> cannot be inherited (as it is already a friend)
Parameters:
[in,out] inStream The input stream
Returns:
Input stream
Implements brics_3d::ITriangleMesh.
Definition at line 117 of file TriangleMeshImplicit.cpp.
void brics_3d::TriangleMeshImplicit::removeTriangle (int triangleIndex) [virtual]
Remove a triangle from the mesh NOTE: depending on the implementation of the triangle mesh, this might be a costly operation, as indices list might have to be updated.
Parameters:
triangleIndex The index of a triangle. The fist triangle has index 0, the second has 1 and so on... The valid range is [0, getSize()]
Implements brics_3d::ITriangleMesh.
Definition at line 106 of file TriangleMeshImplicit.cpp.
void brics_3d::TriangleMeshImplicit::setIndices (std::vector< int > * indices)
Set the pointer to the indices.
Parameters:
indices Pointer to new index set
Definition at line 65 of file TriangleMeshImplicit.cpp.
References indices.
void brics_3d::TriangleMeshImplicit::setVertices (std::vector< Point3D > * vertices)
Set the pointer to the vertices.
Parameters:
vertices Pointer to new vertex set
Definition at line 51 of file TriangleMeshImplicit.cpp.
References vertices.
void brics_3d::TriangleMeshImplicit::write (std::ostream & outStream) [private, virtual]
Helper function for streaming output.
This function enforces that streaming functionality is implemented in derived classes. This is necessary as the operator<< cannot be inherited (as it is already a friend)
Parameters:
[in,out] outStream The output stream
Returns:
Output stream
Implements brics_3d::ITriangleMesh.
Definition at line 121 of file TriangleMeshImplicit.cpp.
Member Data Documentation
std::vector<int>* brics_3d::TriangleMeshImplicit::indices [protected]
Pointer to vector with indices.
The -th triangle is defined as a triple of the following indices:
Definition at line 95 of file TriangleMeshImplicit.h.
Referenced by setIndices().
std::vector<Point3D>* brics_3d::TriangleMeshImplicit::vertices [protected]
Pointer to vector with vertices.
Definition at line 89 of file TriangleMeshImplicit.h.
Referenced by setVertices(), and ~TriangleMeshImplicit().
The documentation for this class was generated from the following files:
src/brics_3d/core/TriangleMeshImplicit.h
src/brics_3d/core/TriangleMeshImplicit.cpp