BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::INearestPoint3DNeighbor Class Reference
brics_3d::INearestPoint3DNeighbor Class Reference
NearestNeighbor
Abstract interface for the nearest neighbor search algorithm for 3D points.
#include <INearestPoint3DNeighbor.h>
Public Member Functions
INearestPoint3DNeighbor ()
Standard constructor.
virtual ~INearestPoint3DNeighbor ()
Standard destructor.
virtual void setData (PointCloud3D *data)=0
Set the data.
virtual void findNearestNeighbors (Point3D *query, std::vector< int > *resultIndices, unsigned int k=1)=0
Find the nearest neighbor point of the query with respect to the data point cloud.
Detailed Description
Abstract interface for the nearest neighbor search algorithm for 3D points.
The interface INearestPoint3DNeighbor is specific to the 3D perception and modeling domain, as it uses Cartesian points.
Definition at line 38 of file INearestPoint3DNeighbor.h.
Constructor & Destructor Documentation
brics_3d::INearestPoint3DNeighbor::INearestPoint3DNeighbor () [inline]
Standard constructor.
Definition at line 44 of file INearestPoint3DNeighbor.h.
virtual brics_3d::INearestPoint3DNeighbor::~INearestPoint3DNeighbor () [inline, virtual]
Standard destructor.
Definition at line 49 of file INearestPoint3DNeighbor.h.
Member Function Documentation
virtual void brics_3d::INearestPoint3DNeighbor::findNearestNeighbors (Point3D * query, std::vector< int > * resultIndices, unsigned int k = 1) [pure virtual]
Find the nearest neighbor point of the query with respect to the data point cloud.
Parameters:
[in] query Point that will be queried to the data.
[out] resultIndices Returns the indices of the $k$ nearest neighbors with respect to the data point cloud. If the nearest neighbor exceeds the maximum distance the returned vector will be empty.
[in] k Sets how many nearest neighbors will be searched.
NOTE: setData() must be invoked before.
Implemented in brics_3d::NearestNeighborANN, brics_3d::NearestNeighborFLANN, and brics_3d::NearestNeighborSTANN.
Referenced by brics_3d::NormalEstimation::computeFeature(), and brics_3d::PointCorrespondenceGenericNN::createNearestNeighborCorrespondence().
virtual void brics_3d::INearestPoint3DNeighbor::setData (PointCloud3D * data) [pure virtual]
Set the data.
Parameters:
[in] data Data is represented as a PointCloud3D.
Implemented in brics_3d::NearestNeighborANN, brics_3d::NearestNeighborFLANN, and brics_3d::NearestNeighborSTANN.
Referenced by brics_3d::NormalEstimation::computeFeature(), brics_3d::PointCorrespondenceGenericNN::createNearestNeighborCorrespondence(), and brics_3d::NormalEstimation::setSearchMethod().
The documentation for this class was generated from the following file:
src/brics_3d/algorithm/nearestNeighbor/INearestPoint3DNeighbor.h