BRICS_RN (Robust Navigation Library): TwistWithId Class Reference
TwistWithId Class Reference
TwistWithId is an aggregation of KDL::Twist class with a std::string as frame id.
#include <TwistWithId.h>
Public Member Functions
TwistWithId ()
Default Constructor.
TwistWithId (const KDL::Twist &twist)
Constructor.
TwistWithId (const std::string &id)
Constructor.
TwistWithId (const KDL::Twist &twist, const std::string &id)
Constructor.
TwistWithId (const TwistWithId &orig)
Copy constructor.
const TwistWithId & operator= (const TwistWithId &orig)
Operation assignment.
virtual ~TwistWithId ()
Destructor.
void setTwist (const KDL::Twist &twist)
Sets a new value of the KDL::Twist.
const KDL::Twist & getTwist () const
Get an underlying KDL twist as a const reference or a copy.
KDL::Twist & getTwist ()
Get an underlying KDL trajectory as a reference.
Public Attributes
std::string id
String identifier of the Twist.
Private Attributes
KDL::Twist * twist
Aggregation of the KDL::Twist.
Detailed Description
TwistWithId is an aggregation of KDL::Twist class with a std::string as frame id.
The embedded KDL::Frame will be always heap-allocated.
Definition at line 54 of file TwistWithId.h.
Constructor & Destructor Documentation
TwistWithId::TwistWithId ()
Default Constructor.
Definition at line 46 of file TwistWithId.cpp.
TwistWithId::TwistWithId (const KDL::Twist & twist)
Constructor.
The embedded id is set to the empty string.
Parameters
[in] twist - initial value of KDL::Twist.
Definition at line 56 of file TwistWithId.cpp.
TwistWithId::TwistWithId (const std::string & id)
Constructor.
The embedded KDL::Twist in initialized by its default constructor.
Parameters
[in] is - initial value of twist identifier.
Definition at line 51 of file TwistWithId.cpp.
TwistWithId::TwistWithId (const KDL::Twist & twist, const std::string & id)
Constructor.
Parameters
[in] twist - initial value of KDL::Twist.
[in] is - initial value of twist identifier.
Definition at line 61 of file TwistWithId.cpp.
TwistWithId::TwistWithId (const TwistWithId & orig)
Copy constructor.
Parameters
[in] orig - reference to the original object
Definition at line 66 of file TwistWithId.cpp.
References getTwist(), and id.
TwistWithId::~TwistWithId () virtual
Destructor.
Definition at line 92 of file TwistWithId.cpp.
Member Function Documentation
const KDL::Twist & TwistWithId::getTwist () const
Get an underlying KDL twist as a const reference or a copy.
Modifications on the TwistWithId, except assignment or setTwist(), will be reflected by the returned reference.
Assigning or setting a new twist invalidates all references obtained from const KDL::Twist& getTwist() const.
Definition at line 84 of file TwistWithId.cpp.
Referenced by conversions::odometryRosToTwist(), operator=(), and TwistWithId().
KDL::Twist & TwistWithId::getTwist ()
Get an underlying KDL trajectory as a reference.
Modifications on the TwistWithId, except assignment or setTwist(), will be reflected by the returned reference.
Assigning or setting a new twist invalidates all references obtained from const KDL::Twist& getTwist() const.
Definition at line 88 of file TwistWithId.cpp.
const TwistWithId & TwistWithId::operator= (const TwistWithId & orig)
Operation assignment.
Parameters
[in] orig - reference to the original object
Definition at line 71 of file TwistWithId.cpp.
References getTwist(), and id.
void TwistWithId::setTwist (const KDL::Twist & twist)
Sets a new value of the KDL::Twist.
The supplied KDL::Twist twist is copied and can be delete or modified without affecting the TwistWithId instance. The id member is not modified.
Parameters
[in] twist - new value of KDL::Twist.
Definition at line 79 of file TwistWithId.cpp.
Member Data Documentation
std::string TwistWithId::id
String identifier of the Twist.
Definition at line 59 of file TwistWithId.h.
Referenced by conversions::odometryRosToTwist(), operator=(), and TwistWithId().
KDL::Twist* TwistWithId::twist private
Aggregation of the KDL::Twist.
Definition at line 150 of file TwistWithId.h.
The documentation for this class was generated from the following files:
navigation_trajectory_common/include/navigation_trajectory_common/TwistWithId.h
navigation_trajectory_common/src/TwistWithId.cpp