BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::ISceneGraphUpdate Class Reference
brics_3d::rsg::ISceneGraphUpdate Class Reference
Scenegraph
Abstract interface for all scene graph related update functions.
#include <ISceneGraphUpdate.h>
Public Member Functions
virtual bool addNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)=0
Add a new Node to the robot scene graph.
virtual bool addGroup (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)=0
Add a Group node to the robot scenegraph.
virtual bool addTransformNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId=false)=0
Add a new Transform node the the robot scene graph.
virtual bool addGeometricNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId=false)=0
Add a GeometricNode that contains 3D data to the robot scene graph.
virtual bool setNodeAttributes (unsigned int id, vector< Attribute > newAttributes)=0
Override the attributes of a node.
virtual bool setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp)=0
Update the transformation of an existing Transform node.
virtual bool deleteNode (unsigned int id)=0
Delete a node in the robot scenegraph.
virtual bool addParent (unsigned int id, unsigned int parentId)=0
Add a new parent-child relation between two nodes.
Detailed Description
Abstract interface for all scene graph related update functions.
Definition at line 39 of file ISceneGraphUpdate.h.
Member Function Documentation
virtual bool brics_3d::rsg::ISceneGraphUpdate::addGeometricNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId = false) [pure virtual]
Add a GeometricNode that contains 3D data to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
shape The geometic Shape to be contained the the GeometricNode. Multiple shape types are possible like a Box, a Cylinder a Mesh or a PointCloud for instance.
timeStamp Time stamp assiciated with the geometic Shape.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new GeometricNode was sucessfully added to the scen egraph.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
virtual bool brics_3d::rsg::ISceneGraphUpdate::addGroup (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [pure virtual]
Add a Group node to the robot scenegraph.
The group allows to create the graph structure as it has children, in contrast to a simple node.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Group was sucessfully added to the scene graph.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
virtual bool brics_3d::rsg::ISceneGraphUpdate::addNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [pure virtual]
Add a new Node to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Node was sucessfully added to the scene graph.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
virtual bool brics_3d::rsg::ISceneGraphUpdate::addParent (unsigned int id, unsigned int parentId) [pure virtual]
Add a new parent-child relation between two nodes.
Parameters:
id ID of the node
parentId ID of the parent node. Must not be a leave like a Node or a GeometricNode
Returns:
True on success.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::handleExistingNode().
virtual bool brics_3d::rsg::ISceneGraphUpdate::addTransformNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId = false) [pure virtual]
Add a new Transform node the the robot scene graph.
Internally brics_3d::rsg::Transform is used that is able to maintain a temporal cache of the trnasform data.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
transform The actual transform data that will be (initially) inserted. You can later insert more with brics_3d::rsg::ISceneGraphUpdate::setTransform() .
timeStamp Time stamp associated with the transform.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Transform was sucessfully added to the scene graph.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
virtual bool brics_3d::rsg::ISceneGraphUpdate::deleteNode (unsigned int id) [pure virtual]
Delete a node in the robot scenegraph.
Parameters:
id ID the defines the node to be deleted.
Returns:
True on success.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
virtual bool brics_3d::rsg::ISceneGraphUpdate::setNodeAttributes (unsigned int id, vector< Attribute > newAttributes) [pure virtual]
Override the attributes of a node.
Parameters:
id ID the defines the node to be updated.
newAttributes The new attributes. THe old one will be overidden by tis
Returns:
True on success.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
virtual bool brics_3d::rsg::ISceneGraphUpdate::setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp) [pure virtual]
Update the transformation of an existing Transform node.
Parameters:
id ID the defines the Transform node to be updated.
transform The transform data that will be inserted in to the cacje of the Transform.
timeStamp Time stamp associated with the transform.
Returns:
True on success.
Implemented in brics_3d::rsg::DotVisualizer, brics_3d::rsg::OSGVisualizer, and brics_3d::rsg::SceneGraphFacade.
The documentation for this class was generated from the following file:
src/brics_3d/worldModel/sceneGraph/ISceneGraphUpdate.h