BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::NormalSet3D Class Reference
brics_3d::NormalSet3D Class Reference
Class to represent a set of 3D normals.
#include <NormalSet3D.h>
Public Member Functions
NormalSet3D ()
Standard constructor.
virtual ~NormalSet3D ()
Standard destructor.
void addNormal (Normal3D normal)
Add a normal to the the normal set.
std::vector< Normal3D > * getNormals ()
Get the pointer to the normals.
unsigned int getSize ()
Get the number of normals in the normal set.
Protected Attributes
std::vector< Normal3D > * normals
Detailed Description
Class to represent a set of 3D normals.
Definition at line 31 of file NormalSet3D.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d core NormalSet3D cpp brics_3d::NormalSet3D::NormalSet3D ()
Standard constructor.
Definition at line 25 of file NormalSet3D.cpp.
brics_3d::NormalSet3D::~NormalSet3D () [virtual]
Standard destructor.
Definition at line 31 of file NormalSet3D.cpp.
References normals.
Member Function Documentation
void brics_3d::NormalSet3D::addNormal (Normal3D normal)
Add a normal to the the normal set.
Parameters:
point Normal that will be added
Definition at line 38 of file NormalSet3D.cpp.
Referenced by brics_3d::NormalEstimation::computeFeature().
std::vector< Normal3D > * brics_3d::NormalSet3D::getNormals ()
Get the pointer to the normals.
Returns:
Pointer to the normals
Definition at line 43 of file NormalSet3D.cpp.
Referenced by brics_3d::NormalEstimation::computeFeature(), brics_3d::ObjectModelCylinder::computeModelCoefficients(), brics_3d::ObjectModelNormalPlane::getDistancesToModel(), brics_3d::ObjectModelCylinder::getInlierDistance(), and brics_3d::ObjectModelCylinder::selectWithinDistance().
unsigned int brics_3d::NormalSet3D::getSize ()
Get the number of normals in the normal set.
Returns:
Size of normals set (= number of stored normals)
Definition at line 48 of file NormalSet3D.cpp.
Referenced by brics_3d::ObjectModelCylinder::computeModelCoefficients(), brics_3d::ObjectModelNormalPlane::getDistancesToModel(), and brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
Member Data Documentation
std::vector<Normal3D>* brics_3d::NormalSet3D::normals [protected]
Definition at line 65 of file NormalSet3D.h.
Referenced by ~NormalSet3D().
The documentation for this class was generated from the following files:
src/brics_3d/core/NormalSet3D.h
src/brics_3d/core/NormalSet3D.cpp