BRICS_RN (Robust Navigation Library): Pose2D Class Reference
Pose2D Class Reference
Class represents pose 2D data.
#include <Pose2D.h>
Public Member Functions
Pose2D ()
Constructor.
Pose2D (float x, float y, float theta)
Constructor.
Pose2D (const Pose2D &orig)
Copy constructor.
virtual ~Pose2D ()
Destructor.
const Pose2D & operator= (const Pose2D &orig)
Assignment.
float getX () const
Getting x coordinate.
float getY () const
Getting y coordinate.
float getTheta () const
Getting theta angle.
Private Attributes
float x
x coordinate.
float y
y coordinate.
float theta
theta coordinate.
Friends
Pose2D operator+ (const Pose2D &op1, const Pose2D &op2)
Summation.
Detailed Description
Class represents pose 2D data.
Definition at line 47 of file Pose2D.h.
Constructor & Destructor Documentation
Pose2D::Pose2D ()
Constructor.
Definition at line 42 of file Pose2D.cpp.
Pose2D::Pose2D (float x, float y, float theta)
Constructor.
Parameters
[in] x - coordinate
[in] y - coordinate
[in] theta - coordinate
Definition at line 46 of file Pose2D.cpp.
Pose2D::Pose2D (const Pose2D & orig)
Copy constructor.
Definition at line 49 of file Pose2D.cpp.
Pose2D::~Pose2D () virtual
Destructor.
Definition at line 52 of file Pose2D.cpp.
Member Function Documentation
float Pose2D::getTheta () const
Getting theta angle.
Definition at line 70 of file Pose2D.cpp.
References theta.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator+(), operator=(), conversions::pose2dToFrameKdl(), conversions::pose2dToPoseRos(), and OmniDrivePositionController::targetReached().
float Pose2D::getX () const
Getting x coordinate.
Definition at line 62 of file Pose2D.cpp.
References x.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), OmniDrivePositionController::getDistance(), operator+(), operator=(), conversions::pose2dToFrameKdl(), conversions::pose2dToPoseRos(), and OmniDrivePositionController::targetReached().
float Pose2D::getY () const
Getting y coordinate.
Definition at line 66 of file Pose2D.cpp.
References y.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), OmniDrivePositionController::getDistance(), operator+(), operator=(), conversions::pose2dToFrameKdl(), conversions::pose2dToPoseRos(), and OmniDrivePositionController::targetReached().
const Pose2D & Pose2D::operator= (const Pose2D & orig)
Assignment.
Definition at line 55 of file Pose2D.cpp.
References getTheta(), getX(), getY(), theta, x, and y.
Friends And Related Function Documentation
Pose2D operator+ (const Pose2D & op1, const Pose2D & op2) friend
Summation.
Definition at line 74 of file Pose2D.cpp.
Member Data Documentation
float Pose2D::theta private
theta coordinate.
Definition at line 113 of file Pose2D.h.
Referenced by getTheta(), and operator=().
float Pose2D::x private
x coordinate.
Definition at line 103 of file Pose2D.h.
Referenced by getX(), and operator=().
float Pose2D::y private
y coordinate.
Definition at line 108 of file Pose2D.h.
Referenced by getY(), and operator=().
The documentation for this class was generated from the following files:
navigation_trajectory_common/include/navigation_trajectory_common/Pose2D.h
navigation_trajectory_common/src/Pose2D.cpp