BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Point3D Class Reference
brics_3d::Point3D Class Reference
A class to represent a point in the Cartesian space.
#include <Point3D.h>
Public Member Functions
Point3D ()
Default constructor.
Point3D (Coordinate x, Coordinate y, Coordinate z)
Constructor with full initialization.
Point3D (Point3D *point)
Copy constructor.
Point3D (const Point3D &point)
Copy constructor.
virtual ~Point3D ()
Standard destructor.
virtual Coordinate getX () const
Get the x coordinate This is the only way to access a coordinate.
virtual Coordinate getY () const
Get the y coordinate This is the only way to access a coordinate.
virtual Coordinate getZ () const
Get the y coordinate This is the only way to access a coordinate.
virtual void setX (Coordinate x)
Set the x coordinate This is the only way to manipulate a coordinate.
virtual void setY (Coordinate y)
Set the y coordinate This is the only way to manipulate a coordinate.
virtual void setZ (Coordinate z)
Set the z coordinate This is the only way to manipulate a coordinate.
virtual void getRawData (Coordinate *pointBuffer)
Copy raw data to input buffer (array)
virtual Point3D operator+ (const Point3D *point)
Add a point to another point e.i each coordinate is added.
virtual Point3D operator- (const Point3D *point)
Subtract a point to another point e.i each coordinate is substracted.
virtual Point3D operator* (double scalar)
Multiply a point by a scalar.
virtual Point3D & operator= (const Point3D &point)
Overridden assign operator.
virtual void homogeneousTransformation (IHomogeneousMatrix44 *transformation)
Applies a homogeneous transformation matrix to the point.
virtual Point3D * clone () const
Creates a clone of the point and all potential decoration layers.
virtual ColoredPoint3D * asColoredPoint3D ()
Convenience function to deduce if this point is decorated with color information.
Point3D * new_clone (const Point3D &point)
Private Attributes
Coordinate x
X coordinate in Cartesian system.
Coordinate y
Y coordinate in Cartesian system.
Coordinate z
Z coordinate in Cartesian system (height)
Friends
istream & operator>> (istream &inStream, Point3D &point)
Overridden >> operator.
ostream & operator<< (ostream &outStream, const Point3D &point)
Overridden << operator.
Detailed Description
A class to represent a point in the Cartesian space.
This class is the basic representation of a three dimensional point in a Cartesian space. Basic vector functionality is also provided. Note that all data fields (coordinates) are private. (This is required by the Point3DDecorator.)
Definition at line 54 of file Point3D.h.
Constructor & Destructor Documentation
brics_3d::Point3D::Point3D ()
Default constructor.
Definition at line 36 of file Point3D.cpp.
References x, y, and z.
Referenced by clone(), and brics_3d::Point3DDecorator::Point3DDecorator().
brics_3d::Point3D::Point3D (Coordinate x, Coordinate y, Coordinate z)
Constructor with full initialization.
Parameters:
x X coordinate in Cartesian system
y Y coordinate in Cartesian system
z Z coordinate in Cartesian system (height)
Definition at line 55 of file Point3D.cpp.
References x, y, and z.
brics_3d::Point3D::Point3D (Point3D * point)
Copy constructor.
Parameters:
[in] point Pointer to point that will be copied
Definition at line 42 of file Point3D.cpp.
References getX(), getY(), getZ(), x, y, and z.
brics_3d::Point3D::Point3D (const Point3D & point)
Copy constructor.
Parameters:
[in] point Reference to point that will be copied
Definition at line 48 of file Point3D.cpp.
References getX(), getY(), getZ(), x, y, and z.
brics_3d::Point3D::~Point3D () [virtual]
Standard destructor.
Definition at line 61 of file Point3D.cpp.
Member Function Documentation
ColoredPoint3D * brics_3d::Point3D::asColoredPoint3D () [virtual]
Convenience function to deduce if this point is decorated with color information.
Returns:
Pointer to color object or null if there is no such decoration
Reimplemented in brics_3d::ColoredPoint3D, brics_3d::Point3DDecorator, and brics_3d::Point3DIntensity.
Definition at line 207 of file Point3D.cpp.
Referenced by brics_3d::Point3DDecorator::asColoredPoint3D().
Point3D * brics_3d::Point3D::clone () const [virtual]
Creates a clone of the point and all potential decoration layers.
Returns:
Pointer to cloned object
Reimplemented in brics_3d::ColoredPoint3D, and brics_3d::Point3DIntensity.
Definition at line 203 of file Point3D.cpp.
References Point3D().
Referenced by brics_3d::ColoredPoint3D::clone(), and new_clone().
void brics_3d::Point3D::getRawData (Coordinate * pointBuffer) [virtual]
Copy raw data to input buffer (array)
Parameters:
[out] pointBuffer Pointer to buffer, where to store the raw data
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 87 of file Point3D.cpp.
References x, y, and z.
Referenced by brics_3d::Point3DDecorator::getRawData().
Coordinate brics_3d::Point3D::getX () const [virtual]
Get the x coordinate This is the only way to access a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 65 of file Point3D.cpp.
References x.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::ObjectModelPlaneFromLines::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLineAndPoint::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLines::contains(), brics_3d::ObjectModelPlaneFromLineAndPoint::contains(), brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh(), brics_3d::BoxROIExtractor::filter(), brics_3d::NearestNeighborFLANN::findNearestNeighbors(), brics_3d::NearestNeighborANN::findNearestNeighbors(), brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::Point3DDecorator::getX(), brics_3d::operator<<(), operator=(), Point3D(), and brics_3d::pointToPlaneDistanceSigned().
Coordinate brics_3d::Point3D::getY () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 69 of file Point3D.cpp.
References y.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::ObjectModelPlaneFromLines::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLineAndPoint::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLines::contains(), brics_3d::ObjectModelPlaneFromLineAndPoint::contains(), brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh(), brics_3d::BoxROIExtractor::filter(), brics_3d::NearestNeighborFLANN::findNearestNeighbors(), brics_3d::NearestNeighborANN::findNearestNeighbors(), brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::Point3DDecorator::getY(), brics_3d::operator<<(), operator=(), Point3D(), and brics_3d::pointToPlaneDistanceSigned().
Coordinate brics_3d::Point3D::getZ () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 73 of file Point3D.cpp.
References z.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::ObjectModelPlaneFromLines::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLineAndPoint::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLines::contains(), brics_3d::ObjectModelPlaneFromLineAndPoint::contains(), brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh(), brics_3d::BoxROIExtractor::filter(), brics_3d::NearestNeighborFLANN::findNearestNeighbors(), brics_3d::NearestNeighborANN::findNearestNeighbors(), brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::Point3DDecorator::getZ(), brics_3d::operator<<(), operator=(), Point3D(), and brics_3d::pointToPlaneDistanceSigned().
void brics_3d::Point3D::homogeneousTransformation (IHomogeneousMatrix44 * transformation) [virtual]
Applies a homogeneous transformation matrix to the point.
Parameters:
[in] transformation The homogeneous transformation matrix that will be applied
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 154 of file Point3D.cpp.
References brics_3d::IHomogeneousMatrix44::getRawData(), x, y, and z.
Referenced by brics_3d::PointCloud3DIterator::begin(), brics_3d::Triangle::homogeneousTransformation(), brics_3d::Point3DDecorator::homogeneousTransformation(), and brics_3d::PointCloud3DIterator::next().
Point3D* brics_3d::Point3D::new_clone (const Point3D & point) [inline]
Definition at line 200 of file Point3D.h.
References clone().
Point3D brics_3d::Point3D::operator* (double scalar) [virtual]
Multiply a point by a scalar.
Parameters:
scalar Scalar that will be multiplied to each coordinate
Returns:
Result of scalar multiplication
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 127 of file Point3D.cpp.
References x, y, and z.
Point3D brics_3d::Point3D::operator+ (const Point3D * point) [virtual]
Add a point to another point e.i each coordinate is added.
Parameters:
[in] point Pointer to point that will be added
Returns:
Result of addition
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 93 of file Point3D.cpp.
References x, y, and z.
Point3D brics_3d::Point3D::operator- (const Point3D * point) [virtual]
Subtract a point to another point e.i each coordinate is substracted.
Parameters:
[in] point Pointer to point that will be subtracted
Returns:
Result of substraction
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 110 of file Point3D.cpp.
References x, y, and z.
Point3D & brics_3d::Point3D::operator= (const Point3D & point) [virtual]
Overridden assign operator.
Parameters:
point Reference to right operand
Returns:
Reference to left operand
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 144 of file Point3D.cpp.
References getX(), getY(), getZ(), x, y, and z.
void brics_3d::Point3D::setX (Coordinate x) [virtual]
Set the x coordinate This is the only way to manipulate a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 77 of file Point3D.cpp.
References x.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::Octree::filter(), brics_3d::SimplePointCloudGeneratorCube::generatePointCloud(), brics_3d::Octree::partitionPointCloud(), and brics_3d::Point3DDecorator::setX().
void brics_3d::Point3D::setY (Coordinate y) [virtual]
Set the y coordinate This is the only way to manipulate a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 80 of file Point3D.cpp.
References y.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::Octree::filter(), brics_3d::SimplePointCloudGeneratorCube::generatePointCloud(), brics_3d::Octree::partitionPointCloud(), and brics_3d::Point3DDecorator::setY().
void brics_3d::Point3D::setZ (Coordinate z) [virtual]
Set the z coordinate This is the only way to manipulate a coordinate.
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 83 of file Point3D.cpp.
References z.
Referenced by brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::computeCovarianceMatrix(), brics_3d::Octree::filter(), brics_3d::SimplePointCloudGeneratorCube::generatePointCloud(), brics_3d::Octree::partitionPointCloud(), and brics_3d::Point3DDecorator::setZ().
Friends And Related Function Documentation
ostream& operator<< (ostream & outStream, const Point3D & point) [friend]
Overridden << operator.
Writes a point to a stream e.g. std::cout << pointObj;
Parameters:
outStream The output stream
point Reference to point which data is forwarded to output stream
Returns:
Output stream
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 197 of file Point3D.cpp.
istream& operator>> (istream & inStream, Point3D & point) [friend]
Overridden >> operator.
Reads a point from a stream an stores it. e.g. std::cin >> pointObj;
Parameters:
inStream The input stream
point Reference to point where input is stored
Returns:
Input stream
Reimplemented in brics_3d::Point3DDecorator.
Definition at line 183 of file Point3D.cpp.
Member Data Documentation
Coordinate brics_3d::Point3D::x [private]
X coordinate in Cartesian system.
Definition at line 208 of file Point3D.h.
Referenced by getRawData(), getX(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), Point3D(), and setX().
Coordinate brics_3d::Point3D::y [private]
Y coordinate in Cartesian system.
Definition at line 211 of file Point3D.h.
Referenced by getRawData(), getY(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), Point3D(), and setY().
Coordinate brics_3d::Point3D::z [private]
Z coordinate in Cartesian system (height)
Definition at line 214 of file Point3D.h.
Referenced by getRawData(), getZ(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), Point3D(), and setZ().
The documentation for this class was generated from the following files:
src/brics_3d/core/Point3D.h
src/brics_3d/core/Point3D.cpp