BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::BoundingBox3DExtractor Class Reference
brics_3d::BoundingBox3DExtractor Class Reference
Feature Extraction
Calculate a bounding box for a point cloud.
#include <BoundingBox3DExtractor.h>
Public Member Functions
BoundingBox3DExtractor ()
Standard constructor.
virtual ~BoundingBox3DExtractor ()
Standard destructor.
void computeBoundingBox (PointCloud3D *inputPointCloud, Point3D &resultBoxCenter, Vector3D &resultBoxDimensions)
Compute an axis aligned bounding box.
void computeOrientedBoundingBox (PointCloud3D *inputPointCloud, IHomogeneousMatrix44 *resultTransform, Vector3D &resultBoxDimensions)
Compute an oriented bounding box.
Protected Attributes
Point3D lowerBound
Lower bundariy used to find min values for x, y and z.
Point3D upperBound
Upper bundariy used to find max values for x, y and z.
PCA pcaExtractor
PCA used for computing an oriented bounding box.
Detailed Description
Calculate a bounding box for a point cloud.
Definition at line 35 of file BoundingBox3DExtractor.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d algorithm featureExtraction BoundingBox3DExtractor cpp home alexey workspace BRICS_3d src brics_3d algorithm featureExtraction BoundingBox3DExtractor cpp brics_3d::BoundingBox3DExtractor::BoundingBox3DExtractor ()
Standard constructor.
Definition at line 30 of file BoundingBox3DExtractor.cpp.
brics_3d::BoundingBox3DExtractor::~BoundingBox3DExtractor () [virtual]
Standard destructor.
Definition at line 34 of file BoundingBox3DExtractor.cpp.
Member Function Documentation
void brics_3d::BoundingBox3DExtractor::computeBoundingBox (PointCloud3D * inputPointCloud, Point3D & resultBoxCenter, Vector3D & resultBoxDimensions)
Compute an axis aligned bounding box.
Parameters:
[in] inputPointCloud The point cloud whose bounding box shall be computed.
[out] resultBoxCenter Point that represents the center of the bounding box.
[out] resultBoxDimensions 3D vector the represents the dimensions centered around the resultBoxCenter.
Definition at line 38 of file BoundingBox3DExtractor.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), lowerBound, brics_3d::Point3D::setX(), brics_3d::Point3D::setY(), brics_3d::Point3D::setZ(), and upperBound.
void brics_3d::BoundingBox3DExtractor::computeOrientedBoundingBox (PointCloud3D * inputPointCloud, IHomogeneousMatrix44 * resultTransform, Vector3D & resultBoxDimensions)
Compute an oriented bounding box.
Internally a PCA will be performed to find the orientation.
Parameters:
[in] inputPointCloud The point cloud whose bounding box shall be computed.
[out] resultTransform Transform the contains the oriantation as well as the center of the bounding box.
[out] resultBoxDimensions 3D vector the represents the dimensions centered around the center.
Definition at line 88 of file BoundingBox3DExtractor.cpp.
Member Data Documentation
Point3D brics_3d::BoundingBox3DExtractor::lowerBound [protected]
Lower bundariy used to find min values for x, y and z.
Definition at line 69 of file BoundingBox3DExtractor.h.
Referenced by computeBoundingBox().
PCA brics_3d::BoundingBox3DExtractor::pcaExtractor [protected]
PCA used for computing an oriented bounding box.
Definition at line 75 of file BoundingBox3DExtractor.h.
Point3D brics_3d::BoundingBox3DExtractor::upperBound [protected]
Upper bundariy used to find max values for x, y and z.
Definition at line 72 of file BoundingBox3DExtractor.h.
Referenced by computeBoundingBox().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/featureExtraction/BoundingBox3DExtractor.h
src/brics_3d/algorithm/featureExtraction/BoundingBox3DExtractor.cpp