BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::SceneGraphToUpdatesTraverser Class Reference
brics_3d::rsg::SceneGraphToUpdatesTraverser Class Reference
Scenegraph
Scene graph visitor that traverses an existing graph and will call approproate update functions for each element.
#include <SceneGraphToUpdatesTraverser.h>
Public Member Functions
SceneGraphToUpdatesTraverser (ISceneGraphUpdate *updatesRecieverHandle)
Constructor.
virtual ~SceneGraphToUpdatesTraverser ()
Default destructor.
virtual void visit (Node *node)
virtual void visit (Group *node)
virtual void visit (Transform *node)
virtual void visit (GeometricNode *node)
virtual void reset ()
Reset all memory.
bool getEnableForcedIds ()
void setEnableForcedIds (bool enableForcedIds)
Private Member Functions
bool handleExistingNode (Node *node, unsigned int &parentId)
The common part for all nodeds.
Private Attributes
ISceneGraphUpdate * updatesRecieverHandle
This is the reciever of all updates.
bool enableForcedIds
This will be passed as flag to the update functions. Default is true.
std::map< Node *, vector< Node * > > alreadyVisitedNodesWithPendingStatus
Memory of what already visited nodes, including wich partent per node have been already added.
std::map< Node *, vector< Node * >
>::iterator alreadyVisitedNodesIterator
std::map< Node *, vector< Node * >
>::iterator alreadyVisitedAndPendingNodesIterator
Detailed Description
Scene graph visitor that traverses an existing graph and will call approproate update functions for each element.
This traverser can be used i.e. to duplicate an existing scene graph.
There are a couple of implementational issues to keep in mind:
To be able to successfully add new elements in the observing/receiving graph only already existing nodes can be referenced, in particular via the parent IDs. Only nodes that have been traversed before can be assumbed to exist already.
During a traversal the visited elements do not now which preceeding parent caused the invokation. This needs to be recovered.
Potential duplications of parent-child relation could occour while traversing a more complex graph.
Definition at line 51 of file SceneGraphToUpdatesTraverser.h.
Constructor & Destructor Documentation
brics_3d::rsg::SceneGraphToUpdatesTraverser::SceneGraphToUpdatesTraverser (ISceneGraphUpdate * updatesRecieverHandle)
Constructor.
Parameters:
updatesRecieverHandle Pointer to the reciever of all updates.
Definition at line 29 of file SceneGraphToUpdatesTraverser.cpp.
References enableForcedIds, reset(), and updatesRecieverHandle.
brics_3d::rsg::SceneGraphToUpdatesTraverser::~SceneGraphToUpdatesTraverser () [virtual]
Default destructor.
Definition at line 36 of file SceneGraphToUpdatesTraverser.cpp.
Member Function Documentation
bool brics_3d::rsg::SceneGraphToUpdatesTraverser::getEnableForcedIds ()
Definition at line 77 of file SceneGraphToUpdatesTraverser.cpp.
References enableForcedIds.
bool brics_3d::rsg::SceneGraphToUpdatesTraverser::handleExistingNode (Node * node, unsigned int & parentId) [private]
The common part for all nodeds.
Only the cretation of new nodes differs.
Parameters:
node The current node to be processed.
[out] parentId The deduced parent ID such that a new node can be created in case false will be returned.
Returns:
True if node exists and was sucessfully handeled or false if node could not be handled and needs to be treated as a new node.
Definition at line 86 of file SceneGraphToUpdatesTraverser.cpp.
References brics_3d::rsg::ISceneGraphUpdate::addParent(), alreadyVisitedAndPendingNodesIterator, alreadyVisitedNodesIterator, alreadyVisitedNodesWithPendingStatus, brics_3d::rsg::Node::getId(), brics_3d::rsg::Node::getParents(), LOG, and updatesRecieverHandle.
Referenced by visit().
void brics_3d::rsg::SceneGraphToUpdatesTraverser::reset () [virtual]
Reset all memory.
Definition at line 73 of file SceneGraphToUpdatesTraverser.cpp.
References alreadyVisitedNodesWithPendingStatus.
Referenced by SceneGraphToUpdatesTraverser().
void brics_3d::rsg::SceneGraphToUpdatesTraverser::setEnableForcedIds (bool enableForcedIds)
Definition at line 81 of file SceneGraphToUpdatesTraverser.cpp.
References enableForcedIds.
void brics_3d::rsg::SceneGraphToUpdatesTraverser::visit (Group * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 48 of file SceneGraphToUpdatesTraverser.cpp.
References brics_3d::rsg::ISceneGraphUpdate::addGroup(), enableForcedIds, brics_3d::rsg::Node::getAttributes(), brics_3d::rsg::Node::getId(), handleExistingNode(), and updatesRecieverHandle.
void brics_3d::rsg::SceneGraphToUpdatesTraverser::visit (Node * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 40 of file SceneGraphToUpdatesTraverser.cpp.
References brics_3d::rsg::ISceneGraphUpdate::addNode(), enableForcedIds, brics_3d::rsg::Node::getAttributes(), brics_3d::rsg::Node::getId(), handleExistingNode(), and updatesRecieverHandle.
void brics_3d::rsg::SceneGraphToUpdatesTraverser::visit (Transform * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 57 of file SceneGraphToUpdatesTraverser.cpp.
References brics_3d::rsg::ISceneGraphUpdate::addTransformNode(), enableForcedIds, brics_3d::rsg::Node::getAttributes(), brics_3d::rsg::Node::getId(), brics_3d::rsg::Transform::getLatestTimeStamp(), brics_3d::rsg::Transform::getLatestTransform(), handleExistingNode(), and updatesRecieverHandle.
void brics_3d::rsg::SceneGraphToUpdatesTraverser::visit (GeometricNode * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 65 of file SceneGraphToUpdatesTraverser.cpp.
References brics_3d::rsg::ISceneGraphUpdate::addGeometricNode(), enableForcedIds, brics_3d::rsg::Node::getAttributes(), brics_3d::rsg::Node::getId(), brics_3d::rsg::GeometricNode::getShape(), brics_3d::rsg::GeometricNode::getTimeStamp(), handleExistingNode(), and updatesRecieverHandle.
Member Data Documentation
std::map<Node*, vector<Node*> >::iterator brics_3d::rsg::SceneGraphToUpdatesTraverser::alreadyVisitedAndPendingNodesIterator [private]
Definition at line 99 of file SceneGraphToUpdatesTraverser.h.
Referenced by handleExistingNode().
std::map<Node*, vector<Node*> >::iterator brics_3d::rsg::SceneGraphToUpdatesTraverser::alreadyVisitedNodesIterator [private]
Definition at line 98 of file SceneGraphToUpdatesTraverser.h.
Referenced by handleExistingNode().
std::map<Node*, vector<Node*> > brics_3d::rsg::SceneGraphToUpdatesTraverser::alreadyVisitedNodesWithPendingStatus [private]
Memory of what already visited nodes, including wich partent per node have been already added.
Definition at line 97 of file SceneGraphToUpdatesTraverser.h.
Referenced by handleExistingNode(), and reset().
bool brics_3d::rsg::SceneGraphToUpdatesTraverser::enableForcedIds [private]
This will be passed as flag to the update functions. Default is true.
Definition at line 94 of file SceneGraphToUpdatesTraverser.h.
Referenced by getEnableForcedIds(), SceneGraphToUpdatesTraverser(), setEnableForcedIds(), and visit().
ISceneGraphUpdate* brics_3d::rsg::SceneGraphToUpdatesTraverser::updatesRecieverHandle [private]
This is the reciever of all updates.
Could be an inmlemation an an observer according to ISceneGraphUpdateObserver or another SceneGrapgFacade.
Definition at line 91 of file SceneGraphToUpdatesTraverser.h.
Referenced by handleExistingNode(), SceneGraphToUpdatesTraverser(), and visit().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/SceneGraphToUpdatesTraverser.h
src/brics_3d/worldModel/sceneGraph/SceneGraphToUpdatesTraverser.cpp