BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::SceneGraphFacade Class Reference
brics_3d::rsg::SceneGraphFacade Class Reference
Scenegraph
The central handle to create and maintain a robot scenegraph.
#include <SceneGraphFacade.h>
Public Member Functions
SceneGraphFacade ()
SceneGraphFacade (IIdGenerator *idGenerator)
virtual ~SceneGraphFacade ()
unsigned int getRootId ()
bool getNodes (vector< Attribute > attributes, vector< unsigned int > &ids)
Find all nodes that have at least the specified attributes.
bool getNodeAttributes (unsigned int id, vector< Attribute > &attributes)
Get the attributes of a node.
bool getNodeParents (unsigned int id, vector< unsigned int > &parentIds)
Get all the parent IDs of a certain node.
bool getGroupChildren (unsigned int id, vector< unsigned int > &childIds)
Gett all cild IDs for a certain group node.
bool getTransform (unsigned int id, TimeStamp timeStamp, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr &transform)
Get the transform of a TransformNode at a certain time.
bool getGeometry (unsigned int id, Shape::ShapePtr &shape, TimeStamp &timeStamp)
Get the data of a GeometryNode.
bool getTransformForNode (unsigned int id, unsigned int idReferenceNode, TimeStamp timeStamp, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr &transform)
bool addNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)
Add a new Node to the robot scene graph.
bool addGroup (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)
Add a Group node to the robot scenegraph.
bool addTransformNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId=false)
Add a new Transform node the the robot scene graph.
bool addGeometricNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId=false)
Add a GeometricNode that contains 3D data to the robot scene graph.
bool setNodeAttributes (unsigned int id, vector< Attribute > newAttributes)
Override the attributes of a node.
bool setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp)
Update the transformation of an existing Transform node.
bool deleteNode (unsigned int id)
Delete a node in the robot scenegraph.
bool addParent (unsigned int id, unsigned int parentId)
Add a new parent-child relation between two nodes.
bool attachUpdateObserver (ISceneGraphUpdateObserver *observer)
bool detachUpdateObserver (ISceneGraphUpdateObserver *observer)
bool executeGraphTraverser (INodeVisitor *visitor, unsigned int subgraphId)
Private Member Functions
void initialize ()
Internal initiaization.
Node::NodeWeakPtr findNodeRecerence (unsigned int id)
Resolved IDs to references.
bool doesIdExist (unsigned int id)
Test if an ID is in the idLookUpTable.
Private Attributes
Group::GroupPtr rootNode
The root of all evil...
map< unsigned int,
Node::NodeWeakPtr > idLookUpTable
Table that maps IDs to references.
map< unsigned int,
Node::NodeWeakPtr >
::const_iterator nodeIterator
Iterator for idLookUpTable.
IIdGenerator * idGenerator
Handle to ID generator. Can be optionally specified at creation.
std::vector
< ISceneGraphUpdateObserver * > updateObservers
Set of observers that will be notified when the update function will be called.
Detailed Description
The central handle to create and maintain a robot scenegraph.
It holds the root node of the scene graph.
The SceneGraphFacade takes care (maintains consistency) of mapping between IDs and internal pointers. The implemented interfaces allow to create and maintain a scengraph bases on the node IDs only.
Definition at line 54 of file SceneGraphFacade.h.
Constructor & Destructor Documentation
brics_3d::rsg::SceneGraphFacade::SceneGraphFacade ()
Definition at line 30 of file SceneGraphFacade.cpp.
brics_3d::rsg::SceneGraphFacade::SceneGraphFacade (IIdGenerator * idGenerator)
Definition at line 35 of file SceneGraphFacade.cpp.
brics_3d::rsg::SceneGraphFacade::~SceneGraphFacade () [virtual]
Definition at line 41 of file SceneGraphFacade.cpp.
References idGenerator.
Member Function Documentation
bool brics_3d::rsg::SceneGraphFacade::addGeometricNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId = false) [virtual]
Add a GeometricNode that contains 3D data to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
shape The geometic Shape to be contained the the GeometricNode. Multiple shape types are possible like a Box, a Cylinder a Mesh or a PointCloud for instance.
timeStamp Time stamp assiciated with the geometic Shape.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new GeometricNode was sucessfully added to the scen egraph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 313 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::addGroup (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [virtual]
Add a Group node to the robot scenegraph.
The group allows to create the graph structure as it has children, in contrast to a simple node.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Group was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 210 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::addNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [virtual]
Add a new Node to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Node was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 160 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::addParent (unsigned int id, unsigned int parentId) [virtual]
Add a new parent-child relation between two nodes.
Parameters:
id ID of the node
parentId ID of the parent node. Must not be a leave like a Node or a GeometricNode
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 459 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::addTransformNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId = false) [virtual]
Add a new Transform node the the robot scene graph.
Internally brics_3d::rsg::Transform is used that is able to maintain a temporal cache of the trnasform data.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
transform The actual transform data that will be (initially) inserted. You can later insert more with brics_3d::rsg::ISceneGraphUpdate::setTransform() .
timeStamp Time stamp associated with the transform.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Transform was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 261 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::attachUpdateObserver (ISceneGraphUpdateObserver * observer)
Definition at line 486 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::deleteNode (unsigned int id) [virtual]
Delete a node in the robot scenegraph.
Parameters:
id ID the defines the node to be deleted.
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 413 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::detachUpdateObserver (ISceneGraphUpdateObserver * observer)
Definition at line 492 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::doesIdExist (unsigned int id) [private]
Test if an ID is in the idLookUpTable.
Parameters:
id The ID.
Returns:
True if ID is in table, otherwise false.
Definition at line 527 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::executeGraphTraverser (INodeVisitor * visitor, unsigned int subgraphId)
Definition at line 503 of file SceneGraphFacade.cpp.
Referenced by brics_3d::rsg::DotVisualizer::printGraph().
Node::NodeWeakPtr brics_3d::rsg::SceneGraphFacade::findNodeRecerence (unsigned int id) [private]
Resolved IDs to references.
Parameters:
id The ID.
Returns:
The reference. Will be NULL in case no reference could be found.
Definition at line 513 of file SceneGraphFacade.cpp.
References LOG, and nodeIterator.
bool brics_3d::rsg::SceneGraphFacade::getGeometry (unsigned int id, Shape::ShapePtr & shape, TimeStamp & timeStamp) [virtual]
Get the data of a GeometryNode.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 133 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::getGroupChildren (unsigned int id, vector< unsigned int > & childIds) [virtual]
Gett all cild IDs for a certain group node.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 107 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::getNodeAttributes (unsigned int id, vector< Attribute > & attributes) [virtual]
Get the attributes of a node.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 79 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::getNodeParents (unsigned int id, vector< unsigned int > & parentIds) [virtual]
Get all the parent IDs of a certain node.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 94 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::getNodes (vector< Attribute > attributes, vector< unsigned int > & ids) [virtual]
Find all nodes that have at least the specified attributes.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 60 of file SceneGraphFacade.cpp.
unsigned int brics_3d::rsg::SceneGraphFacade::getRootId ()
Definition at line 56 of file SceneGraphFacade.cpp.
Referenced by brics_3d::rsg::DotVisualizer::printGraph().
bool brics_3d::rsg::SceneGraphFacade::getTransform (unsigned int id, TimeStamp timeStamp, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr & transform) [virtual]
Get the transform of a TransformNode at a certain time.
Implements brics_3d::rsg::ISceneGraphQuery.
Definition at line 121 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::getTransformForNode (unsigned int id, unsigned int idReferenceNode, TimeStamp timeStamp, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr & transform)
Definition at line 146 of file SceneGraphFacade.cpp.
Referenced by brics_3d::rsg::PointCloudAccumulatorIdAware::doGetTransformFromReferenceToPointCloud().
void brics_3d::rsg::SceneGraphFacade::initialize () [private]
Internal initiaization.
Definition at line 48 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::setNodeAttributes (unsigned int id, vector< Attribute > newAttributes) [virtual]
Override the attributes of a node.
Parameters:
id ID the defines the node to be updated.
newAttributes The new attributes. THe old one will be overidden by tis
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 366 of file SceneGraphFacade.cpp.
bool brics_3d::rsg::SceneGraphFacade::setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp) [virtual]
Update the transformation of an existing Transform node.
Parameters:
id ID the defines the Transform node to be updated.
transform The transform data that will be inserted in to the cacje of the Transform.
timeStamp Time stamp associated with the transform.
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 389 of file SceneGraphFacade.cpp.
Member Data Documentation
IIdGenerator* brics_3d::rsg::SceneGraphFacade::idGenerator [private]
Handle to ID generator. Can be optionally specified at creation.
Definition at line 122 of file SceneGraphFacade.h.
Referenced by ~SceneGraphFacade().
map<unsigned int, Node::NodeWeakPtr > brics_3d::rsg::SceneGraphFacade::idLookUpTable [private]
Table that maps IDs to references.
Definition at line 116 of file SceneGraphFacade.h.
map<unsigned int, Node::NodeWeakPtr >::const_iterator brics_3d::rsg::SceneGraphFacade::nodeIterator [private]
Iterator for idLookUpTable.
Definition at line 119 of file SceneGraphFacade.h.
Referenced by findNodeRecerence().
Group::GroupPtr brics_3d::rsg::SceneGraphFacade::rootNode [private]
The root of all evil...
Definition at line 113 of file SceneGraphFacade.h.
std::vector<ISceneGraphUpdateObserver*> brics_3d::rsg::SceneGraphFacade::updateObservers [private]
Set of observers that will be notified when the update function will be called.
Definition at line 125 of file SceneGraphFacade.h.
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/SceneGraphFacade.h
src/brics_3d/worldModel/sceneGraph/SceneGraphFacade.cpp