BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::PCLTypecaster Class Reference
brics_3d::PCLTypecaster Class Reference
#include <PCLTypecaster.h>
Public Member Functions
PCLTypecaster ()
virtual ~PCLTypecaster ()
void convertToPCLDataType (pcl::PointCloud< pcl::PointXYZ >::Ptr pclCloudPtr, brics_3d::PointCloud3D *pointCloud3DPtr)
Converts from XYZ-cloud format of BRICS_3D to XYZ-cloud format of PCL.
void convertToBRICS3DDataType (pcl::PointCloud< pcl::PointXYZ >::ConstPtr pclCloudPtr, brics_3d::PointCloud3D *pointCloud3DPtr)
Converts from XYZ-cloud format of PCL to XYZ-cloud format of BRICS_3D.
void convertToBRICS3DDataType (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr pclCloudPtr, brics_3d::PointCloud3D *pointCloud3DPtr, bool copyColorData=true)
Converts from XYZRGB-cloud format of PCL to XYZ-cloud format of BRICS_3D.
void convertToPCLDataType (pcl::PointCloud< pcl::PointXYZRGB >::Ptr pclCloudPtr, brics_3d::PointCloud3D *pointCloud3DPtr)
Converts from XYZRGB-cloud format of BRICS_3D to XYZRGB-cloud format of PCL.
Detailed Description
Definition at line 33 of file PCLTypecaster.h.
Constructor & Destructor Documentation
brics_3d::PCLTypecaster::PCLTypecaster () [inline]
Definition at line 35 of file PCLTypecaster.h.
virtual brics_3d::PCLTypecaster::~PCLTypecaster () [inline, virtual]
Definition at line 36 of file PCLTypecaster.h.
Member Function Documentation
void brics_3d::PCLTypecaster::convertToBRICS3DDataType (pcl::PointCloud< pcl::PointXYZ >::ConstPtr pclCloudPtr, brics_3d::PointCloud3D * pointCloud3DPtr) [inline]
Converts from XYZ-cloud format of PCL to XYZ-cloud format of BRICS_3D.
Parameters:
pclCloudPtr point cloud data in PCL format
pointCloud3DPtr point cloud datda in BRICS_3D format
Definition at line 62 of file PCLTypecaster.h.
References brics_3d::PointCloud3D::getPointCloud().
void brics_3d::PCLTypecaster::convertToBRICS3DDataType (pcl::PointCloud< pcl::PointXYZRGB >::ConstPtr pclCloudPtr, brics_3d::PointCloud3D * pointCloud3DPtr, bool copyColorData = true) [inline]
Converts from XYZRGB-cloud format of PCL to XYZ-cloud format of BRICS_3D.
Parameters:
pclCloudPtr point cloud data in PCL format
pointCloud3DPtr point cloud datda in BRICS_3D format
Definition at line 88 of file PCLTypecaster.h.
References brics_3d::PointCloud3D::addPointPtr(), and brics_3d::ColorSpaceConvertor::rgb24bitToRGB().
void brics_3d::PCLTypecaster::convertToPCLDataType (pcl::PointCloud< pcl::PointXYZRGB >::Ptr pclCloudPtr, brics_3d::PointCloud3D * pointCloud3DPtr) [inline]
Converts from XYZRGB-cloud format of BRICS_3D to XYZRGB-cloud format of PCL.
Parameters:
pclCloudPtr point cloud data in PCL format
pointCloud3DPtr point cloud data in BRICS_3D format
Definition at line 130 of file PCLTypecaster.h.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::ColorSpaceConvertor::rgbToRGB24Bit().
void brics_3d::PCLTypecaster::convertToPCLDataType (pcl::PointCloud< pcl::PointXYZ >::Ptr pclCloudPtr, brics_3d::PointCloud3D * pointCloud3DPtr) [inline]
Converts from XYZ-cloud format of BRICS_3D to XYZ-cloud format of PCL.
Parameters:
pclCloudPtr point cloud data in PCL format
pointCloud3DPtr point cloud datda in BRICS_3D format
Definition at line 44 of file PCLTypecaster.h.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::PointCloud3D::getSize().
Referenced by brics_3d::RGBColorBasedEuclideanClustering::extractClusters().
The documentation for this class was generated from the following file:
src/brics_3d/util/PCLTypecaster.h