BRICS_RN (Robust Navigation Library): FrameWithId Class Reference
FrameWithId Class Reference
FrameWithId is an aggregation of KDL::Frame class with a std::string as frame id.
#include <FrameWithId.h>
Public Member Functions
FrameWithId (const std::string &id)
Constructor.
FrameWithId (const KDL::Frame &frame)
Constructor.
FrameWithId (const KDL::Frame &frame, const std::string &id)
Constructor.
FrameWithId ()
Default constructor.
FrameWithId (const FrameWithId &orig)
Copy constructor.
const FrameWithId & operator= (const FrameWithId &orig)
Operation assignment.
void setFrame (const KDL::Frame &frame)
Sets new KDL::Frame.
const KDL::Frame & getFrame () const
Returns an underlying KDL::Frame as a const reference.
KDL::Frame & getFrame ()
Returns an underlying KDL::Frame as a reference.
virtual ~FrameWithId ()
Public Attributes
std::string id
String identifier of the frame.
Private Attributes
KDL::Frame * frame
Aggregated, heap-allocated KDL::Frame.
Detailed Description
FrameWithId is an aggregation of KDL::Frame class with a std::string as frame id.
The embedded KDL::Frame will be always heap-allocated.
Definition at line 54 of file FrameWithId.h.
Constructor & Destructor Documentation
FrameWithId::FrameWithId (const std::string & id)
Constructor.
The embedded KDL::Frame member will be initialized by its default constructor.
Parameters
[in] id - string identifier of the frame
Definition at line 46 of file FrameWithId.cpp.
FrameWithId::FrameWithId (const KDL::Frame & frame)
Constructor.
The frame's id is set to be the empty string.
Parameters
[in] frame - initial 6D pose of the frame
Definition at line 51 of file FrameWithId.cpp.
FrameWithId::FrameWithId (const KDL::Frame & frame, const std::string & id)
Constructor.
Parameters
[in] frame - initial 6D pose of the frame
[in] id - string identifier of the frame
Definition at line 56 of file FrameWithId.cpp.
FrameWithId::FrameWithId ()
Default constructor.
The embedded KDL::Frame member will be initialized by its default constructor. The frame's id is set to be the empty string.
Definition at line 61 of file FrameWithId.cpp.
FrameWithId::FrameWithId (const FrameWithId & orig)
Copy constructor.
Parameters
[in] arg - reference to the original object
Definition at line 66 of file FrameWithId.cpp.
References getFrame(), and id.
FrameWithId::~FrameWithId () virtual
Definition at line 78 of file FrameWithId.cpp.
Member Function Documentation
const KDL::Frame & FrameWithId::getFrame () const
Returns an underlying KDL::Frame as a const reference.
Modifications on the FrameWithId, except assignment or setFrame(), will be reflected by the returned reference.
Assigning or setting a new frame invalidates all references obtained from const KDL::Frame& getFrame() const.
Definition at line 87 of file FrameWithId.cpp.
Referenced by OmniDriveTrajectoryGenerator::computePathComposite(), computePathComposite(), conversions::frameToPoseRos(), FrameWithId(), conversions::odometryRosToFrame(), operator=(), conversions::pathToPathKdl(), utilities::perpendicularDistance(), and conversions::poseRosToFrame().
KDL::Frame & FrameWithId::getFrame ()
Returns an underlying KDL::Frame as a reference.
Modifications on the FrameWithId, except assignment or setFrame(), will be reflected by the returned reference.
Assigning or setting a new frame invalidates all references obtained from KDL::Frame& getFrame().
Definition at line 91 of file FrameWithId.cpp.
const FrameWithId & FrameWithId::operator= (const FrameWithId & orig)
Operation assignment.
Parameters
[in] orig - reference to the original object
Definition at line 71 of file FrameWithId.cpp.
References getFrame(), and id.
void FrameWithId::setFrame (const KDL::Frame & frame)
Sets new KDL::Frame.
The supplied KDL::Frame frame is copied and can be delete or modified without affecting the FrameWithId instance. The id member is not modified.
Definition at line 82 of file FrameWithId.cpp.
Member Data Documentation
KDL::Frame* FrameWithId::frame private
Aggregated, heap-allocated KDL::Frame.
Definition at line 148 of file FrameWithId.h.
std::string FrameWithId::id
String identifier of the frame.
Definition at line 59 of file FrameWithId.h.
Referenced by conversions::frameToPoseRos(), FrameWithId(), conversions::odometryRosToFrame(), operator=(), and conversions::poseRosToFrame().
The documentation for this class was generated from the following files:
navigation_trajectory_common/include/navigation_trajectory_common/FrameWithId.h
navigation_trajectory_common/src/FrameWithId.cpp