BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::RGBColorBasedEuclideanClustering Class Reference
brics_3d::RGBColorBasedEuclideanClustering Class Reference
Segmentation
Segmentation based on Eucledian distance and distance in RGB color-space.
#include <RGBColorBasedEuclideanClustering.h>
Public Member Functions
RGBColorBasedEuclideanClustering ()
virtual ~RGBColorBasedEuclideanClustering ()
void extractClusters (brics_3d::PointCloud3D *inCloud)
int segment ()
Get the pointcloud being used.
int getMaxClusterSize () const
int getMinClusterSize () const
double getToleranceEuclideanDistance () const
double getToleranceRgbSpace () const
void setMaxClusterSize (int maxClusterSize)
void setMinClusterSize (int minClusterSize)
void setToleranceEuclideanDistance (double toleranceEuclideanDistance)
void setToleranceRgbSpace (double toleranceRgbSpace)
void getExtractedClusters (std::vector< brics_3d::PointCloud3D * > &extractedClusters)
Private Member Functions
bool isSimilar (uint32_t rgb_24bit_first, uint32_t rgb_24bit_second)
Private Attributes
double toleranceRGBSpace
double toleranceEuclideanDistance
unsigned int minClusterSize
unsigned int maxClusterSize
std::vector
< brics_3d::PointCloud3D * > extractedClusters
Detailed Description
Segmentation based on Eucledian distance and distance in RGB color-space.
Definition at line 35 of file RGBColorBasedEuclideanClustering.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d algorithm segmentation RGBColorBasedEuclideanClustering cpp brics_3d::RGBColorBasedEuclideanClustering::RGBColorBasedEuclideanClustering ()
Definition at line 34 of file RGBColorBasedEuclideanClustering.cpp.
brics_3d::RGBColorBasedEuclideanClustering::~RGBColorBasedEuclideanClustering () [virtual]
Definition at line 39 of file RGBColorBasedEuclideanClustering.cpp.
Member Function Documentation
void brics_3d::RGBColorBasedEuclideanClustering::extractClusters (brics_3d::PointCloud3D * inCloud)
Definition at line 96 of file RGBColorBasedEuclideanClustering.cpp.
References brics_3d::PointCloud3D::addPointPtr(), brics_3d::PCLTypecaster::convertToPCLDataType(), extractedClusters, brics_3d::PointCloud3D::getPointCloud(), brics_3d::ISegmentation::inputPointCloud, isSimilar(), maxClusterSize, and minClusterSize.
Referenced by segment().
void brics_3d::RGBColorBasedEuclideanClustering::getExtractedClusters (std::vector< brics_3d::PointCloud3D * > & extractedClusters) [inline]
Definition at line 86 of file RGBColorBasedEuclideanClustering.h.
References extractedClusters.
int brics_3d::RGBColorBasedEuclideanClustering::getMaxClusterSize () const
Definition at line 44 of file RGBColorBasedEuclideanClustering.cpp.
References maxClusterSize.
int brics_3d::RGBColorBasedEuclideanClustering::getMinClusterSize () const
Definition at line 49 of file RGBColorBasedEuclideanClustering.cpp.
References minClusterSize.
double brics_3d::RGBColorBasedEuclideanClustering::getToleranceEuclideanDistance () const
Definition at line 54 of file RGBColorBasedEuclideanClustering.cpp.
References toleranceEuclideanDistance.
double brics_3d::RGBColorBasedEuclideanClustering::getToleranceRgbSpace () const
Definition at line 59 of file RGBColorBasedEuclideanClustering.cpp.
References toleranceRGBSpace.
bool brics_3d::RGBColorBasedEuclideanClustering::isSimilar (uint32_t rgb_24bit_first, uint32_t rgb_24bit_second) [inline, private]
Definition at line 39 of file RGBColorBasedEuclideanClustering.h.
References toleranceRGBSpace.
Referenced by extractClusters().
int brics_3d::RGBColorBasedEuclideanClustering::segment () [virtual]
Get the pointcloud being used.
Parameters:
pointer to the pointcloud being used Abstract method to perform segmentation
Implements brics_3d::ISegmentation.
Definition at line 84 of file RGBColorBasedEuclideanClustering.cpp.
References extractClusters(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::ISegmentation::inputPointCloud, and LOG.
void brics_3d::RGBColorBasedEuclideanClustering::setMaxClusterSize (int maxClusterSize)
Definition at line 64 of file RGBColorBasedEuclideanClustering.cpp.
References maxClusterSize.
void brics_3d::RGBColorBasedEuclideanClustering::setMinClusterSize (int minClusterSize)
Definition at line 69 of file RGBColorBasedEuclideanClustering.cpp.
References minClusterSize.
void brics_3d::RGBColorBasedEuclideanClustering::setToleranceEuclideanDistance (double toleranceEuclideanDistance)
Definition at line 74 of file RGBColorBasedEuclideanClustering.cpp.
References toleranceEuclideanDistance.
void brics_3d::RGBColorBasedEuclideanClustering::setToleranceRgbSpace (double toleranceRgbSpace)
Definition at line 79 of file RGBColorBasedEuclideanClustering.cpp.
References toleranceRGBSpace.
Member Data Documentation
std::vector<brics_3d::PointCloud3D*> brics_3d::RGBColorBasedEuclideanClustering::extractedClusters [private]
Definition at line 69 of file RGBColorBasedEuclideanClustering.h.
Referenced by extractClusters(), and getExtractedClusters().
unsigned int brics_3d::RGBColorBasedEuclideanClustering::maxClusterSize [private]
Definition at line 67 of file RGBColorBasedEuclideanClustering.h.
Referenced by extractClusters(), getMaxClusterSize(), and setMaxClusterSize().
unsigned int brics_3d::RGBColorBasedEuclideanClustering::minClusterSize [private]
Definition at line 66 of file RGBColorBasedEuclideanClustering.h.
Referenced by extractClusters(), getMinClusterSize(), and setMinClusterSize().
double brics_3d::RGBColorBasedEuclideanClustering::toleranceEuclideanDistance [private]
Definition at line 65 of file RGBColorBasedEuclideanClustering.h.
Referenced by getToleranceEuclideanDistance(), and setToleranceEuclideanDistance().
double brics_3d::RGBColorBasedEuclideanClustering::toleranceRGBSpace [private]
Definition at line 64 of file RGBColorBasedEuclideanClustering.h.
Referenced by getToleranceRgbSpace(), isSimilar(), and setToleranceRgbSpace().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/RGBColorBasedEuclideanClustering.h
src/brics_3d/algorithm/segmentation/RGBColorBasedEuclideanClustering.cpp