BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Point3DDecorator Class Reference
brics_3d::Point3DDecorator Class Reference
Abstract class that can extend or "decorate" a Point3D.
#include <Point3DDecorator.h>
Public Member Functions
Point3DDecorator ()
Standard constructor.
Point3DDecorator (Point3D *point)
Constructor that requires a Point3D pointer.
Point3DDecorator (Point3DDecorator *point)
Copy constructor.
Point3DDecorator (const Point3DDecorator &point)
Copy constructor.
Point3DDecorator & operator= (Point3DDecorator &point)
Assignement operator.
virtual ~Point3DDecorator ()
Standard destructor.
Coordinate getX () const
Get the x coordinate This is the only way to access a coordinate.
Coordinate getY () const
Get the y coordinate This is the only way to access a coordinate.
Coordinate getZ () const
Get the y coordinate This is the only way to access a coordinate.
void setX (Coordinate x)
Set the x coordinate This is the only way to manipulate a coordinate.
void setY (Coordinate y)
Set the y coordinate This is the only way to manipulate a coordinate.
void setZ (Coordinate z)
Set the z coordinate This is the only way to manipulate a coordinate.
void getRawData (Coordinate *pointBuffer)
Copy raw data to input buffer (array)
Point3D & operator= (const Point3D &point)
Overridden assign operator.
Point3D operator+ (const Point3D *point)
Add a point to another point e.i each coordinate is added.
Point3D operator- (const Point3D *point)
Subtract a point to another point e.i each coordinate is substracted.
Point3D operator* (double scalar)
Multiply a point by a scalar.
void homogeneousTransformation (IHomogeneousMatrix44 *transformation)
Applies a homogeneous transformation matrix to the point.
void decorate (Point3D *point)
decorates a point
Point3D * getPoint ()
Gets the next inner skin of decoration layer With this function it is possible to traverse recursively the layers, depending on what kind of object type is returned.
virtual ColoredPoint3D * asColoredPoint3D ()
Convenience function to deduce if this point is decorated with color information.
Protected Attributes
Point3D * point
Pointer to the next inner skin of decoration layer. Can be either another decoration or a (real) Point3D.
Friends
istream & operator>> (istream &inStream, Point3D &point)
ostream & operator<< (ostream &outStream, const Point3D &point)
Detailed Description
Abstract class that can extend or "decorate" a Point3D.
Here we force the user/implementor if this decorator interface to re-implement all functions of Point3D, which will be most of the times just forwarded to the Point3D reference "point".
Definition at line 33 of file Point3DDecorator.h.
Constructor & Destructor Documentation
brics_3d::Point3DDecorator::Point3DDecorator ()
Standard constructor.
Definition at line 24 of file Point3DDecorator.cpp.
References point, and brics_3d::Point3D::Point3D().
brics_3d::Point3DDecorator::Point3DDecorator (Point3D * point)
Constructor that requires a Point3D pointer.
Parameters:
[in] point The Point3D that will be copied and wrapped/enhanced/decorated by this decorator.
Note that there is no standard constructor, to prevent a situation with an Point3DDecorator instance, but no internal Point3D specified.
Definition at line 28 of file Point3DDecorator.cpp.
References decorate().
brics_3d::Point3DDecorator::Point3DDecorator (Point3DDecorator * point)
Copy constructor.
Parameters:
point Pointer to a decorated point that will be copied and decorated
Definition at line 34 of file Point3DDecorator.cpp.
References decorate(), and getPoint().
brics_3d::Point3DDecorator::Point3DDecorator (const Point3DDecorator & point)
Copy constructor.
Parameters:
point Reference to a decorated point that will be copied and decorated
Definition at line 39 of file Point3DDecorator.cpp.
References brics_3d::Point3D::Point3D().
brics_3d::Point3DDecorator::~Point3DDecorator () [virtual]
Standard destructor.
Definition at line 47 of file Point3DDecorator.cpp.
References point.
Member Function Documentation
ColoredPoint3D * brics_3d::Point3DDecorator::asColoredPoint3D () [virtual]
Convenience function to deduce if this point is decorated with color information.
Returns:
Pointer to color object or null if there is no such decoration
Reimplemented from brics_3d::Point3D.
Reimplemented in brics_3d::ColoredPoint3D, and brics_3d::Point3DIntensity.
Definition at line 116 of file Point3DDecorator.cpp.
References brics_3d::Point3D::asColoredPoint3D(), and point.
void brics_3d::Point3DDecorator::decorate (Point3D * point)
decorates a point
Decorating means that the decorator takes over ownership/responsibility for that (inner) point. NOTE: there is no copy created, in contrast to the copy constructors.
Definition at line 108 of file Point3DDecorator.cpp.
References point.
Referenced by Point3DDecorator().
Point3D * brics_3d::Point3DDecorator::getPoint ()
Gets the next inner skin of decoration layer With this function it is possible to traverse recursively the layers, depending on what kind of object type is returned.
Definition at line 112 of file Point3DDecorator.cpp.
References point.
Referenced by Point3DDecorator().
void brics_3d::Point3DDecorator::getRawData (Coordinate * pointBuffer) [virtual]
Copy raw data to input buffer (array)
Parameters:
[out] pointBuffer Pointer to buffer, where to store the raw data
Reimplemented from brics_3d::Point3D.
Definition at line 100 of file Point3DDecorator.cpp.
References brics_3d::Point3D::getRawData(), and point.
Coordinate brics_3d::Point3DDecorator::getX () const [virtual]
Get the x coordinate This is the only way to access a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 76 of file Point3DDecorator.cpp.
References brics_3d::Point3D::getX(), and point.
Referenced by brics_3d::operator<<().
Coordinate brics_3d::Point3DDecorator::getY () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 80 of file Point3DDecorator.cpp.
References brics_3d::Point3D::getY(), and point.
Referenced by brics_3d::operator<<().
Coordinate brics_3d::Point3DDecorator::getZ () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 84 of file Point3DDecorator.cpp.
References brics_3d::Point3D::getZ(), and point.
Referenced by brics_3d::operator<<().
void brics_3d::Point3DDecorator::homogeneousTransformation (IHomogeneousMatrix44 * transformation) [virtual]
Applies a homogeneous transformation matrix to the point.
Parameters:
[in] transformation The homogeneous transformation matrix that will be applied
Reimplemented from brics_3d::Point3D.
Definition at line 104 of file Point3DDecorator.cpp.
References brics_3d::Point3D::homogeneousTransformation(), and point.
Point3D brics_3d::Point3DDecorator::operator* (double scalar) [virtual]
Multiply a point by a scalar.
Parameters:
scalar Scalar that will be multiplied to each coordinate
Returns:
Result of scalar multiplication
Reimplemented from brics_3d::Point3D.
Definition at line 62 of file Point3DDecorator.cpp.
References point.
Point3D brics_3d::Point3DDecorator::operator+ (const Point3D * point) [virtual]
Add a point to another point e.i each coordinate is added.
Parameters:
[in] point Pointer to point that will be added
Returns:
Result of addition
Reimplemented from brics_3d::Point3D.
Definition at line 54 of file Point3DDecorator.cpp.
References point.
Point3D brics_3d::Point3DDecorator::operator- (const Point3D * point) [virtual]
Subtract a point to another point e.i each coordinate is substracted.
Parameters:
[in] point Pointer to point that will be subtracted
Returns:
Result of substraction
Reimplemented from brics_3d::Point3D.
Definition at line 58 of file Point3DDecorator.cpp.
References point.
Point3DDecorator & brics_3d::Point3DDecorator::operator= (Point3DDecorator & point)
Assignement operator.
Definition at line 43 of file Point3DDecorator.cpp.
References point.
Point3D & brics_3d::Point3DDecorator::operator= (const Point3D & point) [virtual]
Overridden assign operator.
Parameters:
point Reference to right operand
Returns:
Reference to left operand
Reimplemented from brics_3d::Point3D.
Definition at line 66 of file Point3DDecorator.cpp.
References point.
void brics_3d::Point3DDecorator::setX (Coordinate x) [virtual]
Set the x coordinate This is the only way to manipulate a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 88 of file Point3DDecorator.cpp.
References point, and brics_3d::Point3D::setX().
Referenced by brics_3d::operator>>().
void brics_3d::Point3DDecorator::setY (Coordinate y) [virtual]
Set the y coordinate This is the only way to manipulate a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 92 of file Point3DDecorator.cpp.
References point, and brics_3d::Point3D::setY().
Referenced by brics_3d::operator>>().
void brics_3d::Point3DDecorator::setZ (Coordinate z) [virtual]
Set the z coordinate This is the only way to manipulate a coordinate.
Reimplemented from brics_3d::Point3D.
Definition at line 96 of file Point3DDecorator.cpp.
References point, and brics_3d::Point3D::setZ().
Referenced by brics_3d::operator>>().
Friends And Related Function Documentation
ostream& operator<< (ostream & outStream, const Point3D & point) [friend]
Writes a point to a stream e.g. std::cout << pointObj;
Parameters:
outStream The output stream
point Reference to point which data is forwarded to output stream
Returns:
Output stream
Reimplemented from brics_3d::Point3D.
Definition at line 197 of file Point3D.cpp.
istream& operator>> (istream & inStream, Point3D & point) [friend]
Reads a point from a stream an stores it. e.g. std::cin >> pointObj;
Parameters:
inStream The input stream
point Reference to point where input is stored
Returns:
Input stream
Reimplemented from brics_3d::Point3D.
Definition at line 183 of file Point3D.cpp.
Member Data Documentation
Point3D* brics_3d::Point3DDecorator::point [protected]
Pointer to the next inner skin of decoration layer. Can be either another decoration or a (real) Point3D.
Definition at line 119 of file Point3DDecorator.h.
Referenced by asColoredPoint3D(), brics_3d::ColoredPoint3D::clone(), decorate(), getPoint(), getRawData(), getX(), getY(), getZ(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), Point3DDecorator(), setX(), setY(), setZ(), and ~Point3DDecorator().
The documentation for this class was generated from the following files:
src/brics_3d/core/Point3DDecorator.h
src/brics_3d/core/Point3DDecorator.cpp