BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ConfigurationFileHandler Class Reference
brics_3d::ConfigurationFileHandler Class Reference
Reads a XML configuration file to get parameters for an algorithm.
#include <ConfigurationFileHandler.h>
Public Member Functions
ConfigurationFileHandler (const std::string filename)
Constructor.
virtual ~ConfigurationFileHandler ()
Standard destructor.
bool getAttribute (std::string algorithm, std::string attribute, std::string *result)
Get a certain attribute of an algorithm e.g a threshold, etc.
bool getAttribute (std::string algorithm, std::string attribute, int *result)
Get a certain attribute of an algorithm e.g a threshold, etc.
bool getAttribute (std::string algorithm, std::string attribute, double *result)
Get a certain attribute of an algorithm e.g a threshold, etc.
bool getSubAlgorithm (std::string algorithm, std::string subalgorithm, std::string *result)
Get the a sub brics_3d/core/component.
bool getErrorsOccured ()
Check if errors e.i.
Private Attributes
std::string filename
Stores the path to the XML configuration file.
bool errorsOccured
Flag that indicates if errors occurred during parsing.
Detailed Description
Reads a XML configuration file to get parameters for an algorithm.
The current implementation bases on the Xerces library. If Xerces is not installed all methods will return false. In general the provided functionality is abstract enough that would allow to replace Xerces, so a factory does not directly depend on Xerces.
Definition at line 43 of file ConfigurationFileHandler.h.
Constructor & Destructor Documentation
brics_3d::ConfigurationFileHandler::ConfigurationFileHandler (const std::string filename)
Constructor.
Parameters:
filename Specifies the path to the XML configuration file
Definition at line 32 of file ConfigurationFileHandler.cpp.
References errorsOccured, filename, and LOG.
brics_3d::ConfigurationFileHandler::~ConfigurationFileHandler () [virtual]
Standard destructor.
Definition at line 98 of file ConfigurationFileHandler.cpp.
Member Function Documentation
bool brics_3d::ConfigurationFileHandler::getAttribute (std::string algorithm, std::string attribute, std::string * result)
Get a certain attribute of an algorithm e.g a threshold, etc.
Parameters:
algorithm Specifies which algorithm will be searched. An algorithm is specified by the tagname of an element in the XML file
attribute Specifies which attribute of the algorithm (specified by "algorithm") will be searched. An attribute is specified by an attribute of an element in the XML file
[out] result Pointer to a string where to store the result.
Returns:
True if attribute is found, else false (or if an error occurred)
Definition at line 105 of file ConfigurationFileHandler.cpp.
References errorsOccured, and LOG.
Referenced by brics_3d::IterativeClosestPointFactory::createIterativeClosestPoint().
bool brics_3d::ConfigurationFileHandler::getAttribute (std::string algorithm, std::string attribute, int * result)
Get a certain attribute of an algorithm e.g a threshold, etc.
Parameters:
algorithm Specifies which algorithm will be searched. An algorithm is specified by the tagname of an element in the XML file
attribute Specifies which attribute of the algorithm (specified by "algorithm") will be searched. An attribute is specified by an attribute of an element in the XML file
[out] result Pointer to an integer where to store the result.
Returns:
True if attribute is found, else false (or if an error occurred)
Definition at line 189 of file ConfigurationFileHandler.cpp.
References errorsOccured, and LOG.
bool brics_3d::ConfigurationFileHandler::getAttribute (std::string algorithm, std::string attribute, double * result)
Get a certain attribute of an algorithm e.g a threshold, etc.
Parameters:
algorithm Specifies which algorithm will be searched. An algorithm is specified by the tagname of an element in the XML file
attribute Specifies which attribute of the algorithm (specified by "algorithm") will be searched. An attribute is specified by an attribute of an element in the XML file
[out] result Pointer to a double where to store the result.
Returns:
True if attribute is found, else false (or if an error occurred)
Definition at line 148 of file ConfigurationFileHandler.cpp.
References errorsOccured, and LOG.
bool brics_3d::ConfigurationFileHandler::getErrorsOccured ()
Check if errors e.i.
return errorsOccured
Returns:
True if errors occurred during parsing in initalization.
Definition at line 278 of file ConfigurationFileHandler.cpp.
References errorsOccured.
Referenced by brics_3d::IterativeClosestPointFactory::createIterativeClosestPoint().
bool brics_3d::ConfigurationFileHandler::getSubAlgorithm (std::string algorithm, std::string subalgorithm, std::string * result)
Get the a sub brics_3d/core/component.
TODO: return XML node ID to allow for arbitrary nested algorithms
Parameters:
algorithm Specifies which algorithm will be searched. An algorithm is specified by the tagname of an element in the XML file
subalgorithm Specifies which subalgorithm will be searched. A subalgorithm is specified by the tagname of a child element in the XML file.
[out] result Pointer to a string where to store the result. The returned result ist the "implementation" attribute in the XML file.
Returns:
True if attribute is found, else false (or if an error occurred)
Definition at line 230 of file ConfigurationFileHandler.cpp.
References errorsOccured, and LOG.
Referenced by brics_3d::IterativeClosestPointFactory::createIterativeClosestPoint().
Member Data Documentation
bool brics_3d::ConfigurationFileHandler::errorsOccured [private]
Flag that indicates if errors occurred during parsing.
Definition at line 117 of file ConfigurationFileHandler.h.
Referenced by ConfigurationFileHandler(), getAttribute(), getErrorsOccured(), and getSubAlgorithm().
std::string brics_3d::ConfigurationFileHandler::filename [private]
Stores the path to the XML configuration file.
Definition at line 114 of file ConfigurationFileHandler.h.
Referenced by ConfigurationFileHandler().
The documentation for this class was generated from the following files:
src/brics_3d/util/ConfigurationFileHandler.h
src/brics_3d/util/ConfigurationFileHandler.cpp