BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelLine Class Reference
brics_3d::ObjectModelLine Class Reference
Segmentation
#include <ObjectModelLine.h>
Public Member Functions
ObjectModelLine ()
virtual ~ObjectModelLine ()
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXd &model_coefficients)
void optimizeModelCoefficients (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, Eigen::VectorXd &optimized_coefficients)
void getDistancesToModel (const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Compute all distances from the cloud data to a given model.
void selectWithinDistance (const Eigen::VectorXd &model_coefficients, double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
void getInlierDistance (std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Select all the points which respect the given model coefficients as inliers.
void projectPoints (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, PointCloud3D *projectedPointCloud)
bool doSamplesVerifyModel (const std::set< int > &indices, const Eigen::VectorXd &model_coefficients, double threshold)
Verify whether a subset of indices verifies a given set of model coefficients.
void computeRandomModel (int &iterations, Eigen::VectorXd &model_coefficients, bool &isDegenerate, bool &modelFound)
Compute the model coefficients by generating some random samples.
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Detailed Description
Note:
The implementation is reusing the object model implementation in ROS:PCl
Definition at line 31 of file ObjectModelLine.h.
Constructor & Destructor Documentation
brics_3d::ObjectModelLine::ObjectModelLine () [inline]
Definition at line 33 of file ObjectModelLine.h.
virtual brics_3d::ObjectModelLine::~ObjectModelLine () [inline, virtual]
Definition at line 34 of file ObjectModelLine.h.
Member Function Documentation
bool brics_3d::ObjectModelLine::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXd & model_coefficients)
Definition at line 79 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
Referenced by computeRandomModel().
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelLine cpp void brics_3d::ObjectModelLine::computeRandomModel (int & iterations, Eigen::VectorXd & model_coefficients, bool & isDegenerate, bool & modelFound) [virtual]
Compute the model coefficients by generating some random samples.
Parameters:
model_coefficients,: the computed model coefficients
isDegenerate,: Whether degenerate samples are found from the input pointcloud or not
modelFound,: Whether a valid model is found from the sample or not
Implements brics_3d::IObjectModel.
Definition at line 25 of file ObjectModelLine.cpp.
References computeModelCoefficients(), and getSamples().
bool brics_3d::ObjectModelLine::doSamplesVerifyModel (const std::set< int > & indices, const Eigen::VectorXd & model_coefficients, double threshold) [virtual]
Verify whether a subset of indices verifies a given set of model coefficients.
Pure virtual.
Parameters:
indices the data indices that need to be tested against the model
model_coefficients the set of model coefficients
threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements brics_3d::IObjectModel.
Definition at line 274 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelLine::getDistancesToModel (const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Compute all distances from the cloud data to a given model.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
distances the resultant estimated distances
Implements brics_3d::IObjectModel.
Reimplemented in brics_3d::ObjectModelOrientedLine.
Definition at line 141 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelLine::getInlierDistance (std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
distances of inliers from the model
Implements brics_3d::IObjectModel.
Definition at line 213 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
int brics_3d::ObjectModelLine::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Implements brics_3d::IObjectModel.
Definition at line 53 of file ObjectModelLine.h.
void brics_3d::ObjectModelLine::getSamples (int & iterations, std::vector< int > & samples)
Definition at line 51 of file ObjectModelLine.cpp.
References brics_3d::IObjectModel::MAX_ITERATIONS_COLLINEAR.
Referenced by computeRandomModel().
void brics_3d::ObjectModelLine::optimizeModelCoefficients (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, Eigen::VectorXd & optimized_coefficients)
Definition at line 101 of file ObjectModelLine.cpp.
References brics_3d::compute3DCentroid(), brics_3d::computeCovarianceMatrix(), EIGEN_ALIGN_MEMORY, and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelLine::projectPoints (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, PointCloud3D * projectedPointCloud)
Definition at line 245 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelLine::selectWithinDistance (const Eigen::VectorXd & model_coefficients, double threshold, std::vector< int > & inliers) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
inliers the resultant model inliers
Implements brics_3d::IObjectModel.
Reimplemented in brics_3d::ObjectModelOrientedLine.
Definition at line 171 of file ObjectModelLine.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelLine.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelLine.cpp