BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::SimplePointCloudGeneratorCube Class Reference
brics_3d::SimplePointCloudGeneratorCube Class Reference
#include <SimplePointCloudGeneratorCube.h>
Public Member Functions
SimplePointCloudGeneratorCube ()
virtual ~SimplePointCloudGeneratorCube ()
void generatePointCloud (brics_3d::PointCloud3D *generatedPointCloud)
Generates a 3D model of a simple shape.
double getCubeSideLength () const
int getNumOfFaces () const
int getPointsOnEachSide () const
void getOrigin (double *x, double *y, double *z)
Gives the centre of the generated cube.
void setCubeSideLength (double cubeSideLength)
void setNumOfFaces (int numOfFaces)
void setOrigin (double origin[3])
void setPointsOnEachSide (int pointsOnEachSide)
Private Attributes
double cubeSideLength
Length of each side in meters.
int pointsOnEachSide
no of point in each row in a cube-side.
int numOfFaces
Number of faces in the Cube.
double origin [3]
The centroid of the generated cube.
Detailed Description
Definition at line 29 of file SimplePointCloudGeneratorCube.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d util SimplePointCloudGeneratorCube cpp brics_3d::SimplePointCloudGeneratorCube::SimplePointCloudGeneratorCube ()
Definition at line 26 of file SimplePointCloudGeneratorCube.cpp.
brics_3d::SimplePointCloudGeneratorCube::~SimplePointCloudGeneratorCube () [virtual]
Definition at line 94 of file SimplePointCloudGeneratorCube.cpp.
Member Function Documentation
void brics_3d::SimplePointCloudGeneratorCube::generatePointCloud (brics_3d::PointCloud3D * generatedPointCloud) [virtual]
Generates a 3D model of a simple shape.
Parameters:
generatedPointCloud Pointcloud representing the requested 3D model
Implements brics_3d::ISimplePointCloudGenerator.
Definition at line 99 of file SimplePointCloudGeneratorCube.cpp.
References brics_3d::PointCloud3D::addPoint(), cubeSideLength, pointsOnEachSide, brics_3d::Point3D::setX(), brics_3d::Point3D::setY(), and brics_3d::Point3D::setZ().
double brics_3d::SimplePointCloudGeneratorCube::getCubeSideLength () const
Returns:
Length of each size in meters
Definition at line 39 of file SimplePointCloudGeneratorCube.cpp.
References cubeSideLength.
int brics_3d::SimplePointCloudGeneratorCube::getNumOfFaces () const
Returns:
Number of faces in the Cube
Definition at line 45 of file SimplePointCloudGeneratorCube.cpp.
References numOfFaces.
void brics_3d::SimplePointCloudGeneratorCube::getOrigin (double * x, double * y, double * z)
Gives the centre of the generated cube.
Parameters:
x
y
z
Definition at line 87 of file SimplePointCloudGeneratorCube.cpp.
int brics_3d::SimplePointCloudGeneratorCube::getPointsOnEachSide () const
Returns:
No of point in each row in a cube-side.
Definition at line 51 of file SimplePointCloudGeneratorCube.cpp.
References pointsOnEachSide.
void brics_3d::SimplePointCloudGeneratorCube::setCubeSideLength (double cubeSideLength)
Parameters:
cubeSideLength Length of each size in meters
Definition at line 57 of file SimplePointCloudGeneratorCube.cpp.
References cubeSideLength.
void brics_3d::SimplePointCloudGeneratorCube::setNumOfFaces (int numOfFaces)
Parameters:
numOfFaces Number of faces in the Cube
Definition at line 63 of file SimplePointCloudGeneratorCube.cpp.
References numOfFaces.
void brics_3d::SimplePointCloudGeneratorCube::setOrigin (double origin[3])
Parameters:
origin The centroid of the generated cube
Definition at line 73 of file SimplePointCloudGeneratorCube.cpp.
void brics_3d::SimplePointCloudGeneratorCube::setPointsOnEachSide (int pointsOnEachSide)
Parameters:
pointsOnEachSide No of point in each row in a cube-side.
Definition at line 81 of file SimplePointCloudGeneratorCube.cpp.
References pointsOnEachSide.
Member Data Documentation
double brics_3d::SimplePointCloudGeneratorCube::cubeSideLength [private]
Length of each side in meters.
Definition at line 35 of file SimplePointCloudGeneratorCube.h.
Referenced by generatePointCloud(), getCubeSideLength(), and setCubeSideLength().
int brics_3d::SimplePointCloudGeneratorCube::numOfFaces [private]
Number of faces in the Cube.
Definition at line 46 of file SimplePointCloudGeneratorCube.h.
Referenced by getNumOfFaces(), and setNumOfFaces().
double brics_3d::SimplePointCloudGeneratorCube::origin[3] [private]
The centroid of the generated cube.
Definition at line 51 of file SimplePointCloudGeneratorCube.h.
int brics_3d::SimplePointCloudGeneratorCube::pointsOnEachSide [private]
no of point in each row in a cube-side.
This will define the point-density
Definition at line 41 of file SimplePointCloudGeneratorCube.h.
Referenced by generatePointCloud(), getPointsOnEachSide(), and setPointsOnEachSide().
The documentation for this class was generated from the following files:
src/brics_3d/util/SimplePointCloudGeneratorCube.h
src/brics_3d/util/SimplePointCloudGeneratorCube.cpp