BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::IHomogeneousMatrix44 Class Reference
brics_3d::IHomogeneousMatrix44 Class Reference
An abstract class interface to represent a homogeneous 4x4 matrix.
#include <IHomogeneousMatrix44.h>
Public Types
typedef boost::shared_ptr
< IHomogeneousMatrix44 > IHomogeneousMatrix44Ptr
typedef boost::shared_ptr
< IHomogeneousMatrix44 const > IHomogeneousMatrix44ConstPtr
Public Member Functions
IHomogeneousMatrix44 ()
Default constructor.
virtual ~IHomogeneousMatrix44 ()
Standard destructor.
virtual const double * getRawData () const =0
Returns a pointer to a read-only buffer where the raw data of the matrix is stored.
virtual double * setRawData ()=0
Returns a pointer to a writable buffer where the raw data of the matrix is stored.
virtual IHomogeneousMatrix44 * operator* (const IHomogeneousMatrix44 &matrix)=0
Multiply a matrix by another matrix.
virtual IHomogeneousMatrix44 * operator= (const IHomogeneousMatrix44 &matrix)=0
Assign a matrix to another matrix.
virtual bool isIdentity (double precision=0.00001)=0
Quick check if this matix is approximately an identity matrix.
virtual void inverse ()=0
Invert the matrix.
Friends
ostream & operator<< (ostream &outStream, const IHomogeneousMatrix44 &matrix)
Overridden << operator.
Detailed Description
An abstract class interface to represent a homogeneous 4x4 matrix.
The intention of this class is that the Point3D representation does not depend on the implementation of the transformation matrix. It only depends on this interface.
Definition at line 38 of file IHomogeneousMatrix44.h.
Member Typedef Documentation
typedef boost::shared_ptr<IHomogeneousMatrix44 const> brics_3d::IHomogeneousMatrix44::IHomogeneousMatrix44ConstPtr
Definition at line 42 of file IHomogeneousMatrix44.h.
typedef boost::shared_ptr<IHomogeneousMatrix44> brics_3d::IHomogeneousMatrix44::IHomogeneousMatrix44Ptr
Definition at line 41 of file IHomogeneousMatrix44.h.
Constructor & Destructor Documentation
brics_3d::IHomogeneousMatrix44::IHomogeneousMatrix44 () [inline]
Default constructor.
Definition at line 47 of file IHomogeneousMatrix44.h.
virtual brics_3d::IHomogeneousMatrix44::~IHomogeneousMatrix44 () [inline, virtual]
Standard destructor.
Definition at line 52 of file IHomogeneousMatrix44.h.
Member Function Documentation
virtual const double* brics_3d::IHomogeneousMatrix44::getRawData () const [pure virtual]
Returns a pointer to a read-only buffer where the raw data of the matrix is stored.
Important: the 16 values are stored in column-row order! So the layout is:
0 4 8 12
1 5 9 13
2 6 10 14
3 7 11 15
Returns:
(Constant) pointer to buffer where the matrix is stored. Buffer has a size of 16 double values.
Implemented in brics_3d::HomogeneousMatrix44.
Referenced by brics_3d::Vector3D::homogeneousTransformation(), and brics_3d::Point3D::homogeneousTransformation().
virtual void brics_3d::IHomogeneousMatrix44::inverse () [pure virtual]
Invert the matrix.
Implemented in brics_3d::HomogeneousMatrix44.
virtual bool brics_3d::IHomogeneousMatrix44::isIdentity (double precision = 0.00001) [pure virtual]
Quick check if this matix is approximately an identity matrix.
Parameters:
precision Precision when matrix elemets are considered to be equal
Returns:
True if it is approximately an identity matrix.
Implemented in brics_3d::HomogeneousMatrix44.
virtual IHomogeneousMatrix44* brics_3d::IHomogeneousMatrix44::operator* (const IHomogeneousMatrix44 & matrix) [pure virtual]
Multiply a matrix by another matrix.
Parameters:
matrix Multiplicand matrix
Returns:
Result of matrix multiplication
Implemented in brics_3d::HomogeneousMatrix44.
virtual IHomogeneousMatrix44* brics_3d::IHomogeneousMatrix44::operator= (const IHomogeneousMatrix44 & matrix) [pure virtual]
Assign a matrix to another matrix.
Parameters:
matrix R-value matrix
Implemented in brics_3d::HomogeneousMatrix44.
virtual double* brics_3d::IHomogeneousMatrix44::setRawData () [pure virtual]
Returns a pointer to a writable buffer where the raw data of the matrix is stored.
Implemented in brics_3d::HomogeneousMatrix44.
Referenced by brics_3d::RigidTransformationEstimationSVD::estimateTransformation(), brics_3d::RigidTransformationEstimationQUAT::estimateTransformation(), brics_3d::RigidTransformationEstimationORTHO::estimateTransformation(), brics_3d::RigidTransformationEstimationHELIX::estimateTransformation(), and brics_3d::RigidTransformationEstimationAPX::estimateTransformation().
Friends And Related Function Documentation
ostream& operator<< (ostream & outStream, const IHomogeneousMatrix44 & matrix) [friend]
Overridden << operator.
Writes a homogeneous matrix to a stream e.g. std::cout << homMatObj;
Parameters:
outStream The output stream
matrix Pointer to homogeneous matrix which data is forwarded to the output stream
Returns:
Output stream
Reimplemented in brics_3d::HomogeneousMatrix44.
Definition at line 126 of file HomogeneousMatrix44.cpp.
The documentation for this class was generated from the following file:
src/brics_3d/core/IHomogeneousMatrix44.h