BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Vector3D Class Reference
brics_3d::Vector3D Class Reference
#include <Vector3D.h>
Public Member Functions
Vector3D ()
Default constructor.
Vector3D (Coordinate x, Coordinate y, Coordinate z)
Constructor with full initialization.
Vector3D (Vector3D *point)
Copy constructor.
virtual ~Vector3D ()
Standard destructor.
virtual Coordinate getX () const
Get the x coordinate This is the only way to access a coordinate.
virtual Coordinate getY () const
Get the y coordinate This is the only way to access a coordinate.
virtual Coordinate getZ () const
Get the y coordinate This is the only way to access a coordinate.
virtual void setX (Coordinate x)
Set the x coordinate This is the only way to manipulate a coordinate.
virtual void setY (Coordinate y)
Set the y coordinate This is the only way to manipulate a coordinate.
virtual void setZ (Coordinate z)
Set the z coordinate This is the only way to manipulate a coordinate.
virtual void getRawData (Coordinate *pointBuffer)
Copy raw data to input buffer (array)
virtual Vector3D operator+ (const Vector3D *point)
Add a point to another point e.i each coordinate is added.
virtual Vector3D operator- (const Vector3D *point)
Subtract a point to another point e.i each coordinate is substracted.
virtual Vector3D operator* (double scalar)
Multiply a point by a scalar.
virtual Vector3D & operator= (const Vector3D &point)
Overridden assign operator.
virtual void homogeneousTransformation (IHomogeneousMatrix44 *transformation)
Applies a homogeneous transformation matrix to the point.
Private Attributes
Coordinate x
X coordinate in Cartesian system.
Coordinate y
Y coordinate in Cartesian system.
Coordinate z
Z coordinate in Cartesian system (height)
Friends
istream & operator>> (istream &inStream, Vector3D &point)
Overridden >> operator.
ostream & operator<< (ostream &outStream, const Vector3D &point)
Overridden << operator.
Detailed Description
Definition at line 41 of file Vector3D.h.
Constructor & Destructor Documentation
brics_3d::Vector3D::Vector3D ()
Default constructor.
Definition at line 36 of file Vector3D.cpp.
References x, y, and z.
brics_3d::Vector3D::Vector3D (Coordinate x, Coordinate y, Coordinate z)
Constructor with full initialization.
Parameters:
x X coordinate in Cartesian system
y Y coordinate in Cartesian system
z Z coordinate in Cartesian system (height)
Definition at line 48 of file Vector3D.cpp.
References x, y, and z.
brics_3d::Vector3D::Vector3D (Vector3D * point)
Copy constructor.
Parameters:
[in] point Pointer to point that will be copied
Definition at line 42 of file Vector3D.cpp.
References getX(), getY(), getZ(), x, y, and z.
brics_3d::Vector3D::~Vector3D () [virtual]
Standard destructor.
Definition at line 54 of file Vector3D.cpp.
Member Function Documentation
void brics_3d::Vector3D::getRawData (Coordinate * pointBuffer) [virtual]
Copy raw data to input buffer (array)
Parameters:
[out] pointBuffer Pointer to buffer, where to store the raw data
Definition at line 80 of file Vector3D.cpp.
References x, y, and z.
Coordinate brics_3d::Vector3D::getX () const [virtual]
Get the x coordinate This is the only way to access a coordinate.
Definition at line 58 of file Vector3D.cpp.
References x.
Referenced by brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::operator<<(), operator=(), and Vector3D().
Coordinate brics_3d::Vector3D::getY () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Definition at line 62 of file Vector3D.cpp.
References y.
Referenced by brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::operator<<(), operator=(), and Vector3D().
Coordinate brics_3d::Vector3D::getZ () const [virtual]
Get the y coordinate This is the only way to access a coordinate.
Definition at line 66 of file Vector3D.cpp.
References z.
Referenced by brics_3d::NormalEstimation::flipNormalTowardsViewpoint(), brics_3d::operator<<(), operator=(), and Vector3D().
void brics_3d::Vector3D::homogeneousTransformation (IHomogeneousMatrix44 * transformation) [virtual]
Applies a homogeneous transformation matrix to the point.
Parameters:
[in] transformation The homogeneous transformation matrix that will be applied
Definition at line 147 of file Vector3D.cpp.
References brics_3d::IHomogeneousMatrix44::getRawData(), x, y, and z.
Vector3D brics_3d::Vector3D::operator* (double scalar) [virtual]
Multiply a point by a scalar.
Parameters:
scalar Scalar that will be multiplied to each coordinate
Returns:
Result of scalar multiplication
Definition at line 120 of file Vector3D.cpp.
References x, y, and z.
Vector3D brics_3d::Vector3D::operator+ (const Vector3D * point) [virtual]
Add a point to another point e.i each coordinate is added.
Parameters:
[in] point Pointer to point that will be added
Returns:
Result of addition
Definition at line 86 of file Vector3D.cpp.
References x, y, and z.
Vector3D brics_3d::Vector3D::operator- (const Vector3D * point) [virtual]
Subtract a point to another point e.i each coordinate is substracted.
Parameters:
[in] point Pointer to point that will be subtracted
Returns:
Result of substraction
Definition at line 103 of file Vector3D.cpp.
References x, y, and z.
Vector3D & brics_3d::Vector3D::operator= (const Vector3D & point) [virtual]
Overridden assign operator.
Parameters:
point Reference to right operand
Returns:
Reference to left operand
Definition at line 137 of file Vector3D.cpp.
References getX(), getY(), getZ(), x, y, and z.
void brics_3d::Vector3D::setX (Coordinate x) [virtual]
Set the x coordinate This is the only way to manipulate a coordinate.
Definition at line 70 of file Vector3D.cpp.
References x.
Referenced by brics_3d::NormalEstimation::computeFeature(), and brics_3d::NormalEstimation::flipNormalTowardsViewpoint().
void brics_3d::Vector3D::setY (Coordinate y) [virtual]
Set the y coordinate This is the only way to manipulate a coordinate.
Definition at line 73 of file Vector3D.cpp.
References y.
Referenced by brics_3d::NormalEstimation::computeFeature(), and brics_3d::NormalEstimation::flipNormalTowardsViewpoint().
void brics_3d::Vector3D::setZ (Coordinate z) [virtual]
Set the z coordinate This is the only way to manipulate a coordinate.
Definition at line 76 of file Vector3D.cpp.
References z.
Referenced by brics_3d::NormalEstimation::computeFeature(), and brics_3d::NormalEstimation::flipNormalTowardsViewpoint().
Friends And Related Function Documentation
ostream& operator<< (ostream & outStream, const Vector3D & point) [friend]
Overridden << operator.
Writes a point to a stream e.g. std::cout << pointObj;
Parameters:
outStream The output stream
point Reference to point which data is forwarded to output stream
Returns:
Output stream
Definition at line 190 of file Vector3D.cpp.
istream& operator>> (istream & inStream, Vector3D & point) [friend]
Overridden >> operator.
Reads a point from a stream an stores it. e.g. std::cin >> pointObj;
Parameters:
inStream The input stream
point Reference to point where input is stored
Returns:
Input stream
Definition at line 176 of file Vector3D.cpp.
Member Data Documentation
Coordinate brics_3d::Vector3D::x [private]
X coordinate in Cartesian system.
Definition at line 170 of file Vector3D.h.
Referenced by getRawData(), getX(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), setX(), and Vector3D().
Coordinate brics_3d::Vector3D::y [private]
Y coordinate in Cartesian system.
Definition at line 173 of file Vector3D.h.
Referenced by getRawData(), getY(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), setY(), and Vector3D().
Coordinate brics_3d::Vector3D::z [private]
Z coordinate in Cartesian system (height)
Definition at line 176 of file Vector3D.h.
Referenced by getRawData(), getZ(), homogeneousTransformation(), operator*(), operator+(), operator-(), operator=(), brics_3d::operator>>(), setZ(), and Vector3D().
The documentation for this class was generated from the following files:
src/brics_3d/core/Vector3D.h
src/brics_3d/core/Vector3D.cpp