BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::DotVisualizer Class Reference
brics_3d::rsg::DotVisualizer Class Reference
Scenegraph
Observer that will create a print out on every update.
#include <DotVisualizer.h>
Public Member Functions
DotVisualizer (brics_3d::rsg::SceneGraphFacade *scene)
virtual ~DotVisualizer ()
bool addNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)
Add a new Node to the robot scene graph.
bool addGroup (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, bool forcedId=false)
Add a Group node to the robot scenegraph.
bool addTransformNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId=false)
Add a new Transform node the the robot scene graph.
bool addGeometricNode (unsigned int parentId, unsigned int &assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId=false)
Add a GeometricNode that contains 3D data to the robot scene graph.
bool setNodeAttributes (unsigned int id, vector< Attribute > newAttributes)
Override the attributes of a node.
bool setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp)
Update the transformation of an existing Transform node.
bool deleteNode (unsigned int id)
Delete a node in the robot scenegraph.
bool addParent (unsigned int id, unsigned int parentId)
Add a new parent-child relation between two nodes.
bool getKeepHistory () const
void setKeepHistory (bool keepHistory)
Private Member Functions
void printGraph ()
Print the current graph into a file.
Private Attributes
brics_3d::rsg::SceneGraphFacade * scene
Handle the to the scene to be observed.
brics_3d::rsg::DotGraphGenerator graphPrinter
Traverser to produce a dot file.
std::ofstream output
bool keepHistory
If true all printaout will be saved to disk with a running number as part of the file name.
unsigned int counter
Detailed Description
Observer that will create a print out on every update.
Note:
You need to have the dot executable installed on your system.
Definition at line 39 of file DotVisualizer.h.
Constructor & Destructor Documentation
brics_3d::rsg::DotVisualizer::DotVisualizer (brics_3d::rsg::SceneGraphFacade * scene)
Definition at line 29 of file DotVisualizer.cpp.
References counter, and keepHistory.
brics_3d::rsg::DotVisualizer::~DotVisualizer () [virtual]
Definition at line 34 of file DotVisualizer.cpp.
Member Function Documentation
bool brics_3d::rsg::DotVisualizer::addGeometricNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, Shape::ShapePtr shape, TimeStamp timeStamp, bool forcedId = false) [virtual]
Add a GeometricNode that contains 3D data to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
shape The geometic Shape to be contained the the GeometricNode. Multiple shape types are possible like a Box, a Cylinder a Mesh or a PointCloud for instance.
timeStamp Time stamp assiciated with the geometic Shape.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new GeometricNode was sucessfully added to the scen egraph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 54 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::addGroup (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [virtual]
Add a Group node to the robot scenegraph.
The group allows to create the graph structure as it has children, in contrast to a simple node.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Group was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 44 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::addNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, bool forcedId = false) [virtual]
Add a new Node to the robot scene graph.
Parameters:
[in] parentId ID of the parent node. To add more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
[in] forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Node was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 39 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::addParent (unsigned int id, unsigned int parentId) [virtual]
Add a new parent-child relation between two nodes.
Parameters:
id ID of the node
parentId ID of the parent node. Must not be a leave like a Node or a GeometricNode
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 74 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::addTransformNode (unsigned int parentId, unsigned int & assignedId, vector< Attribute > attributes, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp, bool forcedId = false) [virtual]
Add a new Transform node the the robot scene graph.
Internally brics_3d::rsg::Transform is used that is able to maintain a temporal cache of the trnasform data.
Parameters:
[in] parentId ID of the parent node. To add more more parents use the brics_3d::rsg::ISceneGraphUpdate::addParent() function.
[in,out] assignedId The ID that was assigned internally. In case the forcedId flag has been set to true it will used instead of the internal ID assignment. Use this functio with care. There are are some internal checks if the manually assigned is valid but do not rely on this in a distibuted setting.
[in] attributes A set of attributs that will be set for the node.
transform The actual transform data that will be (initially) inserted. You can later insert more with brics_3d::rsg::ISceneGraphUpdate::setTransform() .
timeStamp Time stamp associated with the transform.
forcedId If set to true the ID defined in assignedId will be taken instead of an intanally generated one. This is in particular useful if distibuted scene graphs propagate updates and ensures IDs are not re-created.
Returns:
True if a new Transform was sucessfully added to the scene graph.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 49 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::deleteNode (unsigned int id) [virtual]
Delete a node in the robot scenegraph.
Parameters:
id ID the defines the node to be deleted.
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 69 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::getKeepHistory () const [inline]
Definition at line 54 of file DotVisualizer.h.
References keepHistory.
void brics_3d::rsg::DotVisualizer::printGraph () [private]
Print the current graph into a file.
Definition at line 79 of file DotVisualizer.cpp.
References counter, brics_3d::rsg::SceneGraphFacade::executeGraphTraverser(), brics_3d::rsg::DotGraphGenerator::getDotGraph(), brics_3d::rsg::SceneGraphFacade::getRootId(), graphPrinter, keepHistory, LOG, output, brics_3d::rsg::DotGraphGenerator::reset(), and scene.
Referenced by addGeometricNode(), addGroup(), addNode(), addParent(), addTransformNode(), deleteNode(), setNodeAttributes(), and setTransform().
void brics_3d::rsg::DotVisualizer::setKeepHistory (bool keepHistory) [inline]
Definition at line 59 of file DotVisualizer.h.
References keepHistory.
bool brics_3d::rsg::DotVisualizer::setNodeAttributes (unsigned int id, vector< Attribute > newAttributes) [virtual]
Override the attributes of a node.
Parameters:
id ID the defines the node to be updated.
newAttributes The new attributes. THe old one will be overidden by tis
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 59 of file DotVisualizer.cpp.
References printGraph().
bool brics_3d::rsg::DotVisualizer::setTransform (unsigned int id, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr transform, TimeStamp timeStamp) [virtual]
Update the transformation of an existing Transform node.
Parameters:
id ID the defines the Transform node to be updated.
transform The transform data that will be inserted in to the cacje of the Transform.
timeStamp Time stamp associated with the transform.
Returns:
True on success.
Implements brics_3d::rsg::ISceneGraphUpdate.
Definition at line 64 of file DotVisualizer.cpp.
References printGraph().
Member Data Documentation
unsigned int brics_3d::rsg::DotVisualizer::counter [private]
Definition at line 81 of file DotVisualizer.h.
Referenced by DotVisualizer(), and printGraph().
brics_3d::rsg::DotGraphGenerator brics_3d::rsg::DotVisualizer::graphPrinter [private]
Traverser to produce a dot file.
Definition at line 69 of file DotVisualizer.h.
Referenced by printGraph().
bool brics_3d::rsg::DotVisualizer::keepHistory [private]
If true all printaout will be saved to disk with a running number as part of the file name.
Definition at line 79 of file DotVisualizer.h.
Referenced by DotVisualizer(), getKeepHistory(), printGraph(), and setKeepHistory().
std::ofstream brics_3d::rsg::DotVisualizer::output [private]
Definition at line 71 of file DotVisualizer.h.
Referenced by printGraph().
brics_3d::rsg::SceneGraphFacade* brics_3d::rsg::DotVisualizer::scene [private]
Handle the to the scene to be observed.
Definition at line 66 of file DotVisualizer.h.
Referenced by printGraph().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/DotVisualizer.h
src/brics_3d/worldModel/sceneGraph/DotVisualizer.cpp