BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::PointCorrespondenceGenericNN Class Reference
brics_3d::PointCorrespondenceGenericNN Class Reference
Registration
Implementation of correspondence problem for points using generic nearest neighbor search.
#include <PointCorrespondenceGenericNN.h>
Public Member Functions
PointCorrespondenceGenericNN ()
Standard constructor.
PointCorrespondenceGenericNN (INearestPoint3DNeighbor *nearestNeighborAlgorithm)
Constructor that defines the nearest neighbor search strategy.
virtual ~PointCorrespondenceGenericNN ()
Standard destructor.
void createNearestNeighborCorrespondence (PointCloud3D *pointCloud1, PointCloud3D *pointCloud2, std::vector< CorrespondencePoint3DPair > *resultPointPairs)
Establishes a point to point correspondence with nearest neighborhood search.
INearestPoint3DNeighbor * getNearestNeighborAlgorithm () const
Get the nearest neighbor search strategy.
void setNearestNeighborAlgorithm (INearestPoint3DNeighbor *nearestNeighborAlgorithm)
Set the nearest neighbor search strategy.
Private Attributes
INearestPoint3DNeighbor * nearestNeighborAlgorithm
Internal handle to the nearest neighbor search strategy.
Detailed Description
Implementation of correspondence problem for points using generic nearest neighbor search.
Definition at line 32 of file PointCorrespondenceGenericNN.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d algorithm registration PointCorrespondenceGenericNN cpp brics_3d::PointCorrespondenceGenericNN::PointCorrespondenceGenericNN ()
Standard constructor.
Definition at line 27 of file PointCorrespondenceGenericNN.cpp.
brics_3d::PointCorrespondenceGenericNN::PointCorrespondenceGenericNN (INearestPoint3DNeighbor * nearestNeighborAlgorithm)
Constructor that defines the nearest neighbor search strategy.
Parameters:
[in] nearestNeighborAlgorithm The nearest neighbor search strategy that will be used
Definition at line 32 of file PointCorrespondenceGenericNN.cpp.
brics_3d::PointCorrespondenceGenericNN::~PointCorrespondenceGenericNN () [virtual]
Standard destructor.
Definition at line 36 of file PointCorrespondenceGenericNN.cpp.
References nearestNeighborAlgorithm.
Member Function Documentation
void brics_3d::PointCorrespondenceGenericNN::createNearestNeighborCorrespondence (PointCloud3D * pointCloud1, PointCloud3D * pointCloud2, std::vector< CorrespondencePoint3DPair > * resultPointPairs) [virtual]
Establishes a point to point correspondence with nearest neighborhood search.
Parameters:
[in] pointCloud1 Pointer to first point cloud
[in] pointCloud2 Pointer to second point cloud
[out] resultPointPairs Pointer where to store the resulting point correspondences. If no correspondences are found, this vector will be empty.
Implements brics_3d::IPointCorrespondence.
Definition at line 42 of file PointCorrespondenceGenericNN.cpp.
References brics_3d::INearestPoint3DNeighbor::findNearestNeighbors(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), nearestNeighborAlgorithm, and brics_3d::INearestPoint3DNeighbor::setData().
INearestPoint3DNeighbor * brics_3d::PointCorrespondenceGenericNN::getNearestNeighborAlgorithm () const
Get the nearest neighbor search strategy.
Returns:
Returns the nearest neighbor search strategy
Definition at line 77 of file PointCorrespondenceGenericNN.cpp.
void brics_3d::PointCorrespondenceGenericNN::setNearestNeighborAlgorithm (INearestPoint3DNeighbor * nearestNeighborAlgorithm)
Set the nearest neighbor search strategy.
Parameters:
[in] nearestNeighborAlgorithm The nearest neighbor search strategy that will be used
Definition at line 81 of file PointCorrespondenceGenericNN.cpp.
Member Data Documentation
INearestPoint3DNeighbor* brics_3d::PointCorrespondenceGenericNN::nearestNeighborAlgorithm [private]
Internal handle to the nearest neighbor search strategy.
Definition at line 68 of file PointCorrespondenceGenericNN.h.
Referenced by createNearestNeighborCorrespondence(), and ~PointCorrespondenceGenericNN().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/registration/PointCorrespondenceGenericNN.h
src/brics_3d/algorithm/registration/PointCorrespondenceGenericNN.cpp