BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::MetricCalculator Class Reference
brics_3d::MetricCalculator Class Reference
Performs all the calculation for generating the results of evaluation metrics.
#include <MetricCalculator.h>
Public Member Functions
MetricCalculator ()
virtual ~MetricCalculator ()
int calculateMetrics ()
double ** getResultGtMetrics () const
double ** getResultMsMetrics () const
double ** getResultOverlap () const
int getNoOfMetricsGt ()
int getNoOfMetricsMs ()
void setEvaluatorObject (Evaluator evaluatorObj)
Evaluator getEvaluatorObject ()
int compareVectors (vector< string > &v1, vector< string > &v2)
Method to copare two vectors and return number of identical elements.
int maxElementIndex (double array[], int start, int end)
Returns the index of the largest element in the array.
Private Member Functions
void calculateOverlap ()
void calculateGtMetrics ()
void calculateMsMetrics ()
Private Attributes
double ** resultOverlap
double ** resultGtMetrics
double ** resultMsMetrics
Evaluator evaluatorObject
Static Private Attributes
static const int noOfMetricsGt = 5
static const int noOfMetricsMs = 5
static const int size_of_region_gt = 0
static const int correct_detection = 1
static const int no_overseg_region = 2
static const int percent_overseg_region = 3
static const int percent_non_classification = 4
static const int size_of_region_ms = 0
static const int percent_wrong_classification = 1
static const int no_underseg_region = 2
static const int percent_underseg = 3
static const int percent_noise_classification = 4
Detailed Description
Performs all the calculation for generating the results of evaluation metrics.
Definition at line 32 of file MetricCalculator.h.
Constructor & Destructor Documentation
brics_3d::MetricCalculator::MetricCalculator ()
Definition at line 23 of file MetricCalculator.cpp.
brics_3d::MetricCalculator::~MetricCalculator () [virtual]
Definition at line 340 of file MetricCalculator.cpp.
Member Function Documentation
void brics_3d::MetricCalculator::calculateGtMetrics () [private]
Definition at line 186 of file MetricCalculator.cpp.
References correct_detection, evaluatorObject, brics_3d::Evaluator::getCountGt(), brics_3d::Evaluator::getCountMs(), brics_3d::Evaluator::getImageSize(), no_overseg_region, percent_non_classification, percent_overseg_region, resultGtMetrics, resultOverlap, and size_of_region_gt.
Referenced by calculateMetrics().
int brics_3d::MetricCalculator::calculateMetrics ()
Definition at line 44 of file MetricCalculator.cpp.
References calculateGtMetrics(), calculateMsMetrics(), calculateOverlap(), evaluatorObject, brics_3d::Evaluator::getCountGt(), brics_3d::Evaluator::getCountMs(), brics_3d::Evaluator::getImageSize(), brics_3d::Evaluator::IsInitialized(), noOfMetricsGt, noOfMetricsMs, resultGtMetrics, resultMsMetrics, and resultOverlap.
void brics_3d::MetricCalculator::calculateMsMetrics () [private]
Definition at line 227 of file MetricCalculator.cpp.
References evaluatorObject, brics_3d::Evaluator::getCountGt(), brics_3d::Evaluator::getCountMs(), brics_3d::Evaluator::getImageSize(), no_underseg_region, percent_noise_classification, percent_underseg, percent_wrong_classification, resultMsMetrics, resultOverlap, and size_of_region_ms.
Referenced by calculateMetrics().
void brics_3d::MetricCalculator::calculateOverlap () [private]
Definition at line 97 of file MetricCalculator.cpp.
References compareVectors(), evaluatorObject, brics_3d::Evaluator::getCountGt(), brics_3d::Evaluator::getCountMs(), brics_3d::Evaluator::getRegionCorrespondence(), resultOverlap, brics_3d::Evaluator::vectorGt, and brics_3d::Evaluator::vectorMs.
Referenced by calculateMetrics().
int brics_3d::MetricCalculator::compareVectors (vector< string > & v1, vector< string > & v2)
Method to copare two vectors and return number of identical elements.
It also deletes the elements from the vectors that have matched with an element from the other vector
Definition at line 287 of file MetricCalculator.cpp.
Referenced by calculateOverlap().
Evaluator brics_3d::MetricCalculator::getEvaluatorObject ()
Definition at line 328 of file MetricCalculator.cpp.
References evaluatorObject.
int brics_3d::MetricCalculator::getNoOfMetricsGt ()
Definition at line 332 of file MetricCalculator.cpp.
References noOfMetricsGt.
int brics_3d::MetricCalculator::getNoOfMetricsMs ()
Definition at line 336 of file MetricCalculator.cpp.
References noOfMetricsMs.
double ** brics_3d::MetricCalculator::getResultGtMetrics () const
Definition at line 25 of file MetricCalculator.cpp.
References resultGtMetrics.
double ** brics_3d::MetricCalculator::getResultMsMetrics () const
Definition at line 30 of file MetricCalculator.cpp.
References resultMsMetrics.
double ** brics_3d::MetricCalculator::getResultOverlap () const
Definition at line 35 of file MetricCalculator.cpp.
References resultOverlap.
int brics_3d::MetricCalculator::maxElementIndex (double array[], int start, int end)
Returns the index of the largest element in the array.
start and end defines the span of indexes to be checked for
Definition at line 310 of file MetricCalculator.cpp.
void brics_3d::MetricCalculator::setEvaluatorObject (Evaluator evaluatorObj)
Definition at line 40 of file MetricCalculator.cpp.
References evaluatorObject.
Member Data Documentation
const int brics_3d::MetricCalculator::correct_detection = 1 [static, private]
Definition at line 41 of file MetricCalculator.h.
Referenced by calculateGtMetrics().
Evaluator brics_3d::MetricCalculator::evaluatorObject [private]
Definition at line 37 of file MetricCalculator.h.
Referenced by calculateGtMetrics(), calculateMetrics(), calculateMsMetrics(), calculateOverlap(), getEvaluatorObject(), and setEvaluatorObject().
const int brics_3d::MetricCalculator::no_overseg_region = 2 [static, private]
Definition at line 42 of file MetricCalculator.h.
Referenced by calculateGtMetrics().
const int brics_3d::MetricCalculator::no_underseg_region = 2 [static, private]
Definition at line 47 of file MetricCalculator.h.
Referenced by calculateMsMetrics().
const int brics_3d::MetricCalculator::noOfMetricsGt = 5 [static, private]
Definition at line 38 of file MetricCalculator.h.
Referenced by calculateMetrics(), and getNoOfMetricsGt().
const int brics_3d::MetricCalculator::noOfMetricsMs = 5 [static, private]
Definition at line 39 of file MetricCalculator.h.
Referenced by calculateMetrics(), and getNoOfMetricsMs().
const int brics_3d::MetricCalculator::percent_noise_classification = 4 [static, private]
Definition at line 49 of file MetricCalculator.h.
Referenced by calculateMsMetrics().
const int brics_3d::MetricCalculator::percent_non_classification = 4 [static, private]
Definition at line 44 of file MetricCalculator.h.
Referenced by calculateGtMetrics().
const int brics_3d::MetricCalculator::percent_overseg_region = 3 [static, private]
Definition at line 43 of file MetricCalculator.h.
Referenced by calculateGtMetrics().
const int brics_3d::MetricCalculator::percent_underseg = 3 [static, private]
Definition at line 48 of file MetricCalculator.h.
Referenced by calculateMsMetrics().
const int brics_3d::MetricCalculator::percent_wrong_classification = 1 [static, private]
Definition at line 46 of file MetricCalculator.h.
Referenced by calculateMsMetrics().
double** brics_3d::MetricCalculator::resultGtMetrics [private]
Definition at line 35 of file MetricCalculator.h.
Referenced by calculateGtMetrics(), calculateMetrics(), and getResultGtMetrics().
double** brics_3d::MetricCalculator::resultMsMetrics [private]
Definition at line 36 of file MetricCalculator.h.
Referenced by calculateMetrics(), calculateMsMetrics(), and getResultMsMetrics().
double** brics_3d::MetricCalculator::resultOverlap [private]
Definition at line 34 of file MetricCalculator.h.
Referenced by calculateGtMetrics(), calculateMetrics(), calculateMsMetrics(), calculateOverlap(), and getResultOverlap().
const int brics_3d::MetricCalculator::size_of_region_gt = 0 [static, private]
Definition at line 40 of file MetricCalculator.h.
Referenced by calculateGtMetrics().
const int brics_3d::MetricCalculator::size_of_region_ms = 0 [static, private]
Definition at line 45 of file MetricCalculator.h.
Referenced by calculateMsMetrics().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/evaluation/MetricCalculator.h
src/brics_3d/algorithm/segmentation/evaluation/MetricCalculator.cpp