BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::IterativeClosestPointFactory Class Reference
brics_3d::IterativeClosestPointFactory Class Reference
Registration
IterativeClosestPoint factory that can be configured with a XML file.
#include <IterativeClosestPointFactory.h>
Public Member Functions
IterativeClosestPointFactory ()
Standard constructor.
virtual ~IterativeClosestPointFactory ()
Standard destructor.
IIterativeClosestPointPtr createIterativeClosestPoint ()
Factory method the returns an IterativeClosestPoint in a standard configuration.
IIterativeClosestPointPtr createIterativeClosestPoint (std::string configurationFile)
Factory method the returns an IterativeClosestPoint configured by an XML file.
IIterativeClosestPointSetupPtr getIcpSetupHandle ()
Get an ICP setup handle, if available.
Private Attributes
IIterativeClosestPointSetupPtr icpConfigurator
Detailed Description
IterativeClosestPoint factory that can be configured with a XML file.
Definition at line 41 of file IterativeClosestPointFactory.h.
Constructor & Destructor Documentation
brics_3d::IterativeClosestPointFactory::IterativeClosestPointFactory ()
Standard constructor.
Definition at line 42 of file IterativeClosestPointFactory.cpp.
brics_3d::IterativeClosestPointFactory::~IterativeClosestPointFactory () [virtual]
Standard destructor.
Definition at line 46 of file IterativeClosestPointFactory.cpp.
Member Function Documentation
IIterativeClosestPointPtr brics_3d::IterativeClosestPointFactory::createIterativeClosestPoint ()
Factory method the returns an IterativeClosestPoint in a standard configuration.
Definition at line 50 of file IterativeClosestPointFactory.cpp.
References icpConfigurator.
Referenced by createIterativeClosestPoint().
IIterativeClosestPointPtr brics_3d::IterativeClosestPointFactory::createIterativeClosestPoint (std::string configurationFile)
Factory method the returns an IterativeClosestPoint configured by an XML file.
Wrong parameters descriptions in the XML file will be handled as warnings and the default parameter is chosen.
Parameters:
configurationFile Path to the XML configuration file
Returns:
Returns an instance of the abstract Iterative Closest Point interface
Example XML file:
<!DOCTYPE dummy>
<BRICS_3D-Configuration>
<IterativeClosestPoint implementation="IterativeClosestPoint" maxiterations="25" convergencethreshold="0.001">
<PointCorrespondence implementation="PointCorrespondenceKDTree"></PointCorrespondence>
<RigidTransformationEstimation implementation="RigidTransformationEstimationSVD"></RigidTransformationEstimation>
</IterativeClosestPoint>
</BRICS_3D-Configuration>
NOTE1: The current implementation of the ConfigurationFileHandlerTest configuration file parser bases on the Xerces library. If it is not installed the default configuration is choosen.
Definition at line 58 of file IterativeClosestPointFactory.cpp.
References createIterativeClosestPoint(), brics_3d::ConfigurationFileHandler::getAttribute(), brics_3d::ConfigurationFileHandler::getErrorsOccured(), brics_3d::ConfigurationFileHandler::getSubAlgorithm(), icpConfigurator, and LOG.
IIterativeClosestPointSetupPtr brics_3d::IterativeClosestPointFactory::getIcpSetupHandle ()
Get an ICP setup handle, if available.
Returns:
Returns the handle to the IIterativeClosestPointSetup interface of the last invocation of createIterativeClosestPoint if available. Otherwise returns 0.
Definition at line 182 of file IterativeClosestPointFactory.cpp.
References icpConfigurator.
Member Data Documentation
IIterativeClosestPointSetupPtr brics_3d::IterativeClosestPointFactory::icpConfigurator [private]
Definition at line 94 of file IterativeClosestPointFactory.h.
Referenced by createIterativeClosestPoint(), and getIcpSetupHandle().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/registration/IterativeClosestPointFactory.h
src/brics_3d/algorithm/registration/IterativeClosestPointFactory.cpp