BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::BoxROIExtractor Class Reference
brics_3d::BoxROIExtractor Class Reference
The origin of box is considered to be in the center of each size value.
#include <BoxROIExtractor.h>
Public Member Functions
BoxROIExtractor ()
BoxROIExtractor (Coordinate sizeX, Coordinate sizeY, Coordinate sizeZ)
virtual ~BoxROIExtractor ()
void filter (PointCloud3D *originalPointCloud, PointCloud3D *resultPointCloud)
Filter a point cloud.
Coordinate getSizeX () const
Coordinate getSizeY () const
Coordinate getSizeZ () const
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr getBoxOrigin () const
void setSizeX (Coordinate sizeX)
void setSizeY (Coordinate sizeY)
void setSizeZ (Coordinate sizeZ)
void setBoxOrigin (IHomogeneousMatrix44::IHomogeneousMatrix44Ptr boxOrigin)
Private Attributes
Coordinate sizeX
Coordinate sizeY
Coordinate sizeZ
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr boxOrigin
Detailed Description
The origin of box is considered to be in the center of each size value.
Definition at line 31 of file BoxROIExtractor.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d algorithm filtering BoxROIExtractor cpp brics_3d::BoxROIExtractor::BoxROIExtractor ()
Definition at line 26 of file BoxROIExtractor.cpp.
brics_3d::BoxROIExtractor::BoxROIExtractor (Coordinate sizeX, Coordinate sizeY, Coordinate sizeZ)
Definition at line 32 of file BoxROIExtractor.cpp.
brics_3d::BoxROIExtractor::~BoxROIExtractor () [virtual]
Definition at line 38 of file BoxROIExtractor.cpp.
Member Function Documentation
void brics_3d::BoxROIExtractor::filter (PointCloud3D * originalPointCloud, PointCloud3D * resultPointCloud) [virtual]
Filter a point cloud.
Parameters:
[in] originalPointCloud The input point cloud that will be filtered. This data will not be modified.
[out] resultPointCloud The filtered point cloud with.
Implements brics_3d::IFiltering.
Definition at line 42 of file BoxROIExtractor.cpp.
References brics_3d::PointCloud3D::addPointPtr(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), brics_3d::Point3D::getZ(), sizeX, sizeY, and sizeZ.
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr brics_3d::BoxROIExtractor::getBoxOrigin () const [inline]
Definition at line 58 of file BoxROIExtractor.h.
References boxOrigin.
Coordinate brics_3d::BoxROIExtractor::getSizeX () const [inline]
Definition at line 43 of file BoxROIExtractor.h.
References sizeX.
Coordinate brics_3d::BoxROIExtractor::getSizeY () const [inline]
Definition at line 48 of file BoxROIExtractor.h.
References sizeY.
Coordinate brics_3d::BoxROIExtractor::getSizeZ () const [inline]
Definition at line 53 of file BoxROIExtractor.h.
References sizeZ.
void brics_3d::BoxROIExtractor::setBoxOrigin (IHomogeneousMatrix44::IHomogeneousMatrix44Ptr boxOrigin) [inline]
Definition at line 78 of file BoxROIExtractor.h.
References boxOrigin.
void brics_3d::BoxROIExtractor::setSizeX (Coordinate sizeX) [inline]
Definition at line 63 of file BoxROIExtractor.h.
References sizeX.
void brics_3d::BoxROIExtractor::setSizeY (Coordinate sizeY) [inline]
Definition at line 68 of file BoxROIExtractor.h.
References sizeY.
void brics_3d::BoxROIExtractor::setSizeZ (Coordinate sizeZ) [inline]
Definition at line 73 of file BoxROIExtractor.h.
References sizeZ.
Member Data Documentation
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr brics_3d::BoxROIExtractor::boxOrigin [private]
Definition at line 89 of file BoxROIExtractor.h.
Referenced by getBoxOrigin(), and setBoxOrigin().
Coordinate brics_3d::BoxROIExtractor::sizeX [private]
Definition at line 85 of file BoxROIExtractor.h.
Referenced by filter(), getSizeX(), and setSizeX().
Coordinate brics_3d::BoxROIExtractor::sizeY [private]
Definition at line 86 of file BoxROIExtractor.h.
Referenced by filter(), getSizeY(), and setSizeY().
Coordinate brics_3d::BoxROIExtractor::sizeZ [private]
Definition at line 87 of file BoxROIExtractor.h.
Referenced by filter(), getSizeZ(), and setSizeZ().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/filtering/BoxROIExtractor.h
src/brics_3d/algorithm/filtering/BoxROIExtractor.cpp