BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::INodeVisitor Class Reference
brics_3d::rsg::INodeVisitor Class Reference
Scenegraph
Abstract interface for visitors of the scene graph (Visitor pattern).
#include <INodeVisitor.h>
Public Types
enum TraverseDirection { downwards, upwards }
Public Member Functions
INodeVisitor (TraverseDirection direction=downwards)
virtual ~INodeVisitor ()
virtual void visit (Node *node)
virtual void visit (Group *node)
virtual void visit (Transform *node)
virtual void visit (GeometricNode *node)
TraverseDirection getDirection () const
void setDirection (TraverseDirection direction)
Protected Attributes
TraverseDirection direction
Detailed Description
Abstract interface for visitors of the scene graph (Visitor pattern).
Definition at line 36 of file INodeVisitor.h.
Member Enumeration Documentation
enum brics_3d::rsg::INodeVisitor::TraverseDirection
Enumerator:
downwards
upwards
Definition at line 39 of file INodeVisitor.h.
Constructor & Destructor Documentation
brics_3d::rsg::INodeVisitor::INodeVisitor (TraverseDirection direction = downwards) [inline]
Definition at line 44 of file INodeVisitor.h.
References direction.
virtual brics_3d::rsg::INodeVisitor::~INodeVisitor () [inline, virtual]
Definition at line 45 of file INodeVisitor.h.
Member Function Documentation
TraverseDirection brics_3d::rsg::INodeVisitor::getDirection () const [inline]
Definition at line 52 of file INodeVisitor.h.
References direction.
Referenced by brics_3d::rsg::Transform::accept(), brics_3d::rsg::Node::accept(), brics_3d::rsg::Group::accept(), and brics_3d::rsg::GeometricNode::accept().
void brics_3d::rsg::INodeVisitor::setDirection (TraverseDirection direction) [inline]
Definition at line 57 of file INodeVisitor.h.
References direction.
virtual void brics_3d::rsg::INodeVisitor::visit (Group * node) [inline, virtual]
Reimplemented in brics_3d::rsg::AttributeFinder, brics_3d::rsg::DotGraphGenerator, brics_3d::rsg::OutdatedDataDeleter, brics_3d::rsg::PathCollector, brics_3d::rsg::PointCloudAccumulator, brics_3d::rsg::SceneGraphToUpdatesTraverser, and brics_3d::rsg::SubGraphChecker.
Definition at line 48 of file INodeVisitor.h.
virtual void brics_3d::rsg::INodeVisitor::visit (GeometricNode * node) [inline, virtual]
Reimplemented in brics_3d::rsg::AttributeFinder, brics_3d::rsg::DotGraphGenerator, brics_3d::rsg::OutdatedDataDeleter, brics_3d::rsg::PathCollector, brics_3d::rsg::PointCloudAccumulator, brics_3d::rsg::SceneGraphToUpdatesTraverser, and brics_3d::rsg::SubGraphChecker.
Definition at line 50 of file INodeVisitor.h.
virtual void brics_3d::rsg::INodeVisitor::visit (Transform * node) [inline, virtual]
Reimplemented in brics_3d::rsg::AttributeFinder, brics_3d::rsg::DotGraphGenerator, brics_3d::rsg::OutdatedDataDeleter, brics_3d::rsg::PathCollector, brics_3d::rsg::PointCloudAccumulator, brics_3d::rsg::SceneGraphToUpdatesTraverser, and brics_3d::rsg::SubGraphChecker.
Definition at line 49 of file INodeVisitor.h.
virtual void brics_3d::rsg::INodeVisitor::visit (Node * node) [inline, virtual]
Reimplemented in brics_3d::rsg::AttributeFinder, brics_3d::rsg::DotGraphGenerator, brics_3d::rsg::OutdatedDataDeleter, brics_3d::rsg::PathCollector, brics_3d::rsg::PointCloudAccumulator, brics_3d::rsg::SceneGraphToUpdatesTraverser, and brics_3d::rsg::SubGraphChecker.
Definition at line 47 of file INodeVisitor.h.
Referenced by brics_3d::rsg::Transform::accept(), brics_3d::rsg::Node::accept(), brics_3d::rsg::Group::accept(), and brics_3d::rsg::GeometricNode::accept().
Member Data Documentation
TraverseDirection brics_3d::rsg::INodeVisitor::direction [protected]
Definition at line 63 of file INodeVisitor.h.
Referenced by getDirection(), INodeVisitor(), and setDirection().
The documentation for this class was generated from the following file:
src/brics_3d/worldModel/sceneGraph/INodeVisitor.h