BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelCylinder Class Reference
brics_3d::ObjectModelCylinder Class Reference
Segmentation
#include <ObjectModelCylinder.h>
Public Member Functions
ObjectModelCylinder ()
virtual ~ObjectModelCylinder ()
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXd &model_coefficients)
void optimizeModelCoefficients (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, Eigen::VectorXd &optimized_coefficients)
void getDistancesToModel (const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Compute all distances from the cloud data to a given model.
void selectWithinDistance (const Eigen::VectorXd &model_coefficients, double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
void getInlierDistance (std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Select all the points which respect the given model coefficients as inliers.
void projectPoints (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, PointCloud3D *projectedPointCloud)
bool doSamplesVerifyModel (const std::set< int > &indices, const Eigen::VectorXd &model_coefficients, double threshold)
Verify whether a subset of indices verifies a given set of model coefficients.
void computeRandomModel (int &iterations, Eigen::VectorXd &model_coefficients, bool &isDegenerate, bool &modelFound)
Compute the model coefficients by generating some random samples.
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Protected Member Functions
double pointToLineDistance (const Eigen::Vector4d &pt, const Eigen::VectorXd &model_coefficients)
Get the distance from a point to a line (represented by a point and a direction)
double pointToLineDistance (const Eigen::Vector4d &pt, const Eigen::Vector4d &line_pt, const Eigen::Vector4d &line_dir)
Get the distance from a point to a line (represented by a point and a direction)
void projectPointToLine (const Eigen::Vector4d &pt, const Eigen::Vector4d &line_pt, const Eigen::Vector4d &line_dir, Eigen::Vector4d &pt_proj)
Project a point onto a line given by a point and a direction vector.
void projectPointToCylinder (const Eigen::Vector4d &pt, const Eigen::VectorXd &model_coefficients, Eigen::Vector4d &pt_proj)
Project a point onto a cylinder given by its model coefficients (point_on_axis, axis_direction, cylinder_radius_R)
Detailed Description
Note:
The implementation is reusing the object model implementation in ROS:PCl
Definition at line 31 of file ObjectModelCylinder.h.
Constructor & Destructor Documentation
brics_3d::ObjectModelCylinder::ObjectModelCylinder () [inline]
Definition at line 34 of file ObjectModelCylinder.h.
virtual brics_3d::ObjectModelCylinder::~ObjectModelCylinder () [inline, virtual]
Definition at line 35 of file ObjectModelCylinder.h.
Member Function Documentation
bool brics_3d::ObjectModelCylinder::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXd & model_coefficients)
Definition at line 77 of file ObjectModelCylinder.cpp.
References brics_3d::NormalSet3D::getNormals(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::NormalSet3D::getSize(), brics_3d::IObjectModel::inputPointCloud, brics_3d::IObjectModelUsingNormals::normals, pointToLineDistance(), brics_3d::IObjectModel::radiusMax, and brics_3d::IObjectModel::radiusMin.
Referenced by computeRandomModel().
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelCylinder cpp void brics_3d::ObjectModelCylinder::computeRandomModel (int & iterations, Eigen::VectorXd & model_coefficients, bool & isDegenerate, bool & modelFound) [virtual]
Compute the model coefficients by generating some random samples.
Parameters:
model_coefficients,: the computed model coefficients
isDegenerate,: Whether degenerate samples are found from the input pointcloud or not
modelFound,: Whether a valid model is found from the sample or not
Implements brics_3d::IObjectModel.
Definition at line 25 of file ObjectModelCylinder.cpp.
References computeModelCoefficients(), and getSamples().
bool brics_3d::ObjectModelCylinder::doSamplesVerifyModel (const std::set< int > & indices, const Eigen::VectorXd & model_coefficients, double threshold) [virtual]
Verify whether a subset of indices verifies a given set of model coefficients.
Pure virtual.
Parameters:
indices the data indices that need to be tested against the model
model_coefficients the set of model coefficients
threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements brics_3d::IObjectModel.
Definition at line 282 of file ObjectModelCylinder.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::IObjectModel::inputPointCloud, and pointToLineDistance().
void brics_3d::ObjectModelCylinder::getDistancesToModel (const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Compute all distances from the cloud data to a given model.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
distances the resultant estimated distances
Implements brics_3d::IObjectModel.
Definition at line 149 of file ObjectModelCylinder.cpp.
void brics_3d::ObjectModelCylinder::getInlierDistance (std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
distances of inliers from the model
Implements brics_3d::IObjectModel.
Definition at line 239 of file ObjectModelCylinder.cpp.
References brics_3d::IObjectModel::getAngle3D(), brics_3d::NormalSet3D::getNormals(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::IObjectModel::inputPointCloud, brics_3d::IObjectModelUsingNormals::normalDistanceWeight, brics_3d::IObjectModelUsingNormals::normals, and pointToLineDistance().
int brics_3d::ObjectModelCylinder::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Implements brics_3d::IObjectModel.
Definition at line 52 of file ObjectModelCylinder.h.
void brics_3d::ObjectModelCylinder::getSamples (int & iterations, std::vector< int > & samples)
Definition at line 52 of file ObjectModelCylinder.cpp.
References brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
Referenced by computeRandomModel().
void brics_3d::ObjectModelCylinder::optimizeModelCoefficients (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, Eigen::VectorXd & optimized_coefficients)
double brics_3d::ObjectModelCylinder::pointToLineDistance (const Eigen::Vector4d & pt, const Eigen::Vector4d & line_pt, const Eigen::Vector4d & line_dir) [protected]
Get the distance from a point to a line (represented by a point and a direction)
Parameters:
pt a point
line_pt a point on the line (make sure that line_pt[3] = 0 as there are no internal checks!)
line_dir the line direction
Definition at line 323 of file ObjectModelCylinder.cpp.
double brics_3d::ObjectModelCylinder::pointToLineDistance (const Eigen::Vector4d & pt, const Eigen::VectorXd & model_coefficients) [protected]
Get the distance from a point to a line (represented by a point and a direction)
Parameters:
pt a point
model_coefficients the line coefficients (a point on the line, line direction)
Definition at line 304 of file ObjectModelCylinder.cpp.
Referenced by computeModelCoefficients(), doSamplesVerifyModel(), getInlierDistance(), and selectWithinDistance().
void brics_3d::ObjectModelCylinder::projectPoints (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, PointCloud3D * projectedPointCloud)
void brics_3d::ObjectModelCylinder::projectPointToCylinder (const Eigen::Vector4d & pt, const Eigen::VectorXd & model_coefficients, Eigen::Vector4d & pt_proj) [inline, protected]
Project a point onto a cylinder given by its model coefficients (point_on_axis, axis_direction, cylinder_radius_R)
Parameters:
pt the input point to project
model_coefficients the coefficients of the cylinder (point_on_axis, axis_direction, cylinder_radius_R)
pt_proj the resultant projected point
Definition at line 93 of file ObjectModelCylinder.h.
void brics_3d::ObjectModelCylinder::projectPointToLine (const Eigen::Vector4d & pt, const Eigen::Vector4d & line_pt, const Eigen::Vector4d & line_dir, Eigen::Vector4d & pt_proj) [inline, protected]
Project a point onto a line given by a point and a direction vector.
Parameters:
pt the input point to project
line_pt the point on the line (make sure that line_pt[3] = 0 as there are no internal checks!)
line_dir the direction of the line (make sure that line_dir[3] = 0 as there are no internal checks!)
pt_proj the resultant projected point
Definition at line 78 of file ObjectModelCylinder.h.
void brics_3d::ObjectModelCylinder::selectWithinDistance (const Eigen::VectorXd & model_coefficients, double threshold, std::vector< int > & inliers) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
inliers the resultant model inliers
Implements brics_3d::IObjectModel.
Definition at line 192 of file ObjectModelCylinder.cpp.
References brics_3d::IObjectModel::getAngle3D(), brics_3d::NormalSet3D::getNormals(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::IObjectModel::inputPointCloud, brics_3d::IObjectModelUsingNormals::normalDistanceWeight, brics_3d::IObjectModelUsingNormals::normals, and pointToLineDistance().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelCylinder.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelCylinder.cpp