BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::RegionBasedSACSegmentationUsingNormals Class Reference
brics_3d::RegionBasedSACSegmentationUsingNormals Class Reference
: Adapter class for initialization of sample consensus based segmentation method which requires point normals
#include <RegionBasedSACSegmentationUsingNormals.h>
Public Member Functions
RegionBasedSACSegmentationUsingNormals ()
~RegionBasedSACSegmentationUsingNormals ()
void setInputNormals (NormalSet3D *normalSet)
Set the pointer to the normal-set for the corresponding input point cloud.
NormalSet3D * getInputNormals ()
Get a pointer to brics_3d::NOrmalSet3D for input point cloud being segmented.
void setNormalDistanceWeight (double distanceWeight)
Set the relative weight variable indicating the angular distance between point normals and the plane normal.
double getNormalDistanceWeight ()
Get the relative weight variable indicating the angular distance between point normals and the plane normal.
void setAxis (const Eigen::Vector3d &axis)
Set the axis along which we need to search for a model perpendicular to.
Eigen::Vector3d getAxis ()
Get the axis along which we need to search for a model perpendicular to.
void setEpsAngle (double epAngle)
Set the angle epsilon (delta) threshold.
double getEpsAngle ()
Get the angle threshold between the given axis and the model-normal.
void setRadiusLimits (const double &minRadius, const double &maxRadius)
Set the minimum and maximum radius allowable for models including a radius value.
bool initSACModel (const int model_type)
Initialize the Sample Consensus model and set its parameters.
void initSACMethod (const int methodType)
Initialize the segmentation method and set the required parameters.
int segment ()
Base method for finding of a model in the input point cloud.
Static Public Attributes
static const int OBJMODEL_CYLINDER = 4
static const int OBJMODEL_NORMAL_PLANE = 7
Private Attributes
IObjectModelUsingNormals * objectModelUsingNormals
The point normal based object model to be searched for in its parametric form.
double radiusMin
Minimum and maximum radius allowable for the models.
double radiusMax
double normalDistanceWeight
The relative weight (between 0 and 1) to corresponding to angular distance between point normals and the plane normal.
NormalSet3D * normalSet
A pointer to the vector of normals.
Eigen::Vector3d axis
Axis along which we need to search for a model perpendicular to.
double epsAngle
The maximum angle between the model normal and the given axis.
Detailed Description
: Adapter class for initialization of sample consensus based segmentation method which requires point normals
Definition at line 38 of file RegionBasedSACSegmentationUsingNormals.h.
Constructor & Destructor Documentation
brics_3d::RegionBasedSACSegmentationUsingNormals::RegionBasedSACSegmentationUsingNormals () [inline]
Definition at line 67 of file RegionBasedSACSegmentationUsingNormals.h.
brics_3d::RegionBasedSACSegmentationUsingNormals::~RegionBasedSACSegmentationUsingNormals () [inline]
Definition at line 77 of file RegionBasedSACSegmentationUsingNormals.h.
Member Function Documentation
Eigen::Vector3d brics_3d::RegionBasedSACSegmentationUsingNormals::getAxis () [inline]
Get the axis along which we need to search for a model perpendicular to.
Definition at line 132 of file RegionBasedSACSegmentationUsingNormals.h.
double brics_3d::RegionBasedSACSegmentationUsingNormals::getEpsAngle () [inline]
Get the angle threshold between the given axis and the model-normal.
Definition at line 150 of file RegionBasedSACSegmentationUsingNormals.h.
References epsAngle.
NormalSet3D* brics_3d::RegionBasedSACSegmentationUsingNormals::getInputNormals () [inline]
Get a pointer to brics_3d::NOrmalSet3D for input point cloud being segmented.
Returns:
Pointer to brics_3d::NormalSet3D
Definition at line 94 of file RegionBasedSACSegmentationUsingNormals.h.
References normalSet.
double brics_3d::RegionBasedSACSegmentationUsingNormals::getNormalDistanceWeight () [inline]
Get the relative weight variable indicating the angular distance between point normals and the plane normal.
Definition at line 114 of file RegionBasedSACSegmentationUsingNormals.h.
References normalDistanceWeight.
void brics_3d::RegionBasedSACSegmentationUsingNormals::initSACMethod (const int methodType) [inline]
Initialize the segmentation method and set the required parameters.
Parameters:
methodType the type of Sample Consensus method to be used
Reimplemented from brics_3d::RegionBasedSACSegmentation.
Definition at line 251 of file RegionBasedSACSegmentationUsingNormals.h.
References brics_3d::ISegmentation::inputPointCloud, objectModelUsingNormals, brics_3d::RegionBasedSACSegmentation::SAC_ALMeDS, brics_3d::RegionBasedSACSegmentation::SAC_LMEDS, brics_3d::RegionBasedSACSegmentation::SAC_MLESAC, brics_3d::RegionBasedSACSegmentation::SAC_MSAC, brics_3d::RegionBasedSACSegmentation::SAC_RANSAC, brics_3d::RegionBasedSACSegmentation::sacMethod, brics_3d::ISACMethods::setDistanceThreshold(), brics_3d::ISACMethods::setObjectModel(), brics_3d::ISACMethods::setPointCloud(), and brics_3d::RegionBasedSACSegmentation::threshold.
Referenced by segment().
bool brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel (const int model_type) [inline]
Initialize the Sample Consensus model and set its parameters.
Parameters:
model_type the type of SAC model that is to be used
Reimplemented from brics_3d::RegionBasedSACSegmentation.
Definition at line 174 of file RegionBasedSACSegmentationUsingNormals.h.
References axis, epsAngle, brics_3d::IObjectModelUsingNormals::getAxis(), brics_3d::IObjectModelUsingNormals::getEpsAngle(), brics_3d::IObjectModelUsingNormals::getNormalDistanceWeight(), brics_3d::IObjectModel::getRadiusLimits(), brics_3d::NormalSet3D::getSize(), brics_3d::PointCloud3D::getSize(), brics_3d::ISegmentation::inputPointCloud, normalDistanceWeight, normalSet, objectModelUsingNormals, OBJMODEL_CYLINDER, OBJMODEL_NORMAL_PLANE, radiusMax, radiusMin, brics_3d::IObjectModelUsingNormals::setAxis(), brics_3d::IObjectModelUsingNormals::setEpsAngle(), brics_3d::IObjectModel::setInputCloud(), brics_3d::IObjectModelUsingNormals::setInputNormals(), brics_3d::IObjectModelUsingNormals::setNormalDistanceWeight(), and brics_3d::IObjectModel::setRadiusLimits().
Referenced by segment().
int brics_3d::RegionBasedSACSegmentationUsingNormals::segment () [inline, virtual]
Base method for finding of a model in the input point cloud.
Parameters:
inliers the point indices lying inside the estimated model
model_coefficients the resultant model coefficients
Reimplemented from brics_3d::RegionBasedSACSegmentation.
Definition at line 320 of file RegionBasedSACSegmentationUsingNormals.h.
References brics_3d::ISACMethods::computeModel(), brics_3d::ISACMethods::getInliers(), brics_3d::ISACMethods::getModelCoefficients(), initSACMethod(), initSACModel(), brics_3d::RegionBasedSACSegmentation::inliers, brics_3d::ISegmentation::inputPointCloud, brics_3d::RegionBasedSACSegmentation::modelCoefficients, brics_3d::RegionBasedSACSegmentation::modelType, brics_3d::RegionBasedSACSegmentation::sacMethod, and brics_3d::RegionBasedSACSegmentation::SACMethodType.
void brics_3d::RegionBasedSACSegmentationUsingNormals::setAxis (const Eigen::Vector3d & axis) [inline]
Set the axis along which we need to search for a model perpendicular to.
Parameters:
axis the axis perpendicular to which the model parameters will be searched for
Definition at line 124 of file RegionBasedSACSegmentationUsingNormals.h.
References axis.
void brics_3d::RegionBasedSACSegmentationUsingNormals::setEpsAngle (double epAngle) [inline]
Set the angle epsilon (delta) threshold.
Parameters:
epAngle the maximum allowed difference between the model normal and the given axis.
Definition at line 142 of file RegionBasedSACSegmentationUsingNormals.h.
References epsAngle.
void brics_3d::RegionBasedSACSegmentationUsingNormals::setInputNormals (NormalSet3D * normalSet) [inline]
Set the pointer to the normal-set for the corresponding input point cloud.
Parameters:
normalSet Pointer to brics_3d::NormalSet3D
Definition at line 84 of file RegionBasedSACSegmentationUsingNormals.h.
References normalSet.
void brics_3d::RegionBasedSACSegmentationUsingNormals::setNormalDistanceWeight (double distanceWeight) [inline]
Set the relative weight variable indicating the angular distance between point normals and the plane normal.
Parameters:
distanceWeight the distance/angular weight between 0 and 1
Definition at line 105 of file RegionBasedSACSegmentationUsingNormals.h.
References normalDistanceWeight.
void brics_3d::RegionBasedSACSegmentationUsingNormals::setRadiusLimits (const double & minRadius, const double & maxRadius) [inline]
Set the minimum and maximum radius allowable for models including a radius value.
Parameters:
minRadius the minimum radius model
maxRadius the maximum radius model
Definition at line 162 of file RegionBasedSACSegmentationUsingNormals.h.
References radiusMax, and radiusMin.
Member Data Documentation
Eigen::Vector3d brics_3d::RegionBasedSACSegmentationUsingNormals::axis [private]
Axis along which we need to search for a model perpendicular to.
Definition at line 57 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACModel(), and setAxis().
double brics_3d::RegionBasedSACSegmentationUsingNormals::epsAngle [private]
The maximum angle between the model normal and the given axis.
Definition at line 60 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by getEpsAngle(), initSACModel(), and setEpsAngle().
double brics_3d::RegionBasedSACSegmentationUsingNormals::normalDistanceWeight [private]
The relative weight (between 0 and 1) to corresponding to angular distance between point normals and the plane normal.
0 corresponds to 0 rad and 1 corresponds to pi/2 rad
Definition at line 51 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by getNormalDistanceWeight(), initSACModel(), and setNormalDistanceWeight().
NormalSet3D* brics_3d::RegionBasedSACSegmentationUsingNormals::normalSet [private]
A pointer to the vector of normals.
Definition at line 54 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by getInputNormals(), initSACModel(), and setInputNormals().
IObjectModelUsingNormals* brics_3d::RegionBasedSACSegmentationUsingNormals::objectModelUsingNormals [private]
The point normal based object model to be searched for in its parametric form.
Definition at line 43 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACMethod(), and initSACModel().
const int brics_3d::RegionBasedSACSegmentationUsingNormals::OBJMODEL_CYLINDER = 4 [static]
Definition at line 64 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACModel().
const int brics_3d::RegionBasedSACSegmentationUsingNormals::OBJMODEL_NORMAL_PLANE = 7 [static]
Definition at line 65 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACModel().
double brics_3d::RegionBasedSACSegmentationUsingNormals::radiusMax [private]
Definition at line 46 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACModel(), and setRadiusLimits().
double brics_3d::RegionBasedSACSegmentationUsingNormals::radiusMin [private]
Minimum and maximum radius allowable for the models.
Definition at line 46 of file RegionBasedSACSegmentationUsingNormals.h.
Referenced by initSACModel(), and setRadiusLimits().
The documentation for this class was generated from the following file:
src/brics_3d/algorithm/segmentation/RegionBasedSACSegmentationUsingNormals.h