BRICS_RN (Robust Navigation Library): Stopwatch Class Reference
Stopwatch Class Reference
Implementation of a stopwatch for profiling of the algorithms.
#include <Stopwatch.h>
Public Member Functions
Stopwatch ()
Default constructor.
Stopwatch (const Stopwatch &orig)
Copy constructor.
virtual ~Stopwatch ()
Destructor.
void start ()
Start or restart a stop watch.
void stop ()
Stop a stop watch.
void pause ()
Pause a stopwatch without resetting.
double getStartTime () const
Return the start time in milliseconds.
double getStopTime () const
Return the stop time in milliseconds.
double getElapsedTime () const
return elapsed time in milliseconds
Private Member Functions
double convertToMs (const timespec &time) const
Private Attributes
timespec startTime
timespec stopTime
double elapsedTime
bool isPause
Detailed Description
Implementation of a stopwatch for profiling of the algorithms.
This class implements a simple, but high-resolution stopwatch. Note that the implementation requires proper support from the running kernel / hardware and as such may not be available on all supported platforms. Notably, it is not available under MacOSX.
The resolution of the stopwatch is platform depended. It returns time as a floating-point number measured in milliseconds.
Definition at line 58 of file Stopwatch.h.
Constructor & Destructor Documentation
Stopwatch::Stopwatch ()
Default constructor.
Definition at line 42 of file Stopwatch.cpp.
References elapsedTime, and isPause.
Stopwatch::Stopwatch (const Stopwatch & orig)
Copy constructor.
Definition at line 47 of file Stopwatch.cpp.
References elapsedTime, isPause, startTime, and stopTime.
Stopwatch::~Stopwatch () virtual
Destructor.
Definition at line 54 of file Stopwatch.cpp.
Member Function Documentation
double Stopwatch::convertToMs (const timespec & time) const private
Definition at line 78 of file Stopwatch.cpp.
Referenced by getElapsedTime(), getStartTime(), and getStopTime().
double Stopwatch::getElapsedTime () const
return elapsed time in milliseconds
The returned time is only valid, while the clock is stopped and not paused.
If the clock is paused by calling pause(), then a wrong value will be returned. If the clock is stopped, after it has been paused, then the returned value will cover the whole time span from the initial start up to the final stop. The time step at with the clock was paused is lost. If the clock is running, i.e. neither paused nor stopped, then a random value will be returned.
Definition at line 90 of file Stopwatch.cpp.
References convertToMs(), elapsedTime, startTime, and stopTime.
Referenced by ChaikinCurveApproximation::approximate(), DouglasPeuckerApproximation::approximate(), CollisionCheckingRos::collisionCheck(), PathPlannerRos::computePath(), LinearInterpolation::interpolate(), and pause().
double Stopwatch::getStartTime () const
Return the start time in milliseconds.
The start time is measured against an unspecified, implementation-depending epoch.
Definition at line 82 of file Stopwatch.cpp.
References convertToMs(), and startTime.
double Stopwatch::getStopTime () const
Return the stop time in milliseconds.
The stop time is measured against an unspecified, implementation-depending epoch.
Definition at line 86 of file Stopwatch.cpp.
References convertToMs(), and stopTime.
void Stopwatch::pause ()
Pause a stopwatch without resetting.
Definition at line 70 of file Stopwatch.cpp.
References elapsedTime, getElapsedTime(), isPause, and stopTime.
void Stopwatch::start ()
Start or restart a stop watch.
If the stop watch had been paused before, then it is resumed. Otherwise it is reset and then started.
Definition at line 57 of file Stopwatch.cpp.
References elapsedTime, isPause, and startTime.
Referenced by ChaikinCurveApproximation::approximate(), DouglasPeuckerApproximation::approximate(), CollisionCheckingRos::collisionCheck(), PathPlannerRos::computePath(), and LinearInterpolation::interpolate().
void Stopwatch::stop ()
Stop a stop watch.
Definition at line 65 of file Stopwatch.cpp.
References isPause, and stopTime.
Referenced by ChaikinCurveApproximation::approximate(), DouglasPeuckerApproximation::approximate(), CollisionCheckingRos::collisionCheck(), PathPlannerRos::computePath(), and LinearInterpolation::interpolate().
Member Data Documentation
double Stopwatch::elapsedTime private
Definition at line 126 of file Stopwatch.h.
Referenced by getElapsedTime(), pause(), start(), and Stopwatch().
bool Stopwatch::isPause private
Definition at line 127 of file Stopwatch.h.
Referenced by pause(), start(), stop(), and Stopwatch().
timespec Stopwatch::startTime private
Definition at line 124 of file Stopwatch.h.
Referenced by getElapsedTime(), getStartTime(), start(), and Stopwatch().
timespec Stopwatch::stopTime private
Definition at line 125 of file Stopwatch.h.
Referenced by getElapsedTime(), getStopTime(), pause(), stop(), and Stopwatch().
The documentation for this class was generated from the following files:
navigation_trajectory_common/include/navigation_trajectory_common/Stopwatch.h
navigation_trajectory_common/src/Stopwatch.cpp