BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ParameterSet Class Reference
brics_3d::ParameterSet Class Reference
A ParameterSet holds a number of parameters, representing (name/value) pairs.
#include <ParameterSet.h>
Public Member Functions
ParameterSet ()
Default constructor.
ParameterSet (std::string s)
Constructor that tries to parse string.
ParameterSet (std::vector< std::string > sParams)
Constructor that tries to pass vector of strings.
~ParameterSet ()
Destructor.
bool hasParam (std::string name) const
Returns true if a parameter with given name exists.
bool hasDouble (std::string name, double &value) const
Returns true if a parameter with given name exists, that can be casted to a double value.
bool hasInt (std::string name, int &value) const
Returns true if a parameter with given name exists, that can be casted to an int value.
bool hasUnsignedInt (std::string name, unsigned int &value) const
Returns true if a parameter with given name exists, that can be casted to an unsigned int value.
void addData (std::string name, ParameterData *data)
bool hasData (std::string)
ParameterData * getData (std::string name)
std::string pack ()
Packs this ParameterSet into one string.
bool unpack (const std::string &param)
Unpacks the given string into a whole ParameterSet, with all unpacked parameters entered into this set.
Protected Attributes
std::map< std::string,
ParameterData * > dataEntries
Detailed Description
A ParameterSet holds a number of parameters, representing (name/value) pairs.
Definition at line 40 of file ParameterSet.h.
Constructor & Destructor Documentation
brics_3d::ParameterSet::ParameterSet ()
Default constructor.
Definition at line 92 of file ParameterSet.cpp.
brics_3d::ParameterSet::ParameterSet (std::string s)
Constructor that tries to parse string.
Definition at line 95 of file ParameterSet.cpp.
References brics_3d::skipBlank().
brics_3d::ParameterSet::ParameterSet (std::vector< std::string > sParams)
Constructor that tries to pass vector of strings.
Definition at line 108 of file ParameterSet.cpp.
References brics_3d::skipBlank().
brics_3d::ParameterSet::~ParameterSet ()
Destructor.
Definition at line 120 of file ParameterSet.cpp.
References dataEntries.
Member Function Documentation
void brics_3d::ParameterSet::addData (std::string name, ParameterData * data)
Definition at line 240 of file ParameterSet.cpp.
References dataEntries.
ParameterData * brics_3d::ParameterSet::getData (std::string name)
Definition at line 253 of file ParameterSet.cpp.
References dataEntries.
bool brics_3d::ParameterSet::hasData (std::string name)
Definition at line 249 of file ParameterSet.cpp.
References dataEntries.
bool brics_3d::ParameterSet::hasDouble (std::string name, double & value) const
Returns true if a parameter with given name exists, that can be casted to a double value.
The double value is returned in value.
Definition at line 130 of file ParameterSet.cpp.
References LOG.
bool brics_3d::ParameterSet::hasInt (std::string name, int & value) const
Returns true if a parameter with given name exists, that can be casted to an int value.
The int value is returned in value.
Definition at line 145 of file ParameterSet.cpp.
References LOG.
bool brics_3d::ParameterSet::hasParam (std::string name) const
Returns true if a parameter with given name exists.
Definition at line 126 of file ParameterSet.cpp.
Referenced by pack().
bool brics_3d::ParameterSet::hasUnsignedInt (std::string name, unsigned int & value) const
Returns true if a parameter with given name exists, that can be casted to an unsigned int value.
The unsigned int value is returned in value.
Definition at line 160 of file ParameterSet.cpp.
References LOG.
std::string brics_3d::ParameterSet::pack ()
Packs this ParameterSet into one string.
An XML notation is used to separate multiple parameters that are to be packed.
Definition at line 175 of file ParameterSet.cpp.
References hasParam().
bool brics_3d::ParameterSet::unpack (const std::string & param)
Unpacks the given string into a whole ParameterSet, with all unpacked parameters entered into this set.
The ParameterSet must possess an XML based form. Returns true if param could be succesfully unpacked.
Definition at line 186 of file ParameterSet.cpp.
Member Data Documentation
std::map<std::string, ParameterData*> brics_3d::ParameterSet::dataEntries [protected]
Definition at line 83 of file ParameterSet.h.
Referenced by addData(), getData(), hasData(), and ~ParameterSet().
The documentation for this class was generated from the following files:
src/brics_3d/core/ParameterSet.h
src/brics_3d/core/ParameterSet.cpp