BRICS_RN (Robust Navigation Library): PathPlannerRos Class Reference
PathPlannerRos Class Reference
Implementation of the interface class for path planning.
#include <PathPlannerRos.h>
Public Member Functions
PathPlannerRos (nav_core::BaseGlobalPlanner *planner)
Constructor.
PathPlannerRos (const PathPlannerRos &orig)
Copy constructor.
virtual ~PathPlannerRos ()
Destructor.
virtual bool computePath (const FrameWithId &start, const FrameWithId &goal, std::vector< FrameWithId > &path)
An interface for path planning.
Private Attributes
nav_core::BaseGlobalPlanner * planner
Pointer to ROS path planner instance.
Detailed Description
Implementation of the interface class for path planning.
Current implementation is an adapter to BaseGlobalPlanner interface in ROS.
Definition at line 63 of file PathPlannerRos.h.
Constructor & Destructor Documentation
PathPlannerRos::PathPlannerRos (nav_core::BaseGlobalPlanner * planner)
Constructor.
Parameters
planner - nav_core::BaseGlobalPlanner pointer to a desired ROS path planner.
Definition at line 52 of file PathPlannerRos.cpp.
PathPlannerRos::PathPlannerRos (const PathPlannerRos & orig)
Copy constructor.
Definition at line 55 of file PathPlannerRos.cpp.
PathPlannerRos::~PathPlannerRos () virtual
Destructor.
Definition at line 58 of file PathPlannerRos.cpp.
Member Function Documentation
bool PathPlannerRos::computePath (const FrameWithId & start, const FrameWithId & goal, std::vector< FrameWithId > & path) virtual
An interface for path planning.
Parameters
[in] start - FrameWithId start position for a planner.
[in] goal - FrameWithId goal position for a planner.
[out] path - std::vector <FrameWithId> computed path
Returns
true if planner has found a path, otherwise false.
Implements IPathPlanner.
Definition at line 61 of file PathPlannerRos.cpp.
References conversions::frameToPoseStampedRos(), Stopwatch::getElapsedTime(), LOG, pathRos, conversions::pathRosToPath(), planner, Stopwatch::start(), and Stopwatch::stop().
Member Data Documentation
nav_core::BaseGlobalPlanner* PathPlannerRos::planner private
Pointer to ROS path planner instance.
Definition at line 95 of file PathPlannerRos.h.
Referenced by computePath().
The documentation for this class was generated from the following files:
navigation_trajectory_planner/include/navigation_trajectory_planner/PathPlannerRos.h
navigation_trajectory_planner/src/PathPlannerRos.cpp