BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::Group Class Reference
brics_3d::rsg::Group Class Reference
Scenegraph
The group allows for the graph relations, as it extends a node to have further children nodes.
#include <Group.h>
Public Types
typedef boost::shared_ptr< Group > GroupPtr
typedef boost::shared_ptr
< Group const > GroupConstPtr
Public Member Functions
Group ()
virtual ~Group ()
virtual void addChild (NodePtr child)
virtual void insertChild (NodePtr child, unsigned int index)
void removeChild (NodePtr child)
unsigned int getChildIndex (NodePtr node)
unsigned int getChildIndex (Node *node)
virtual void removeChildren (unsigned int startIndex, unsigned int numberOfChildrenToRemove=1)
unsigned int getNumberOfChildren () const
NodePtr getChild (unsigned int index)
virtual void accept (INodeVisitor *visitor)
Private Attributes
vector< NodePtr > children
Detailed Description
The group allows for the graph relations, as it extends a node to have further children nodes.
Definition at line 35 of file Group.h.
Member Typedef Documentation
typedef boost::shared_ptr<Group const> brics_3d::rsg::Group::GroupConstPtr
Definition at line 40 of file Group.h.
typedef boost::shared_ptr<Group> brics_3d::rsg::Group::GroupPtr
Definition at line 39 of file Group.h.
Constructor & Destructor Documentation
brics_3d::rsg::Group::Group ()
Definition at line 28 of file Group.cpp.
References children.
brics_3d::rsg::Group::~Group () [virtual]
Definition at line 32 of file Group.cpp.
References getChild(), and getNumberOfChildren().
Member Function Documentation
void brics_3d::rsg::Group::accept (INodeVisitor * visitor) [virtual]
Reimplemented from brics_3d::rsg::Node.
Reimplemented in brics_3d::rsg::Transform.
Definition at line 114 of file Group.cpp.
References brics_3d::rsg::Node::accept(), brics_3d::rsg::INodeVisitor::downwards, getChild(), brics_3d::rsg::INodeVisitor::getDirection(), getNumberOfChildren(), brics_3d::rsg::Node::getNumberOfParents(), brics_3d::rsg::Node::getParent(), brics_3d::rsg::INodeVisitor::upwards, and brics_3d::rsg::INodeVisitor::visit().
void brics_3d::rsg::Group::addChild (NodePtr child) [virtual]
Definition at line 44 of file Group.cpp.
References children, and insertChild().
Group::NodePtr brics_3d::rsg::Group::getChild (unsigned int index)
Definition at line 106 of file Group.cpp.
References children.
Referenced by brics_3d::rsg::Transform::accept(), accept(), brics_3d::rsg::PointCloudAccumulator::doGetTransformFromReferenceToPointCloud(), removeChildren(), and ~Group().
unsigned int brics_3d::rsg::Group::getChildIndex (NodePtr node)
Definition at line 86 of file Group.cpp.
References children, and getNumberOfChildren().
Referenced by brics_3d::rsg::PointCloudAccumulator::doGetTransformFromReferenceToPointCloud(), and removeChild().
unsigned int brics_3d::rsg::Group::getChildIndex (Node * node)
Definition at line 96 of file Group.cpp.
References children, and getNumberOfChildren().
unsigned int brics_3d::rsg::Group::getNumberOfChildren () const
Definition at line 110 of file Group.cpp.
References children.
Referenced by brics_3d::rsg::Transform::accept(), accept(), getChildIndex(), removeChildren(), and ~Group().
void brics_3d::rsg::Group::insertChild (NodePtr child, unsigned int index) [virtual]
Definition at line 48 of file Group.cpp.
References children.
Referenced by addChild().
void brics_3d::rsg::Group::removeChild (NodePtr child)
Definition at line 63 of file Group.cpp.
References children, getChildIndex(), and removeChildren().
void brics_3d::rsg::Group::removeChildren (unsigned int startIndex, unsigned int numberOfChildrenToRemove = 1) [virtual]
Definition at line 70 of file Group.cpp.
References children, getChild(), getNumberOfChildren(), and LOG.
Referenced by removeChild().
Member Data Documentation
vector<NodePtr> brics_3d::rsg::Group::children [private]
Definition at line 59 of file Group.h.
Referenced by addChild(), getChild(), getChildIndex(), getNumberOfChildren(), Group(), insertChild(), removeChild(), and removeChildren().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/Group.h
src/brics_3d/worldModel/sceneGraph/Group.cpp