BRICS_RN_Robust_Navigation_Library(BRICS_RN): ChaikinCurveApproximation Class Reference
ChaikinCurveApproximation Class Reference
Implementation of path approximation algorithm.
#include <ChaikinCurveApproximation.h>
Public Member Functions
ChaikinCurveApproximation ()
ChaikinCurveApproximation (const ChaikinCurveApproximation &orig)
virtual ~ChaikinCurveApproximation ()
void approximate (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out)
Smooths input path by Chaiking algorithm.
void approximate (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out, unsigned int lod)
Smooths input path by Chaiking algorithm.
Private Member Functions
unsigned int chaikinCurve (const std::vector< FrameWithId > &pointList, std::vector< FrameWithId > &resultList)
Implementation of the Chaiking algorithms.
Detailed Description
Implementation of path approximation algorithm.
Chaikin algorithm generates a curve from a limited number of points.
Definition at line 50 of file ChaikinCurveApproximation.h.
Constructor & Destructor Documentation
ChaikinCurveApproximation::ChaikinCurveApproximation ()
Definition at line 51 of file ChaikinCurveApproximation.cpp.
ChaikinCurveApproximation::ChaikinCurveApproximation (const ChaikinCurveApproximation & orig)
Definition at line 55 of file ChaikinCurveApproximation.cpp.
ChaikinCurveApproximation::~ChaikinCurveApproximation () [virtual]
Definition at line 59 of file ChaikinCurveApproximation.cpp.
Member Function Documentation
void ChaikinCurveApproximation::approximate (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out) [virtual]
Smooths input path by Chaiking algorithm.
Parameters:
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting smoothed path.
Implements IPathApproximation.
Definition at line 86 of file ChaikinCurveApproximation.cpp.
void ChaikinCurveApproximation::approximate (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out, unsigned int lod)
Smooths input path by Chaiking algorithm.
Parameters:
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting smoothed path.
[out] lod - level of details.
Definition at line 62 of file ChaikinCurveApproximation.cpp.
References chaikinCurve(), Stopwatch::getElapsedTime(), LOG, Stopwatch::start(), and Stopwatch::stop().
unsigned int ChaikinCurveApproximation::chaikinCurve (const std::vector< FrameWithId > & pointList, std::vector< FrameWithId > & resultList) [private]
Implementation of the Chaiking algorithms.
Parameters:
[in] pointList - std::vector <FrameWithId> input path.
[out] resultList - std::vector <FrameWithId> resulting smoothed path.
Definition at line 91 of file ChaikinCurveApproximation.cpp.
Referenced by approximate().
The documentation for this class was generated from the following files:
navigation_trajectory_planner/include/navigation_trajectory_planner/ChaikinCurveApproximation.h
navigation_trajectory_planner/src/ChaikinCurveApproximation.cpp