BRICS_RN (Robust Navigation Library): TrajectoryWithId Class Reference
TrajectoryWithId Class Reference
TrajectoryWithId is an aggregation of KDL::Trajectory class with a std::string as frame id.
#include <TrajectoryWithId.h>
Public Member Functions
TrajectoryWithId ()
Default constructor.
TrajectoryWithId (const std::string &id)
Constructor.
TrajectoryWithId (const KDL::Trajectory &trajectory)
Constructor.
TrajectoryWithId (const KDL::Trajectory &trajectory, const std::string &id)
Constructor.
TrajectoryWithId (const TrajectoryWithId &orig)
Copy constructor.
const TrajectoryWithId & operator= (const TrajectoryWithId &orig)
Operation assignment.
virtual ~TrajectoryWithId ()
Destructor.
void setTrajectory (const KDL::Trajectory &trajectory)
Sets a trajectory.
KDL::Trajectory & getTrajectory ()
Get an underlying KDL trajectory as a reference.
const KDL::Trajectory & getTrajectory () const
Gets an underlying KDL trajectory as const reference or a copy.
Public Attributes
std::string id
String identifier of the trajectory.
KDL::Trajectory * trajectory
Aggregated KDL trajectory.
Detailed Description
TrajectoryWithId is an aggregation of KDL::Trajectory class with a std::string as frame id.
The embedded KDL::Trajectory will be always heap-allocated.
Definition at line 55 of file TrajectoryWithId.h.
Constructor & Destructor Documentation
TrajectoryWithId::TrajectoryWithId ()
Default constructor.
Definition at line 6 of file TrajectoryWithId.cpp.
References trajectory.
TrajectoryWithId::TrajectoryWithId (const std::string & id)
Constructor.
The embedded KDL::Trajectory is initialized by its default constructor.
Parameters
[in] id - string identifier of the trajectory.
Definition at line 11 of file TrajectoryWithId.cpp.
References id, and trajectory.
TrajectoryWithId::TrajectoryWithId (const KDL::Trajectory & trajectory)
Constructor.
The embedded id is set to the empty string.
Parameters
[in] trajectory - KDL trajectory.
Definition at line 16 of file TrajectoryWithId.cpp.
TrajectoryWithId::TrajectoryWithId (const KDL::Trajectory & trajectory, const std::string & id)
Constructor.
Parameters
[in] trajectory - KDL trajectory.
[in] id - string identifier of the trajectory.
Definition at line 20 of file TrajectoryWithId.cpp.
References id.
TrajectoryWithId::TrajectoryWithId (const TrajectoryWithId & orig)
Copy constructor.
Parameters
[in] orig - reference to the original object
Definition at line 33 of file TrajectoryWithId.cpp.
References getTrajectory(), id, and trajectory.
TrajectoryWithId::~TrajectoryWithId () virtual
Destructor.
Definition at line 38 of file TrajectoryWithId.cpp.
References trajectory.
Member Function Documentation
KDL::Trajectory & TrajectoryWithId::getTrajectory ()
Get an underlying KDL trajectory as a reference.
Modifications on the TrajectoryWithId, except assignment or setTrajectory(), will be reflected by the returned reference. Modifications of the returned trajectory will be visible in the TrajectoryWithId instance.
Assigning or setting a new trajectory invalidates all references obtained from KDL::Trajectory& getTrajectory().
Definition at line 48 of file TrajectoryWithId.cpp.
References trajectory.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDrivePositionController::setTargetTrajectory(), OmniDrivePositionController::targetReached(), and TrajectoryWithId().
const KDL::Trajectory & TrajectoryWithId::getTrajectory () const
Gets an underlying KDL trajectory as const reference or a copy.
Modifications on the TrajectoryWithId, except assignment or setTrajectory(), will be reflected by the returned reference.
Assigning or setting a new trajectory invalidates all references obtained from const KDL::Trajectory& getTrajectory() const.
Definition at line 52 of file TrajectoryWithId.cpp.
References trajectory.
const TrajectoryWithId & TrajectoryWithId::operator= (const TrajectoryWithId & orig)
Operation assignment.
Parameters
[in] orig - reference to the original object
Definition at line 25 of file TrajectoryWithId.cpp.
References id, and trajectory.
void TrajectoryWithId::setTrajectory (const KDL::Trajectory & trajectory)
Sets a trajectory.
The supplied KDL::Trajectory trajectory is copied and can be delete or modified without affecting the TrajectoryWithId instance. The id member is not modified.
Parameters
[in] trajectory - KDL::Trajectory
Definition at line 43 of file TrajectoryWithId.cpp.
References trajectory.
Referenced by OmniDrivePositionController::setTargetTrajectory().
Member Data Documentation
std::string TrajectoryWithId::id
String identifier of the trajectory.
Definition at line 60 of file TrajectoryWithId.h.
Referenced by operator=(), OmniDrivePositionController::setTargetTrajectory(), and TrajectoryWithId().
KDL::Trajectory* TrajectoryWithId::trajectory
Aggregated KDL trajectory.
Definition at line 150 of file TrajectoryWithId.h.
Referenced by getTrajectory(), operator=(), setTrajectory(), TrajectoryWithId(), and ~TrajectoryWithId().
The documentation for this class was generated from the following files:
navigation_trajectory_common/include/navigation_trajectory_common/TrajectoryWithId.h
navigation_trajectory_common/src/TrajectoryWithId.cpp