BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Point3DIntensity Class Reference
brics_3d::Point3DIntensity Class Reference
Decoration layer for a Point3D that carries intensety information.
#include <Point3DIntensity.h>
Public Member Functions
Point3DIntensity ()
Point3DIntensity (Point3D *point)
Point3DIntensity (Point3D *point, double intensity)
Point3DIntensity (Point3DIntensity *point)
Point3DIntensity (const Point3DIntensity &point)
Point3DIntensity & operator= (const Point3DIntensity &point)
virtual ~Point3DIntensity ()
void setIntensity (double intensity)
double getIntensity ()
virtual ColoredPoint3D * asColoredPoint3D ()
Convenience function to deduce if this point is decorated with color information.
virtual Point3D * clone () const
Creates a clone of the point and all potential decoration layers.
Protected Attributes
double intensity
Detailed Description
Decoration layer for a Point3D that carries intensety information.
Definition at line 30 of file Point3DIntensity.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d core Point3DIntensity cpp brics_3d::Point3DIntensity::Point3DIntensity ()
Definition at line 25 of file Point3DIntensity.cpp.
brics_3d::Point3DIntensity::Point3DIntensity (Point3D * point)
Definition at line 30 of file Point3DIntensity.cpp.
brics_3d::Point3DIntensity::Point3DIntensity (Point3D * point, double intensity)
Definition at line 35 of file Point3DIntensity.cpp.
brics_3d::Point3DIntensity::Point3DIntensity (Point3DIntensity * point)
Definition at line 40 of file Point3DIntensity.cpp.
References getIntensity().
brics_3d::Point3DIntensity::Point3DIntensity (const Point3DIntensity & point)
Definition at line 45 of file Point3DIntensity.cpp.
References intensity.
brics_3d::Point3DIntensity::~Point3DIntensity () [virtual]
Definition at line 55 of file Point3DIntensity.cpp.
Member Function Documentation
virtual ColoredPoint3D* brics_3d::Point3DIntensity::asColoredPoint3D () [inline, virtual]
Convenience function to deduce if this point is decorated with color information.
Returns:
Pointer to color object or null if there is no such decoration
Reimplemented from brics_3d::Point3DDecorator.
Definition at line 43 of file Point3DIntensity.h.
References asColoredPoint3D().
Referenced by asColoredPoint3D().
Point3D * brics_3d::Point3DIntensity::clone () const [virtual]
Creates a clone of the point and all potential decoration layers.
Returns:
Pointer to cloned object
Reimplemented from brics_3d::Point3D.
Definition at line 67 of file Point3DIntensity.cpp.
double brics_3d::Point3DIntensity::getIntensity ()
Definition at line 63 of file Point3DIntensity.cpp.
Referenced by Point3DIntensity().
Point3DIntensity & brics_3d::Point3DIntensity::operator= (const Point3DIntensity & point)
Definition at line 50 of file Point3DIntensity.cpp.
void brics_3d::Point3DIntensity::setIntensity (double intensity)
Definition at line 59 of file Point3DIntensity.cpp.
Member Data Documentation
double brics_3d::Point3DIntensity::intensity [protected]
Definition at line 50 of file Point3DIntensity.h.
Referenced by Point3DIntensity().
The documentation for this class was generated from the following files:
src/brics_3d/core/Point3DIntensity.h
src/brics_3d/core/Point3DIntensity.cpp