BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::GeometricNode Class Reference
brics_3d::rsg::GeometricNode Class Reference
Scenegraph
A leaf node in the robot scenegraph that carries any kind of 3D data.
#include <GeometricNode.h>
Public Types
typedef boost::shared_ptr
< GeometricNode > GeometricNodePtr
typedef boost::shared_ptr
< GeometricNode const > GeometricNodeConstPtr
Public Member Functions
GeometricNode ()
virtual ~GeometricNode ()
Shape::ShapePtr getShape () const
TimeStamp getTimeStamp () const
void setShape (Shape::ShapePtr shape)
void setTimeStamp (TimeStamp timeStamp)
virtual void accept (INodeVisitor *visitor)
Private Attributes
TimeStamp timeStamp
Shape::ShapePtr shape
Detailed Description
A leaf node in the robot scenegraph that carries any kind of 3D data.
The geometric node is a rather general container for any kind of 3D data. Possible data ranges from rather primitive shapes like boxes and cylinders to point clouds and meshes. 3D features like spin images etc. would be placed in to a geometric node too.
Definition at line 41 of file GeometricNode.h.
Member Typedef Documentation
typedef boost::shared_ptr<GeometricNode const> brics_3d::rsg::GeometricNode::GeometricNodeConstPtr
Definition at line 46 of file GeometricNode.h.
typedef boost::shared_ptr<GeometricNode> brics_3d::rsg::GeometricNode::GeometricNodePtr
Definition at line 45 of file GeometricNode.h.
Constructor & Destructor Documentation
brics_3d::rsg::GeometricNode::GeometricNode ()
Definition at line 26 of file GeometricNode.cpp.
brics_3d::rsg::GeometricNode::~GeometricNode () [virtual]
Definition at line 31 of file GeometricNode.cpp.
Member Function Documentation
void brics_3d::rsg::GeometricNode::accept (INodeVisitor * visitor) [virtual]
Reimplemented from brics_3d::rsg::Node.
Definition at line 37 of file GeometricNode.cpp.
References brics_3d::rsg::Node::accept(), brics_3d::rsg::INodeVisitor::getDirection(), brics_3d::rsg::Node::getNumberOfParents(), brics_3d::rsg::Node::getParent(), brics_3d::rsg::INodeVisitor::upwards, and brics_3d::rsg::INodeVisitor::visit().
Shape::ShapePtr brics_3d::rsg::GeometricNode::getShape () const [inline]
Definition at line 52 of file GeometricNode.h.
References shape.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit(), and brics_3d::rsg::PointCloudAccumulator::visit().
TimeStamp brics_3d::rsg::GeometricNode::getTimeStamp () const [inline]
Definition at line 57 of file GeometricNode.h.
References timeStamp.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
void brics_3d::rsg::GeometricNode::setShape (Shape::ShapePtr shape) [inline]
Definition at line 62 of file GeometricNode.h.
References shape.
void brics_3d::rsg::GeometricNode::setTimeStamp (TimeStamp timeStamp) [inline]
Definition at line 67 of file GeometricNode.h.
References timeStamp.
Member Data Documentation
Shape::ShapePtr brics_3d::rsg::GeometricNode::shape [private]
Definition at line 76 of file GeometricNode.h.
Referenced by getShape(), and setShape().
TimeStamp brics_3d::rsg::GeometricNode::timeStamp [private]
Definition at line 75 of file GeometricNode.h.
Referenced by getTimeStamp(), and setTimeStamp().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/GeometricNode.h
src/brics_3d/worldModel/sceneGraph/GeometricNode.cpp