BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::IObjectModelUsingNormals Class Reference
brics_3d::IObjectModelUsingNormals Class Reference
Segmentation
#include <IObjectModelUsingNormals.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW IObjectModelUsingNormals ()
virtual ~IObjectModelUsingNormals ()
void setEpsAngle (double epAngle)
Set the angle epsilon (delta) threshold.
double getEpsAngle ()
Get the angle threshold between the given axis and the model-normal.
void setInputNormals (NormalSet3D *normalSet)
Set the pointer to the normal-set for the corresponding input point cloud.
NormalSet3D * getInputNormals ()
Get a pointer to brics_3d::NOrmalSet3D for input point cloud being segmented.
void setNormalDistanceWeight (double distanceWeight)
Set the relative weight variable indicating the angular distance between point normals and the plane normal.
double getNormalDistanceWeight ()
Get the relative weight variable indicating the angular distance between point normals and the plane normal.
void setAxis (const Eigen::Vector3d &axis)
Set the axis along which we need to search for a model perpendicular to.
Eigen::Vector3d getAxis ()
Get the axis along which we need to search for a model perpendicular to.
Protected Attributes
double normalDistanceWeight
The relative weight (between 0 and 1) to corresponding to angular distance between point normals and the plane normal.
NormalSet3D * normals
A pointer to vector of normals.
Eigen::Vector3d axis
Axis along which we need to search for a model perpendicular to.
double epsAngle
The maximum angle between the model normal and the given axis.
Detailed Description
Definition at line 32 of file IObjectModelUsingNormals.h.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW brics_3d::IObjectModelUsingNormals::IObjectModelUsingNormals () [inline]
Definition at line 55 of file IObjectModelUsingNormals.h.
virtual brics_3d::IObjectModelUsingNormals::~IObjectModelUsingNormals () [inline, virtual]
Definition at line 56 of file IObjectModelUsingNormals.h.
Member Function Documentation
Eigen::Vector3d brics_3d::IObjectModelUsingNormals::getAxis () [inline]
Get the axis along which we need to search for a model perpendicular to.
Definition at line 129 of file IObjectModelUsingNormals.h.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
double brics_3d::IObjectModelUsingNormals::getEpsAngle () [inline]
Get the angle threshold between the given axis and the model-normal.
Definition at line 71 of file IObjectModelUsingNormals.h.
References epsAngle.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
NormalSet3D* brics_3d::IObjectModelUsingNormals::getInputNormals () [inline]
Get a pointer to brics_3d::NOrmalSet3D for input point cloud being segmented.
Returns:
Pointer to brics_3d::NormalSet3D
Definition at line 91 of file IObjectModelUsingNormals.h.
References normals.
double brics_3d::IObjectModelUsingNormals::getNormalDistanceWeight () [inline]
Get the relative weight variable indicating the angular distance between point normals and the plane normal.
Definition at line 111 of file IObjectModelUsingNormals.h.
References normalDistanceWeight.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
void brics_3d::IObjectModelUsingNormals::setAxis (const Eigen::Vector3d & axis) [inline]
Set the axis along which we need to search for a model perpendicular to.
Parameters:
axis the axis perpendicular to which the model parameters will be searched for
Reimplemented in brics_3d::ObjectModelNormalPlane.
Definition at line 121 of file IObjectModelUsingNormals.h.
References axis.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
void brics_3d::IObjectModelUsingNormals::setEpsAngle (double epAngle) [inline]
Set the angle epsilon (delta) threshold.
Parameters:
epAngle the maximum allowed difference between the model normal and the given axis.
Reimplemented in brics_3d::ObjectModelNormalPlane.
Definition at line 63 of file IObjectModelUsingNormals.h.
References epsAngle.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
void brics_3d::IObjectModelUsingNormals::setInputNormals (NormalSet3D * normalSet) [inline]
Set the pointer to the normal-set for the corresponding input point cloud.
Parameters:
normalSet Pointer to brics_3d::NormalSet3D
Definition at line 81 of file IObjectModelUsingNormals.h.
References normals.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
void brics_3d::IObjectModelUsingNormals::setNormalDistanceWeight (double distanceWeight) [inline]
Set the relative weight variable indicating the angular distance between point normals and the plane normal.
Parameters:
distanceWeight the distance/angular weight between 0 and 1
Definition at line 102 of file IObjectModelUsingNormals.h.
References normalDistanceWeight.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel().
Member Data Documentation
Eigen::Vector3d brics_3d::IObjectModelUsingNormals::axis [protected]
Axis along which we need to search for a model perpendicular to.
Reimplemented in brics_3d::ObjectModelNormalPlane.
Definition at line 46 of file IObjectModelUsingNormals.h.
Referenced by setAxis().
double brics_3d::IObjectModelUsingNormals::epsAngle [protected]
The maximum angle between the model normal and the given axis.
Reimplemented in brics_3d::ObjectModelNormalPlane.
Definition at line 49 of file IObjectModelUsingNormals.h.
Referenced by getEpsAngle(), and setEpsAngle().
double brics_3d::IObjectModelUsingNormals::normalDistanceWeight [protected]
The relative weight (between 0 and 1) to corresponding to angular distance between point normals and the plane normal.
0 corresponds to 0 rad and 1 corresponds to pi/2 rad
Definition at line 40 of file IObjectModelUsingNormals.h.
Referenced by brics_3d::ObjectModelNormalPlane::getDistancesToModel(), brics_3d::ObjectModelCylinder::getInlierDistance(), getNormalDistanceWeight(), brics_3d::ObjectModelCylinder::selectWithinDistance(), and setNormalDistanceWeight().
NormalSet3D* brics_3d::IObjectModelUsingNormals::normals [protected]
A pointer to vector of normals.
Definition at line 43 of file IObjectModelUsingNormals.h.
Referenced by brics_3d::ObjectModelCylinder::computeModelCoefficients(), brics_3d::ObjectModelNormalPlane::getDistancesToModel(), brics_3d::ObjectModelCylinder::getInlierDistance(), getInputNormals(), brics_3d::ObjectModelCylinder::selectWithinDistance(), and setInputNormals().
The documentation for this class was generated from the following file:
src/brics_3d/algorithm/segmentation/objectModels/IObjectModelUsingNormals.h