BRICS_RN_Robust_Navigation_Library(BRICS_RN): CollisionCheckingRos Class Reference
CollisionCheckingRos Class Reference
Implementation of the collision checking interface.
#include <CollisionCheckingRos.h>
Public Member Functions
CollisionCheckingRos (costmap_2d::Costmap2DROS *costmap)
Constructor.
CollisionCheckingRos (CollisionCheckingRos &orig)
Copy constructor.
virtual ~CollisionCheckingRos ()
Destructor.
bool check (const std::vector< FrameWithId > &path, const FrameWithId &actualPose)
An interface for collision checking.
Private Member Functions
bool collisionCheck (const std::vector< FrameWithId > &path, const FrameWithId &actualPose, double interpolationStep, unsigned int numberOfSteps)
Implementation of collision checking routine.
Private Attributes
costmap_2d::Costmap2DROS * costmap
Pointer to the actual map of the environment.
Detailed Description
Implementation of the collision checking interface.
Current implementation uses a ROS costmap collision checking routine.
Definition at line 56 of file CollisionCheckingRos.h.
Constructor & Destructor Documentation
CollisionCheckingRos::CollisionCheckingRos (costmap_2d::Costmap2DROS * costmap)
Constructor.
Parameters:
costmap - costmap_2d::Costmap2DROS a pointer to a costmap, which contains actual representation of the environment
Definition at line 57 of file CollisionCheckingRos.cpp.
CollisionCheckingRos::CollisionCheckingRos (CollisionCheckingRos & orig)
Copy constructor.
Definition at line 60 of file CollisionCheckingRos.cpp.
CollisionCheckingRos::~CollisionCheckingRos () [virtual]
Destructor.
Definition at line 64 of file CollisionCheckingRos.cpp.
Member Function Documentation
bool CollisionCheckingRos::check (const std::vector< FrameWithId > & path, const FrameWithId & actualPose) [virtual]
An interface for collision checking.
Parameters:
[in] path - std::vector <FrameWithId> actual path.
[in] actualPose - FrameWithId actual pose.
Returns:
true if there is a collision, false otherwise.
Implements ICollisionChecking.
Definition at line 68 of file CollisionCheckingRos.cpp.
References collisionCheck().
bool CollisionCheckingRos::collisionCheck (const std::vector< FrameWithId > & path, const FrameWithId & actualPose, double interpolationStep, unsigned int numberOfSteps) [private]
Implementation of collision checking routine.
Parameters:
[in] path - std::vector <FrameWithId> actual path.
[in] actualPose - FrameWithId actual pose.
interpolationStep - interpolation step.
numberOfSteps - number of steps
Returns:
true if there is a collision, false otherwise.
Definition at line 73 of file CollisionCheckingRos.cpp.
References collisionChecker, costmap, conversions::frameToPoseStampedRos(), Stopwatch::getElapsedTime(), LinearInterpolation::interpolate(), LOG, utilities::prunePath(), Stopwatch::start(), and Stopwatch::stop().
Referenced by check().
Member Data Documentation
costmap_2d::Costmap2DROS* CollisionCheckingRos::costmap [private]
Pointer to the actual map of the environment.
Definition at line 102 of file CollisionCheckingRos.h.
Referenced by collisionCheck().
The documentation for this class was generated from the following files:
navigation_trajectory_planner/include/navigation_trajectory_planner/CollisionCheckingRos.h
navigation_trajectory_planner/src/CollisionCheckingRos.cpp