BRICS_RN_Robust_Navigation_Library(BRICS_RN): ConversionUtils Class Reference
ConversionUtils Class Reference
#include <ConversionUtils.h>
Public Member Functions
void poseRosToKdl (const geometry_msgs::Pose &poseROS, KDL::Frame &poseKDL)
void poseKdlToRos (const KDL::Frame &poseKDL, geometry_msgs::Pose &poseROS)
void twistRosToKdl (const geometry_msgs::Twist &twistROS, KDL::Twist &twistKDL)
void twistKdlToRos (const KDL::Twist &twistKDL, geometry_msgs::Twist &twistROS)
void pathRosToKdl (const std::vector< geometry_msgs::PoseStamped > &poseStampedArray, KDL::Path_Composite &path)
void pathKdlToRos (const KDL::Path_Composite &path, std::vector< geometry_msgs::PoseStamped > &poseStampedArray)
void trajectoryRosToKdl (const std::vector< nav_msgs::Odometry > &trajectoryROS, KDL::Trajectory &trajectroyKDL, double dt)
void trajectoryKdlToRos (const KDL::Trajectory &trajectroyKDL, std::vector< nav_msgs::Odometry > &trajectoryROS, double dt)
Detailed Description
Definition at line 57 of file ConversionUtils.h.
Member Function Documentation
void ConversionUtils::pathKdlToRos (const KDL::Path_Composite & path, std::vector< geometry_msgs::PoseStamped > & poseStampedArray) [inline]
Definition at line 122 of file ConversionUtils.h.
void ConversionUtils::pathRosToKdl (const std::vector< geometry_msgs::PoseStamped > & poseStampedArray, KDL::Path_Composite & path) [inline]
Definition at line 98 of file ConversionUtils.h.
References poseRosToKdl().
void ConversionUtils::poseKdlToRos (const KDL::Frame & poseKDL, geometry_msgs::Pose & poseROS) [inline]
Definition at line 71 of file ConversionUtils.h.
Referenced by trajectoryKdlToRos().
void ConversionUtils::poseRosToKdl (const geometry_msgs::Pose & poseROS, KDL::Frame & poseKDL) [inline]
Definition at line 60 of file ConversionUtils.h.
Referenced by pathRosToKdl().
void ConversionUtils::trajectoryKdlToRos (const KDL::Trajectory & trajectroyKDL, std::vector< nav_msgs::Odometry > & trajectoryROS, double dt) [inline]
Definition at line 131 of file ConversionUtils.h.
References poseKdlToRos(), and twistKdlToRos().
void ConversionUtils::trajectoryRosToKdl (const std::vector< nav_msgs::Odometry > & trajectoryROS, KDL::Trajectory & trajectroyKDL, double dt) [inline]
Definition at line 127 of file ConversionUtils.h.
void ConversionUtils::twistKdlToRos (const KDL::Twist & twistKDL, geometry_msgs::Twist & twistROS) [inline]
Definition at line 88 of file ConversionUtils.h.
Referenced by trajectoryKdlToRos().
void ConversionUtils::twistRosToKdl (const geometry_msgs::Twist & twistROS, KDL::Twist & twistKDL) [inline]
Definition at line 83 of file ConversionUtils.h.
The documentation for this class was generated from the following file:
navigation_trajectory_follower/include/navigation_trajectory_follower/ConversionUtils.h