BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::Node Class Reference
brics_3d::rsg::Node Class Reference
A node in the robot scenegraph.
#include <Node.h>
Public Types
typedef boost::shared_ptr< Node > NodePtr
typedef boost::shared_ptr
< Node const > NodeConstPtr
typedef boost::weak_ptr< Node > NodeWeakPtr
typedef boost::weak_ptr< Node
const > NodeWeakConstPtr
typedef vector< Node * > NodePath
typedef vector< NodePath > NodePathList
Public Member Functions
Node ()
virtual ~Node ()
vector< Attribute > getAttributes ()
unsigned int getId () const
void setAttributes (vector< Attribute > attributes)
void setId (unsigned int id)
vector< Node * > getParents ()
Node * getParent (unsigned int index)
unsigned int getNumberOfParents () const
virtual void accept (INodeVisitor *visitor)
Private Member Functions
void addParent (Node *node)
void removeParent (Node *node)
Private Attributes
unsigned int id
Unique ID that will help to identify a certain node.
vector< Attribute > attributes
List of attributes for each node. Can be used to attach (semantic) tags.
vector< Node * > parents
List of pointers to the parent Nodes.
Friends
class brics_3d::rsg::Group
Detailed Description
A node in the robot scenegraph.
Definition at line 45 of file Node.h.
Member Typedef Documentation
typedef boost::shared_ptr<Node const> brics_3d::rsg::Node::NodeConstPtr
Definition at line 50 of file Node.h.
typedef vector< Node* > brics_3d::rsg::Node::NodePath
Definition at line 56 of file Node.h.
typedef vector< NodePath > brics_3d::rsg::Node::NodePathList
Definition at line 57 of file Node.h.
typedef boost::shared_ptr<Node> brics_3d::rsg::Node::NodePtr
Definition at line 49 of file Node.h.
typedef boost::weak_ptr<Node const> brics_3d::rsg::Node::NodeWeakConstPtr
Definition at line 53 of file Node.h.
typedef boost::weak_ptr<Node> brics_3d::rsg::Node::NodeWeakPtr
Definition at line 52 of file Node.h.
Constructor & Destructor Documentation
brics_3d::rsg::Node::Node ()
Definition at line 28 of file Node.cpp.
References attributes, and parents.
brics_3d::rsg::Node::~Node () [virtual]
Definition at line 34 of file Node.cpp.
Member Function Documentation
void brics_3d::rsg::Node::accept (INodeVisitor * visitor) [virtual]
Reimplemented in brics_3d::rsg::GeometricNode, brics_3d::rsg::Group, and brics_3d::rsg::Transform.
Definition at line 91 of file Node.cpp.
References accept(), brics_3d::rsg::INodeVisitor::getDirection(), getNumberOfParents(), getParent(), brics_3d::rsg::INodeVisitor::upwards, and brics_3d::rsg::INodeVisitor::visit().
Referenced by brics_3d::rsg::Transform::accept(), accept(), brics_3d::rsg::Group::accept(), and brics_3d::rsg::GeometricNode::accept().
void brics_3d::rsg::Node::addParent (Node * node) [private]
Definition at line 58 of file Node.cpp.
References parents.
vector< Attribute > brics_3d::rsg::Node::getAttributes ()
Definition at line 38 of file Node.cpp.
References attributes.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
unsigned int brics_3d::rsg::Node::getId () const
Definition at line 43 of file Node.cpp.
References id.
Referenced by brics_3d::rsg::OutdatedDataDeleter::doDeleteNode(), brics_3d::rsg::PointCloudAccumulatorIdAware::doGetTransformFromReferenceToPointCloud(), brics_3d::rsg::Transform::getLatestTimeStamp(), brics_3d::rsg::Transform::getLatestTransform(), brics_3d::rsg::Transform::getOldestTimeStamp(), brics_3d::rsg::Transform::getTransform(), brics_3d::rsg::SceneGraphToUpdatesTraverser::handleExistingNode(), and brics_3d::rsg::SceneGraphToUpdatesTraverser::visit().
unsigned int brics_3d::rsg::Node::getNumberOfParents () const
Definition at line 87 of file Node.cpp.
References parents.
Referenced by brics_3d::rsg::Transform::accept(), accept(), brics_3d::rsg::Group::accept(), brics_3d::rsg::GeometricNode::accept(), brics_3d::rsg::PointCloudAccumulator::doGetTransformFromReferenceToPointCloud(), and getParent().
Node * brics_3d::rsg::Node::getParent (unsigned int index)
Definition at line 76 of file Node.cpp.
References getNumberOfParents(), and parents.
Referenced by brics_3d::rsg::Transform::accept(), accept(), brics_3d::rsg::Group::accept(), brics_3d::rsg::GeometricNode::accept(), and brics_3d::rsg::PointCloudAccumulator::doGetTransformFromReferenceToPointCloud().
vector< Node * > brics_3d::rsg::Node::getParents ()
Definition at line 72 of file Node.cpp.
References parents.
Referenced by brics_3d::rsg::SceneGraphToUpdatesTraverser::handleExistingNode().
void brics_3d::rsg::Node::removeParent (Node * node) [private]
Definition at line 63 of file Node.cpp.
References parents.
void brics_3d::rsg::Node::setAttributes (vector< Attribute > attributes)
Definition at line 48 of file Node.cpp.
References attributes.
void brics_3d::rsg::Node::setId (unsigned int id)
Definition at line 53 of file Node.cpp.
References id.
Friends And Related Function Documentation
friend class brics_3d::rsg::Group [friend]
Definition at line 83 of file Node.h.
Member Data Documentation
vector<Attribute> brics_3d::rsg::Node::attributes [private]
List of attributes for each node. Can be used to attach (semantic) tags.
Definition at line 89 of file Node.h.
Referenced by getAttributes(), Node(), and setAttributes().
unsigned int brics_3d::rsg::Node::id [private]
Unique ID that will help to identify a certain node.
Definition at line 86 of file Node.h.
Referenced by getId(), and setId().
vector<Node*> brics_3d::rsg::Node::parents [private]
List of pointers to the parent Nodes.
Definition at line 92 of file Node.h.
Referenced by addParent(), getNumberOfParents(), getParent(), getParents(), Node(), and removeParent().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/Node.h
src/brics_3d/worldModel/sceneGraph/Node.cpp