BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::rsg::PointCloudAccumulator Class Reference
brics_3d::rsg::PointCloudAccumulator Class Reference
Scenegraph
Scenegraph visitor that collects all point clouds in a sub-graph and returns a point iterator brics_3d::IPoint3DIterator.
#include <PointCloudAccumulator.h>
Public Member Functions
PointCloudAccumulator (Node::NodePtr referenceNode)
Constructor with reference frame defined by the node.
virtual ~PointCloudAccumulator ()
Default destructor.
virtual void visit (Node *node)
virtual void visit (Group *node)
virtual void visit (Transform *node)
virtual void visit (GeometricNode *node)
virtual void reset ()
Reinitialize the internal iterator.
IPoint3DIterator * getAccumulatedPointClouds ()
Get the iterator that contains all point cloud in the subraph after a traversal.
virtual
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr doGetTransformFromReferenceToPointCloud (GeometricNode *node)
Overridable "template method" (for example for an ID aware version) for for resolving the transfrom between the reference frame and the fame valid in the currently visited GeometricNode.
Protected Attributes
PointCloud3DIterator * accumulatedPointClouds
Node::NodePtr referenceNode
Detailed Description
Scenegraph visitor that collects all point clouds in a sub-graph and returns a point iterator brics_3d::IPoint3DIterator.
This visitor will add every found point cloud visited while traversing a sub-graph (where accept() is called). Each point cloud will be interpreted ralative to the frame that is valid for the scenegraph node specified by referenceNode. The resulting iterator will handle this interpretation intrinsically as long you use the getters like brics_3d::IPoint3DIterator::getX().
Definition at line 44 of file PointCloudAccumulator.h.
Constructor & Destructor Documentation
brics_3d::rsg::PointCloudAccumulator::PointCloudAccumulator (Node::NodePtr referenceNode)
Constructor with reference frame defined by the node.
Parameters:
referenceNode The Cartesian frame that is valid for the node will be used as reference to interpret the 3D points.
Definition at line 31 of file PointCloudAccumulator.cpp.
References accumulatedPointClouds, referenceNode, and reset().
brics_3d::rsg::PointCloudAccumulator::~PointCloudAccumulator () [virtual]
Default destructor.
Definition at line 37 of file PointCloudAccumulator.cpp.
Member Function Documentation
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr brics_3d::rsg::PointCloudAccumulator::doGetTransformFromReferenceToPointCloud (GeometricNode * node) [virtual]
Overridable "template method" (for example for an ID aware version) for for resolving the transfrom between the reference frame and the fame valid in the currently visited GeometricNode.
Parameters:
node The currently visited GeometricNode.
Reimplemented in brics_3d::rsg::PointCloudAccumulatorIdAware.
Definition at line 76 of file PointCloudAccumulator.cpp.
References brics_3d::rsg::Group::getChild(), brics_3d::rsg::Group::getChildIndex(), brics_3d::rsg::Node::getNumberOfParents(), brics_3d::rsg::Node::getParent(), brics_3d::rsg::getTransformBetweenNodes(), LOG, and referenceNode.
Referenced by visit().
IPoint3DIterator* brics_3d::rsg::PointCloudAccumulator::getAccumulatedPointClouds () [inline]
Get the iterator that contains all point cloud in the subraph after a traversal.
A traversal is triggered by calling brics_3d::rsg::Node::accept().
Returns:
The iterator handle.
Definition at line 75 of file PointCloudAccumulator.h.
References accumulatedPointClouds.
void brics_3d::rsg::PointCloudAccumulator::reset () [virtual]
Reinitialize the internal iterator.
Invoke this before travasing more then once. Otherwise data will be appended.
Definition at line 41 of file PointCloudAccumulator.cpp.
References accumulatedPointClouds.
Referenced by PointCloudAccumulator().
void brics_3d::rsg::PointCloudAccumulator::visit (Group * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 49 of file PointCloudAccumulator.cpp.
void brics_3d::rsg::PointCloudAccumulator::visit (GeometricNode * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 57 of file PointCloudAccumulator.cpp.
References accumulatedPointClouds, brics_3d::rsg::PointCloud< PointCloudT >::data, doGetTransformFromReferenceToPointCloud(), brics_3d::rsg::GeometricNode::getShape(), and brics_3d::PointCloud3DIterator::insert().
void brics_3d::rsg::PointCloudAccumulator::visit (Transform * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 53 of file PointCloudAccumulator.cpp.
void brics_3d::rsg::PointCloudAccumulator::visit (Node * node) [virtual]
Reimplemented from brics_3d::rsg::INodeVisitor.
Definition at line 45 of file PointCloudAccumulator.cpp.
Member Data Documentation
PointCloud3DIterator* brics_3d::rsg::PointCloudAccumulator::accumulatedPointClouds [protected]
Definition at line 87 of file PointCloudAccumulator.h.
Referenced by getAccumulatedPointClouds(), PointCloudAccumulator(), reset(), and visit().
Node::NodePtr brics_3d::rsg::PointCloudAccumulator::referenceNode [protected]
Definition at line 88 of file PointCloudAccumulator.h.
Referenced by doGetTransformFromReferenceToPointCloud(), and PointCloudAccumulator().
The documentation for this class was generated from the following files:
src/brics_3d/worldModel/sceneGraph/PointCloudAccumulator.h
src/brics_3d/worldModel/sceneGraph/PointCloudAccumulator.cpp