BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::OSGTriangleMeshVisualizer Class Reference
brics_3d::OSGTriangleMeshVisualizer Class Reference
Visualization
Displays triangle meshes in an Open Scene Graph (OSG) viewer.
#include <OSGTriangleMeshVisualizer.h>
Public Member Functions
OSGTriangleMeshVisualizer ()
virtual ~OSGTriangleMeshVisualizer ()
void addTriangleMesh (ITriangleMesh *mesh)
void visualize ()
Static Public Member Functions
static osg::ref_ptr< osg::Node > createTriangleMeshNode (ITriangleMesh *mesh, float red=1.0f, float green=1.0f, float blue=1.0f, float alpha=1.0f)
Static Private Member Functions
static osg::ref_ptr
< osg::TriangleMesh > createTriangleMesh (ITriangleMesh *mesh)
Create an OSG TriangleMesh from an ITriangleMesh.
Private Attributes
osgViewer::Viewer viewer
OSG viewer object.
osg::Group * rootGeode
Root node for scenegraph.
Detailed Description
Displays triangle meshes in an Open Scene Graph (OSG) viewer.
Definition at line 38 of file OSGTriangleMeshVisualizer.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d util OSGTriangleMeshVisualizer cpp brics_3d::OSGTriangleMeshVisualizer::OSGTriangleMeshVisualizer ()
Definition at line 31 of file OSGTriangleMeshVisualizer.cpp.
brics_3d::OSGTriangleMeshVisualizer::~OSGTriangleMeshVisualizer () [virtual]
Definition at line 41 of file OSGTriangleMeshVisualizer.cpp.
Member Function Documentation
void brics_3d::OSGTriangleMeshVisualizer::addTriangleMesh (ITriangleMesh * mesh)
Definition at line 45 of file OSGTriangleMeshVisualizer.cpp.
osg::ref_ptr< osg::TriangleMesh > brics_3d::OSGTriangleMeshVisualizer::createTriangleMesh (ITriangleMesh * mesh) [static, private]
Create an OSG TriangleMesh from an ITriangleMesh.
Definition at line 73 of file OSGTriangleMeshVisualizer.cpp.
References brics_3d::TriangleMeshImplicit::getIndices(), brics_3d::TriangleMeshImplicit::getNumberOfVertices(), brics_3d::TriangleMeshImplicit::getSize(), brics_3d::TriangleMeshImplicit::getVertices(), brics_3d::Point3D::getX(), brics_3d::Point3D::getY(), and brics_3d::Point3D::getZ().
osg::ref_ptr< osg::Node > brics_3d::OSGTriangleMeshVisualizer::createTriangleMeshNode (ITriangleMesh * mesh, float red = 1.0f, float green = 1.0f, float blue = 1.0f, float alpha = 1.0f) [static]
Definition at line 57 of file OSGTriangleMeshVisualizer.cpp.
void brics_3d::OSGTriangleMeshVisualizer::visualize ()
Definition at line 49 of file OSGTriangleMeshVisualizer.cpp.
Member Data Documentation
osg::Group* brics_3d::OSGTriangleMeshVisualizer::rootGeode [private]
Root node for scenegraph.
Definition at line 62 of file OSGTriangleMeshVisualizer.h.
osgViewer::Viewer brics_3d::OSGTriangleMeshVisualizer::viewer [private]
OSG viewer object.
Definition at line 59 of file OSGTriangleMeshVisualizer.h.
The documentation for this class was generated from the following files:
src/brics_3d/util/OSGTriangleMeshVisualizer.h
src/brics_3d/util/OSGTriangleMeshVisualizer.cpp