BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelCircle Class Reference
brics_3d::ObjectModelCircle Class Reference
Segmentation
#include <ObjectModelCircle.h>
Public Member Functions
ObjectModelCircle ()
virtual ~ObjectModelCircle ()
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXd &model_coefficients)
void getDistancesToModel (const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Compute all distances from the cloud data to a given 2D circle model.
void selectWithinDistance (const Eigen::VectorXd &model_coefficients, double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
void getInlierDistance (std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Select all the points which respect the given model coefficients as inliers.
bool doSamplesVerifyModel (const std::set< int > &indices, const Eigen::VectorXd &model_coefficients, double threshold)
Verify whether a subset of indices verifies a given set of model coefficients.
void computeRandomModel (int &iterations, Eigen::VectorXd &model_coefficients, bool &isDegenerate, bool &modelFound)
Compute the model coefficients by generating some random samples.
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Detailed Description
Definition at line 30 of file ObjectModelCircle.h.
Constructor & Destructor Documentation
brics_3d::ObjectModelCircle::ObjectModelCircle () [inline]
Definition at line 36 of file ObjectModelCircle.h.
virtual brics_3d::ObjectModelCircle::~ObjectModelCircle () [inline, virtual]
Definition at line 37 of file ObjectModelCircle.h.
Member Function Documentation
bool brics_3d::ObjectModelCircle::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXd & model_coefficients)
Definition at line 124 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
Referenced by computeRandomModel().
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelCircle cpp void brics_3d::ObjectModelCircle::computeRandomModel (int & iterations, Eigen::VectorXd & model_coefficients, bool & isDegenerate, bool & modelFound) [virtual]
Compute the model coefficients by generating some random samples.
Parameters:
model_coefficients,: the computed model coefficients
isDegenerate,: Whether degenerate samples are found from the input pointcloud or not
modelFound,: Whether a valid model is found from the sample or not
Implements brics_3d::IObjectModel.
Definition at line 27 of file ObjectModelCircle.cpp.
References computeModelCoefficients(), and getSamples().
bool brics_3d::ObjectModelCircle::doSamplesVerifyModel (const std::set< int > & indices, const Eigen::VectorXd & model_coefficients, double threshold) [virtual]
Verify whether a subset of indices verifies a given set of model coefficients.
Pure virtual.
Parameters:
indices the data indices that need to be tested against the model
model_coefficients the set of model coefficients
threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements brics_3d::IObjectModel.
Definition at line 232 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelCircle::getDistancesToModel (const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Compute all distances from the cloud data to a given 2D circle model.
Parameters:
model_coefficients the coefficients of a 2D circle model that we need to compute distances to
distances the resultant estimated distances
Implements brics_3d::IObjectModel.
Definition at line 158 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
void brics_3d::ObjectModelCircle::getInlierDistance (std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
distances of inliers from the model
Implements brics_3d::IObjectModel.
Definition at line 179 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
int brics_3d::ObjectModelCircle::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Implements brics_3d::IObjectModel.
Definition at line 48 of file ObjectModelCircle.h.
void brics_3d::ObjectModelCircle::getSamples (int & iterations, std::vector< int > & samples)
Definition at line 56 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::IObjectModel::inputPointCloud, and brics_3d::IObjectModel::MAX_ITERATIONS_COLLINEAR.
Referenced by computeRandomModel().
void brics_3d::ObjectModelCircle::selectWithinDistance (const Eigen::VectorXd & model_coefficients, double threshold, std::vector< int > & inliers) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
inliers the resultant model inliers
Implements brics_3d::IObjectModel.
Definition at line 201 of file ObjectModelCircle.cpp.
References brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), and brics_3d::IObjectModel::inputPointCloud.
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelCircle.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelCircle.cpp