BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::Octree Class Reference
brics_3d::Octree Class Reference
Filtering
Implementation of the Octree component.
#include <Octree.h>
Public Member Functions
Octree ()
Standard constructor.
virtual ~Octree ()
Standard destructor.
void filter (PointCloud3D *originalPointCloud, PointCloud3D *resultPointCloud)
Reduce the size of a point cloud.
void partitionPointCloud (PointCloud3D *pointCloud, std::vector< PointCloud3D * > *pointCloudCells)
Partitions a point cloud into sub points clouds.
void setVoxelSize (double voxelSize)
Set the size of the maximum of smallest voxel in an Octree.
double getVoxelSize ()
Get the current size the maximum of the smallest voxel in an Octree.
Private Attributes
double voxelSize
The maximum voxel size of the smallest cube in the Octree.
Detailed Description
Implementation of the Octree component.
Definition at line 33 of file Octree.h.
Constructor & Destructor Documentation
brics_3d::Octree::Octree ()
Standard constructor.
Definition at line 29 of file Octree.cpp.
References voxelSize.
brics_3d::Octree::~Octree () [virtual]
Standard destructor.
Definition at line 33 of file Octree.cpp.
Member Function Documentation
void brics_3d::Octree::filter (PointCloud3D * originalPointCloud, PointCloud3D * resultPointCloud) [virtual]
Reduce the size of a point cloud.
The behavior of the size reduction can be influenced with the parameter voxel size: IOctreeSetup::setVoxelSize()
Parameters:
[in] originalPointCloud The input point cloud that will be reduced. This data will not be modified.
[out] resultPointCloud The new point cloud with the reduced amount of points.
Implements brics_3d::IOctreeReductionFilter.
Definition at line 37 of file Octree.cpp.
References brics_3d::PointCloud3D::addPoint(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::Point3D::setX(), brics_3d::Point3D::setY(), brics_3d::Point3D::setZ(), and voxelSize.
double brics_3d::Octree::getVoxelSize () [virtual]
Get the current size the maximum of the smallest voxel in an Octree.
Returns:
The current size.
Implements brics_3d::IOctreeSetup.
Definition at line 160 of file Octree.cpp.
References voxelSize.
void brics_3d::Octree::partitionPointCloud (PointCloud3D * pointCloud, std::vector< PointCloud3D * > * pointCloudCells) [virtual]
Partitions a point cloud into sub points clouds.
The behavior of the subdivision can be influenced with the parameter voxel size: IOctreeSetup::setVoxelSize()
Parameters:
[in] pointCloud The input point cloud that will be partitioned. This data will not be modified.
[out] pointCloudCells Resulting vector of point clouds. Each point cloud represents one cell of the partition.
Implements brics_3d::IOctreePartition.
Definition at line 92 of file Octree.cpp.
References brics_3d::PointCloud3D::addPoint(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::Point3D::setX(), brics_3d::Point3D::setY(), brics_3d::Point3D::setZ(), and voxelSize.
void brics_3d::Octree::setVoxelSize (double voxelSize) [virtual]
Set the size of the maximum of smallest voxel in an Octree.
Parameters:
voxelSize The new voxel size. NOTE: the current implementation interprets voxelSize as the from the center to one of the cube faces.
Implements brics_3d::IOctreeSetup.
Definition at line 153 of file Octree.cpp.
References voxelSize.
Member Data Documentation
double brics_3d::Octree::voxelSize [private]
The maximum voxel size of the smallest cube in the Octree.
Definition at line 57 of file Octree.h.
Referenced by filter(), getVoxelSize(), Octree(), partitionPointCloud(), and setVoxelSize().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/filtering/Octree.h
src/brics_3d/algorithm/filtering/Octree.cpp