BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ISACMethods Class Reference
brics_3d::ISACMethods Class Reference
Segmentation
Abstract interface for Sample-Based-Consensus(SAC) methods.
#include <ISACMethods.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
void setObjectModel (IObjectModel *objectModel)
Set the object model to be used.
void setPointCloud (PointCloud3D *inputPointCloud)
Set the pointcloud to be used.
void setDistanceThreshold (double threshold)
Set the user-defined threshold distance to the model.
double getDistanceThreshold ()
Get the distance to model threshold.
void setMaxIterations (int maxIterations)
Set the maximum number of iterations for model estimation.
int getMaxIterations ()
Get the maximum number of iterations for model estimation.
void setProbability (double probability)
Set the desired probability of choosing at least one sample free from outliers.
double getProbability ()
Obtain the probability of choosing at least one sample free from outliers.
virtual bool computeModel ()=0
Compute the actual model.
void getRandomSamples (std::set< int > &indices, size_t noSamples, std::set< int > &randomSamples)
Get a set of randomly selected indices.
void getInliers (std::vector< int > &inliers)
Return the best set of inliers found so far for this model.
void getModelCoefficients (Eigen::VectorXd &modelCoefficients)
Return the model coefficients of the best model found so far.
void setModelType (int modelType)
Set the type of the model to be estimated.
int getModelType ()
Get the type of SAC model to beestimated.
void setMethodType (int methodType)
Set the type of sample consensus method to be used.
int getMethodType ()
Get the type of sample consensus method used.
void setOptimizeCoefficients (bool optimize)
Set to true if a coefficient refinement is required.
bool getOptimizeCoefficients ()
Get the coefficient refinement internal flag.
Protected Attributes
IObjectModel * objectModel
The object model to be searched for in its parametric form.
double threshold
Threshold distance to model.
int maxIterations
Maximum number of iterations for model estimation.
double probability
Probability of choosing at least one sample free from outliers.
std::vector< int > inliers
The point indices corresponding to the model computed in the last iteration.
Eigen::VectorXd modelCoefficients
The estimated model coefficients.
int iterations
No of iterations for model estimation already completed.
int modelType
Indicates the object model estimated.
int SACMethodType
Indicates the sample consensus method used for estimating the model.
bool optimizeCoefficients
Indicates if model coefficient refinement is enabled.
PointCloud3D * inputPointCloud
The input point-cloud to be processed.
Detailed Description
Abstract interface for Sample-Based-Consensus(SAC) methods.
Definition at line 22 of file ISACMethods.h.
Member Function Documentation
virtual bool brics_3d::ISACMethods::computeModel () [pure virtual]
Compute the actual model.
Pure virtual.
Implemented in brics_3d::SACMethodALMeDS, brics_3d::SACMethodLMeDS, brics_3d::SACMethodMLESAC, brics_3d::SACMethodMSAC, and brics_3d::SACMethodRANSAC.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::segment(), and brics_3d::RegionBasedSACSegmentation::segment().
double brics_3d::ISACMethods::getDistanceThreshold () [inline]
Get the distance to model threshold.
Definition at line 95 of file ISACMethods.h.
References threshold.
void brics_3d::ISACMethods::getInliers (std::vector< int > & inliers) [inline]
Return the best set of inliers found so far for this model.
Parameters:
inliers the resultant set of inliers found
Definition at line 162 of file ISACMethods.h.
References inliers.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::segment(), and brics_3d::RegionBasedSACSegmentation::segment().
int brics_3d::ISACMethods::getMaxIterations () [inline]
Get the maximum number of iterations for model estimation.
Definition at line 113 of file ISACMethods.h.
References maxIterations.
Referenced by brics_3d::RegionBasedSACSegmentation::initSACMethod().
int brics_3d::ISACMethods::getMethodType () [inline]
Get the type of sample consensus method used.
Definition at line 207 of file ISACMethods.h.
References SACMethodType.
void brics_3d::ISACMethods::getModelCoefficients (Eigen::VectorXd & modelCoefficients) [inline]
Return the model coefficients of the best model found so far.
Parameters:
modelCoefficients the resultant model coefficients
Definition at line 172 of file ISACMethods.h.
References modelCoefficients.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::segment(), and brics_3d::RegionBasedSACSegmentation::segment().
int brics_3d::ISACMethods::getModelType () [inline]
Get the type of SAC model to beestimated.
Definition at line 189 of file ISACMethods.h.
References modelType.
bool brics_3d::ISACMethods::getOptimizeCoefficients () [inline]
Get the coefficient refinement internal flag.
Definition at line 225 of file ISACMethods.h.
References optimizeCoefficients.
double brics_3d::ISACMethods::getProbability () [inline]
Obtain the probability of choosing at least one sample free from outliers.
Definition at line 131 of file ISACMethods.h.
References probability.
Referenced by brics_3d::RegionBasedSACSegmentation::initSACMethod().
void brics_3d::ISACMethods::getRandomSamples (std::set< int > & indices, size_t noSamples, std::set< int > & randomSamples) [inline]
Get a set of randomly selected indices.
Parameters:
indices the input indices vector
noSamples the desired number of point indices to randomly select
randomSamples the resultant output set of randomly selected indices
Definition at line 150 of file ISACMethods.h.
void brics_3d::ISACMethods::setDistanceThreshold (double threshold) [inline]
Set the user-defined threshold distance to the model.
Parameters:
threshold user-defined thresholddistance to model threshold
Definition at line 87 of file ISACMethods.h.
References threshold.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACMethod(), and brics_3d::RegionBasedSACSegmentation::initSACMethod().
void brics_3d::ISACMethods::setMaxIterations (int maxIterations) [inline]
Set the maximum number of iterations for model estimation.
Parameters:
max_iterations maximum number of iterations for model estimation
Definition at line 105 of file ISACMethods.h.
References maxIterations.
Referenced by brics_3d::RegionBasedSACSegmentation::initSACMethod().
void brics_3d::ISACMethods::setMethodType (int methodType) [inline]
Set the type of sample consensus method to be used.
Parameters:
methodType the method type
Definition at line 199 of file ISACMethods.h.
References SACMethodType.
void brics_3d::ISACMethods::setModelType (int modelType) [inline]
Set the type of the model to be estimated.
Parameters:
modelType the model type
Definition at line 182 of file ISACMethods.h.
References modelType.
EIGEN_MAKE_ALIGNED_OPERATOR_NEW void brics_3d::ISACMethods::setObjectModel (IObjectModel * objectModel) [inline]
Set the object model to be used.
Parameters:
pointer to the object model
Definition at line 67 of file ISACMethods.h.
References objectModel.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACMethod(), and brics_3d::RegionBasedSACSegmentation::initSACMethod().
void brics_3d::ISACMethods::setOptimizeCoefficients (bool optimize) [inline]
Set to true if a coefficient refinement is required.
Parameters:
optimize true for enabling model coefficient refinement, false otherwise
Definition at line 217 of file ISACMethods.h.
References optimizeCoefficients.
void brics_3d::ISACMethods::setPointCloud (PointCloud3D * inputPointCloud) [inline]
Set the pointcloud to be used.
Parameters:
pointer to the input pointcloud
Definition at line 78 of file ISACMethods.h.
References inputPointCloud.
Referenced by brics_3d::RegionBasedSACSegmentationUsingNormals::initSACMethod(), and brics_3d::RegionBasedSACSegmentation::initSACMethod().
void brics_3d::ISACMethods::setProbability (double probability) [inline]
Set the desired probability of choosing at least one sample free from outliers.
Parameters:
probability the desired probability of choosing at least one sample free from outliers
Definition at line 123 of file ISACMethods.h.
References probability.
Referenced by brics_3d::RegionBasedSACSegmentation::initSACMethod().
Member Data Documentation
std::vector<int> brics_3d::ISACMethods::inliers [protected]
The point indices corresponding to the model computed in the last iteration.
Definition at line 37 of file ISACMethods.h.
Referenced by getInliers().
PointCloud3D* brics_3d::ISACMethods::inputPointCloud [protected]
The input point-cloud to be processed.
Definition at line 57 of file ISACMethods.h.
Referenced by setPointCloud().
int brics_3d::ISACMethods::iterations [protected]
No of iterations for model estimation already completed.
Definition at line 43 of file ISACMethods.h.
Referenced by brics_3d::SACMethodMLESAC::setEMIterations().
int brics_3d::ISACMethods::maxIterations [protected]
Maximum number of iterations for model estimation.
Default value 10000
Definition at line 31 of file ISACMethods.h.
Referenced by getMaxIterations(), and setMaxIterations().
Eigen::VectorXd brics_3d::ISACMethods::modelCoefficients [protected]
The estimated model coefficients.
Definition at line 40 of file ISACMethods.h.
Referenced by getModelCoefficients().
int brics_3d::ISACMethods::modelType [protected]
Indicates the object model estimated.
Definition at line 46 of file ISACMethods.h.
Referenced by getModelType(), and setModelType().
IObjectModel* brics_3d::ISACMethods::objectModel [protected]
The object model to be searched for in its parametric form.
Definition at line 25 of file ISACMethods.h.
Referenced by setObjectModel().
bool brics_3d::ISACMethods::optimizeCoefficients [protected]
Indicates if model coefficient refinement is enabled.
Definition at line 54 of file ISACMethods.h.
Referenced by getOptimizeCoefficients(), and setOptimizeCoefficients().
double brics_3d::ISACMethods::probability [protected]
Probability of choosing at least one sample free from outliers.
Default value 0.99
Definition at line 34 of file ISACMethods.h.
Referenced by getProbability(), and setProbability().
int brics_3d::ISACMethods::SACMethodType [protected]
Indicates the sample consensus method used for estimating the model.
Definition at line 51 of file ISACMethods.h.
Referenced by getMethodType(), and setMethodType().
double brics_3d::ISACMethods::threshold [protected]
Threshold distance to model.
Default value -1
Definition at line 28 of file ISACMethods.h.
Referenced by getDistanceThreshold(), and setDistanceThreshold().
The documentation for this class was generated from the following file:
src/brics_3d/algorithm/segmentation/SACMethods/ISACMethods.h