BRICS_RN (Robust Navigation Library): OmniDrivePositionController Class Reference
OmniDrivePositionController Class Reference
Implementation of the interface class for a position controller for omnidirectional mobile platform.
#include <OmniDrivePositionController.h>
Public Member Functions
OmniDrivePositionController (double positionGainTranslation, double velocityGainTranslation, double positionGainRotation, double velocityGainRotation, double positionToleranceTranslation, double velocityToleranceTranslation, double positionToleranceRotation, double velocityToleranceRotation)
Constructor.
OmniDrivePositionController ()
Default constructor.
OmniDrivePositionController (const OmniDrivePositionController &orig)
virtual ~OmniDrivePositionController ()
void setTargetTrajectory (const TrajectoryWithId &trajectory)
Sets a trajectory to follow.
const TrajectoryWithId & getTargetTrajectory () const
Gets an actual trajectory.
void setTargetOdometry (const Odometry &targetOdometry)
Sets a goal pose to reach.
const Odometry & getTargetOdometry () const
Gets an actual goal pose.
void setTolerance (const Odometry &tolerance)
Sets tolerance parameter for a controller.
const Odometry & getTolerance () const
Get tolerance parameter.
const Odometry & computeNewOdometry (const Odometry &actualOdometry, double elapsedTimeInSec)
Computes desired odometry, given actual odometry and a time step.
bool isTargetReached () const
Returns true if target has been reached.
Private Member Functions
float getDistance (const Pose2D &actualPose, const Pose2D &goalPose)
Calculates a distance between two points (for 2D space).
float getShortestAngle (float goalAngle, float actualAngle)
Calculates a shortest rotation angle (for 2D space).
void resetFlags ()
Resets internal flags.
void targetReached (bool &translation, bool &rotation)
Checks if the goal has been reached.
Private Attributes
Odometry gains
Holds gain values.
Odometry tolerance
Holds tolerance values.
TrajectoryWithId targetTrajectory
Holds target trajectory.
Odometry targetOdometry
Holds goal position.
Odometry computedOdometry
Holds last setpoint for odometry.
Odometry actualOdometry
Holds odometry feedback from the sensors.
double actualTime
Holds actual execution time.
bool translationFlag
Internal flags.
bool rotationFlag
Internal flags.
Detailed Description
Implementation of the interface class for a position controller for omnidirectional mobile platform.
Definition at line 53 of file OmniDrivePositionController.h.
Constructor & Destructor Documentation
OmniDrivePositionController::OmniDrivePositionController (double positionGainTranslation, double velocityGainTranslation, double positionGainRotation, double velocityGainRotation, double positionToleranceTranslation, double velocityToleranceTranslation, double positionToleranceRotation, double velocityToleranceRotation)
Constructor.
Parameters
positionGainTranslation - gain coefficient for a position feedback for linear motion.
velocityGainTranslation - gain coefficient for a velocity feedback for linear motion.
positionGainRotation - gain coefficient for a position feedback for angular motion.
velocityGainRotation - gain coefficient for a velocity feedback for angular motion.
positionToleranceTranslation - tolerance value for a position for linear motion.
velocityToleranceTranslation - tolerance value for a velocity for linear motion.
positionToleranceRotation - tolerance value for a position for linear motion.
velocityToleranceRotation - tolerance value for a velocity for linear motion.
Definition at line 53 of file OmniDrivePositionController.cpp.
OmniDrivePositionController::OmniDrivePositionController ()
Default constructor.
Definition at line 82 of file OmniDrivePositionController.cpp.
OmniDrivePositionController::OmniDrivePositionController (const OmniDrivePositionController & orig)
Definition at line 89 of file OmniDrivePositionController.cpp.
References actualTime, getTargetOdometry(), getTolerance(), rotationFlag, targetOdometry, tolerance, and translationFlag.
OmniDrivePositionController::~OmniDrivePositionController () virtual
Definition at line 101 of file OmniDrivePositionController.cpp.
Member Function Documentation
const Odometry & OmniDrivePositionController::computeNewOdometry (const Odometry & actualOdometry, double elapsedTimeInSec) virtual
Computes desired odometry, given actual odometry and a time step.
Parameters
[in] actualOdometry - actual odometry.
elapsedTimeInSec - a time step.
Returns
setpoint odometry, which includes updated velocities and pose
Implements IPositionController.
Definition at line 163 of file OmniDrivePositionController.cpp.
References actualOdometry, actualTime, computedOdometry, OmniDriveKinematicsModel::convertToLocalReferenceFrame(), gains, Odometry::getPose2D(), getShortestAngle(), Pose2D::getTheta(), Twist2D::getTheta(), TrajectoryWithId::getTrajectory(), Odometry::getTwist2D(), Twist2D::getX(), Pose2D::getX(), Pose2D::getY(), Twist2D::getY(), isTargetReached(), Odometry::setTwist2D(), and targetTrajectory.
float OmniDrivePositionController::getDistance (const Pose2D & actualPose, const Pose2D & goalPose) private
Calculates a distance between two points (for 2D space).
Parameters
[in] actualPose - 1st point coordinates.
[in] goalPose - 2nd point coordinates.
Returns
distance
Definition at line 236 of file OmniDrivePositionController.cpp.
References Pose2D::getX(), and Pose2D::getY().
Referenced by targetReached().
float OmniDrivePositionController::getShortestAngle (float goalAngle, float actualAngle) private
Calculates a shortest rotation angle (for 2D space).
Parameters
[in] goalAngle - 1st angle.
[in] actualAngle - 2nd angle.
Returns
shortest angle
Definition at line 232 of file OmniDrivePositionController.cpp.
Referenced by computeNewOdometry(), and targetReached().
const Odometry & OmniDrivePositionController::getTargetOdometry () const virtual
Gets an actual goal pose.
Returns
Odometry value of the actual goal pose.
Implements IPositionController.
Definition at line 114 of file OmniDrivePositionController.cpp.
References targetOdometry.
Referenced by OmniDrivePositionController().
const TrajectoryWithId & OmniDrivePositionController::getTargetTrajectory () const virtual
Gets an actual trajectory.
Returns
TrajectoryWithId is and aggregatin of KDL::Trajectory with frame id.
Implements IPositionController.
Definition at line 126 of file OmniDrivePositionController.cpp.
References targetTrajectory.
const Odometry & OmniDrivePositionController::getTolerance () const virtual
Get tolerance parameter.
Returns
tolerance of the positioning procedure.
Implements IPositionController.
Definition at line 245 of file OmniDrivePositionController.cpp.
References tolerance.
Referenced by OmniDrivePositionController().
bool OmniDrivePositionController::isTargetReached () const virtual
Returns true if target has been reached.
otherwise false.
Implements IPositionController.
Definition at line 130 of file OmniDrivePositionController.cpp.
References rotationFlag, and translationFlag.
Referenced by computeNewOdometry().
void OmniDrivePositionController::resetFlags () private
Resets internal flags.
Definition at line 105 of file OmniDrivePositionController.cpp.
References rotationFlag, and translationFlag.
Referenced by setTargetTrajectory().
void OmniDrivePositionController::setTargetOdometry (const Odometry & targetOdometry) virtual
Sets a goal pose to reach.
Parameters
[in] targetOdometry - a goal pose
Implements IPositionController.
Definition at line 110 of file OmniDrivePositionController.cpp.
References targetOdometry.
void OmniDrivePositionController::setTargetTrajectory (const TrajectoryWithId & trajectory) virtual
Sets a trajectory to follow.
Parameters
[in] trajectory - a target trajectory
Implements IPositionController.
Definition at line 118 of file OmniDrivePositionController.cpp.
References TrajectoryWithId::getTrajectory(), TrajectoryWithId::id, resetFlags(), TrajectoryWithId::setTrajectory(), and targetTrajectory.
void OmniDrivePositionController::setTolerance (const Odometry & tolerance) virtual
Sets tolerance parameter for a controller.
Parameters
[in] tolerance - required tolerance for positioning procedure.
Implements IPositionController.
Definition at line 241 of file OmniDrivePositionController.cpp.
References tolerance.
void OmniDrivePositionController::targetReached (bool & translation, bool & rotation) private
Checks if the goal has been reached.
Parameters
[out] translation - flag is set to true if target location is reached, otherwise false.
[out] rotation - flag is set to true if target rotation is reached, otherwise false.
Definition at line 135 of file OmniDrivePositionController.cpp.
References actualOdometry, actualPose, getDistance(), Odometry::getPose2D(), getShortestAngle(), Pose2D::getTheta(), TrajectoryWithId::getTrajectory(), Pose2D::getX(), Pose2D::getY(), targetTrajectory, and tolerance.
Member Data Documentation
Odometry OmniDrivePositionController::actualOdometry private
Holds odometry feedback from the sensors.
Definition at line 191 of file OmniDrivePositionController.h.
Referenced by computeNewOdometry(), and targetReached().
double OmniDrivePositionController::actualTime private
Holds actual execution time.
Definition at line 196 of file OmniDrivePositionController.h.
Referenced by computeNewOdometry(), and OmniDrivePositionController().
Odometry OmniDrivePositionController::computedOdometry private
Holds last setpoint for odometry.
Definition at line 186 of file OmniDrivePositionController.h.
Referenced by computeNewOdometry().
Odometry OmniDrivePositionController::gains private
Holds gain values.
Definition at line 166 of file OmniDrivePositionController.h.
Referenced by computeNewOdometry().
bool OmniDrivePositionController::rotationFlag private
Internal flags.
Definition at line 206 of file OmniDrivePositionController.h.
Referenced by isTargetReached(), OmniDrivePositionController(), and resetFlags().
Odometry OmniDrivePositionController::targetOdometry private
Holds goal position.
Definition at line 181 of file OmniDrivePositionController.h.
Referenced by getTargetOdometry(), OmniDrivePositionController(), and setTargetOdometry().
TrajectoryWithId OmniDrivePositionController::targetTrajectory private
Holds target trajectory.
Definition at line 176 of file OmniDrivePositionController.h.
Referenced by computeNewOdometry(), getTargetTrajectory(), setTargetTrajectory(), and targetReached().
Odometry OmniDrivePositionController::tolerance private
Holds tolerance values.
Definition at line 171 of file OmniDrivePositionController.h.
Referenced by getTolerance(), OmniDrivePositionController(), setTolerance(), and targetReached().
bool OmniDrivePositionController::translationFlag private
Internal flags.
Definition at line 201 of file OmniDrivePositionController.h.
Referenced by isTargetReached(), OmniDrivePositionController(), and resetFlags().
The documentation for this class was generated from the following files:
navigation_trajectory_follower/src/omnidrive_controller/OmniDrivePositionController.h
navigation_trajectory_follower/src/omnidrive_controller/OmniDrivePositionController.cpp