BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::PointCloud3D Class Reference
brics_3d::PointCloud3D Class Reference
Class to represent a Cartesian 3D point cloud.
#include <PointCloud3D.h>
Public Types
typedef boost::shared_ptr
< PointCloud3D > PointCloud3DPtr
typedef boost::shared_ptr
< PointCloud3D const > PointCloud3DConstPtr
Public Member Functions
PointCloud3D ()
Standard constuctor.
virtual ~PointCloud3D ()
Standard destructor.
void addPoint (Point3D point)
Add a point to the point cloud.
void addPointPtr (Point3D *point)
Add a point to the point cloud with reference semantics.
boost::ptr_vector< Point3D > * getPointCloud ()
Get the pointer to the point cloud.
void setPointCloud (boost::ptr_vector< Point3D > *pointCloud)
Set the pointer to the point cloud.
unsigned int getSize ()
Get the number of points in the point cloud.
void storeToPlyFile (std::string filename)
Stores the point cloud into a ply file (Stanford polygon file format)
void storeToTxtFile (std::string filename)
Stores the point cloud into a sipmle text file (x y z)
void readFromTxtFile (std::string filename)
Reads data from a simple text file (x y z) and appends it to this point cloud.
void homogeneousTransformation (IHomogeneousMatrix44 *transformation)
Applies a homogeneous transformation to the point cloud.
Protected Attributes
boost::ptr_vector< Point3D > * pointCloud
Pointer to vector which represents a Cartesian point cloud.
Friends
istream & operator>> (istream &inStream, PointCloud3D &pointCloud)
Overridden >> operator.
ostream & operator<< (ostream &outStream, PointCloud3D &pointCloud)
Overridden << operator.
Detailed Description
Class to represent a Cartesian 3D point cloud.
Definition at line 36 of file PointCloud3D.h.
Member Typedef Documentation
typedef boost::shared_ptr<PointCloud3D const> brics_3d::PointCloud3D::PointCloud3DConstPtr
Definition at line 40 of file PointCloud3D.h.
typedef boost::shared_ptr<PointCloud3D> brics_3d::PointCloud3D::PointCloud3DPtr
Definition at line 39 of file PointCloud3D.h.
Constructor & Destructor Documentation
brics_3d::PointCloud3D::PointCloud3D ()
Standard constuctor.
Definition at line 31 of file PointCloud3D.cpp.
brics_3d::PointCloud3D::~PointCloud3D () [virtual]
Standard destructor.
Definition at line 42 of file PointCloud3D.cpp.
Member Function Documentation
void brics_3d::PointCloud3D::addPoint (Point3D point)
Add a point to the point cloud.
Parameters:
point Point that will be added
Definition at line 51 of file PointCloud3D.cpp.
Referenced by brics_3d::Octree::filter(), brics_3d::SimplePointCloudGeneratorCube::generatePointCloud(), brics_3d::operator>>(), brics_3d::Octree::partitionPointCloud(), and brics_3d::DepthImageToPointCloudTransformation::transformDepthImageToPointCloud().
void brics_3d::PointCloud3D::addPointPtr (Point3D * point)
Add a point to the point cloud with reference semantics.
Take this function to add complex/decorated point types.
Parameters:
point Pointer to the point. The point cloud will take over ownership for the pointer and take care about automatic deletion.
Definition at line 55 of file PointCloud3D.cpp.
Referenced by brics_3d::PCLTypecaster::convertToBRICS3DDataType(), brics_3d::RGBColorBasedEuclideanClustering::extractClusters(), brics_3d::EuclideanClustering::extractClusters(), brics_3d::ColorBasedROIExtractorHSV::filter(), and brics_3d::BoxROIExtractor::filter().
boost::ptr_vector< Point3D > * brics_3d::PointCloud3D::getPointCloud ()
Get the pointer to the point cloud.
Returns:
Pointer to point cloud
Definition at line 59 of file PointCloud3D.cpp.
Referenced by brics_3d::compute3DCentroid(), brics_3d::NormalEstimation::compute4DCentroid(), brics_3d::BoundingBox3DExtractor::computeBoundingBox(), brics_3d::Centroid3D::computeCentroid(), brics_3d::computeCovarianceMatrix(), brics_3d::NormalEstimation::computeFeature(), brics_3d::ObjectModelSphere::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLines::computeModelCoefficients(), brics_3d::ObjectModelPlaneFromLineAndPoint::computeModelCoefficients(), brics_3d::ObjectModelLine::computeModelCoefficients(), brics_3d::ObjectModelCylinder::computeModelCoefficients(), brics_3d::ObjectModelCircle::computeModelCoefficients(), brics_3d::PCA::computePrincipleComponents(), brics_3d::PCLTypecaster::convertToBRICS3DDataType(), brics_3d::PCLTypecaster::convertToPCLDataType(), brics_3d::PointCorrespondenceKDTree::createNearestNeighborCorrespondence(), brics_3d::PointCorrespondenceGenericNN::createNearestNeighborCorrespondence(), brics_3d::ObjectModelSphere::doSamplesVerifyModel(), brics_3d::ObjectModelPlane::doSamplesVerifyModel(), brics_3d::ObjectModelNormalPlane::doSamplesVerifyModel(), brics_3d::ObjectModelLine::doSamplesVerifyModel(), brics_3d::ObjectModelCylinder::doSamplesVerifyModel(), brics_3d::ObjectModelCircle::doSamplesVerifyModel(), brics_3d::RGBColorBasedEuclideanClustering::extractClusters(), brics_3d::EuclideanClustering::extractClusters(), brics_3d::Octree::filter(), brics_3d::ColorBasedROIExtractorHSV::filter(), brics_3d::BoxROIExtractor::filter(), brics_3d::ObjectModelSphere::getDistancesToModel(), brics_3d::ObjectModelPlane::getDistancesToModel(), brics_3d::ObjectModelNormalPlane::getDistancesToModel(), brics_3d::ObjectModelLine::getDistancesToModel(), brics_3d::ObjectModelCircle::getDistancesToModel(), brics_3d::ObjectModelSphere::getInlierDistance(), brics_3d::ObjectModelPlane::getInlierDistance(), brics_3d::ObjectModelNormalPlane::getInlierDistance(), brics_3d::ObjectModelLine::getInlierDistance(), brics_3d::ObjectModelCylinder::getInlierDistance(), brics_3d::ObjectModelCircle::getInlierDistance(), brics_3d::ObjectModelSphere::getSamples(), brics_3d::ObjectModelCircle::getSamples(), brics_3d::operator<<(), brics_3d::Octree::partitionPointCloud(), brics_3d::ObjectModelLine::projectPoints(), brics_3d::RGBColorBasedEuclideanClustering::segment(), brics_3d::ObjectModelSphere::selectWithinDistance(), brics_3d::ObjectModelPlane::selectWithinDistance(), brics_3d::ObjectModelLine::selectWithinDistance(), brics_3d::ObjectModelCylinder::selectWithinDistance(), brics_3d::ObjectModelCircle::selectWithinDistance(), brics_3d::NearestNeighborSTANN::setData(), brics_3d::NearestNeighborFLANN::setData(), brics_3d::NearestNeighborANN::setData(), and brics_3d::DelaunayTriangulationOSG::triangulate().
unsigned int brics_3d::PointCloud3D::getSize ()
Get the number of points in the point cloud.
Returns:
Size of point cloud (= number of stored points)
Definition at line 97 of file PointCloud3D.cpp.
Referenced by brics_3d::compute3DCentroid(), brics_3d::NormalEstimation::compute4DCentroid(), brics_3d::Centroid3D::computeCentroid(), brics_3d::computeCovarianceMatrix(), brics_3d::NormalEstimation::computeFeature(), brics_3d::ObjectModelCylinder::computeModelCoefficients(), brics_3d::PCLTypecaster::convertToPCLDataType(), brics_3d::PointCorrespondenceKDTree::createNearestNeighborCorrespondence(), brics_3d::PointCorrespondenceGenericNN::createNearestNeighborCorrespondence(), brics_3d::Octree::filter(), brics_3d::ColorBasedROIExtractorHSV::filter(), brics_3d::BoxROIExtractor::filter(), brics_3d::ObjectModelSphere::getDistancesToModel(), brics_3d::ObjectModelPlane::getDistancesToModel(), brics_3d::ObjectModelNormalPlane::getDistancesToModel(), brics_3d::ObjectModelLine::getDistancesToModel(), brics_3d::ObjectModelCircle::getDistancesToModel(), brics_3d::ObjectModelLine::getInlierDistance(), brics_3d::ObjectModelSphere::getSamples(), brics_3d::ObjectModelCylinder::getSamples(), brics_3d::ObjectModelCircle::getSamples(), brics_3d::RegionBasedSACSegmentationUsingNormals::initSACModel(), brics_3d::operator<<(), brics_3d::Octree::partitionPointCloud(), brics_3d::RGBColorBasedEuclideanClustering::segment(), brics_3d::ObjectModelSphere::selectWithinDistance(), brics_3d::ObjectModelPlane::selectWithinDistance(), brics_3d::ObjectModelLine::selectWithinDistance(), brics_3d::ObjectModelCylinder::selectWithinDistance(), brics_3d::ObjectModelCircle::selectWithinDistance(), brics_3d::NearestNeighborSTANN::setData(), brics_3d::NearestNeighborFLANN::setData(), brics_3d::NearestNeighborANN::setData(), and brics_3d::DepthImageToPointCloudTransformation::transformDepthImageToPointCloud().
void brics_3d::PointCloud3D::homogeneousTransformation (IHomogeneousMatrix44 * transformation)
Applies a homogeneous transformation to the point cloud.
Parameters:
[in] transformation The homogeneous transformation matrix that will be applied
Definition at line 198 of file PointCloud3D.cpp.
Referenced by brics_3d::IterativeClosestPoint::match(), and brics_3d::IterativeClosestPoint::performNextIteration().
void brics_3d::PointCloud3D::readFromTxtFile (std::string filename)
Reads data from a simple text file (x y z) and appends it to this point cloud.
Parameters:
filename Specifies the name of the file .e.g. point_cloud.txt
Definition at line 151 of file PointCloud3D.cpp.
void brics_3d::PointCloud3D::setPointCloud (boost::ptr_vector< Point3D > * pointCloud)
Set the pointer to the point cloud.
Parameters:
pointCloud Pointer to new point cloud
Definition at line 63 of file PointCloud3D.cpp.
void brics_3d::PointCloud3D::storeToPlyFile (std::string filename)
Stores the point cloud into a ply file (Stanford polygon file format)
Parameters:
filename Specifies the name of the file .e.g. point_cloud.ply
Definition at line 101 of file PointCloud3D.cpp.
void brics_3d::PointCloud3D::storeToTxtFile (std::string filename)
Stores the point cloud into a sipmle text file (x y z)
Parameters:
filename Specifies the name of the file .e.g. point_cloud.txt
Definition at line 137 of file PointCloud3D.cpp.
Friends And Related Function Documentation
ostream& operator<< (ostream & outStream, PointCloud3D & pointCloud) [friend]
Overridden << operator.
Writes a point cloud to a stream e.g. std::cout << pointCloudObj;
Parameters:
outStream The output stream
pointCloud Reference to point which data is forwarded to output stream
Returns:
Output stream
Definition at line 190 of file PointCloud3D.cpp.
istream& operator>> (istream & inStream, PointCloud3D & pointCloud) [friend]
Overridden >> operator.
Reads a point cloud from a stream an stores it. E.g. e.g. std::cin >> pointCloudObj;
Parameters:
inStream The input stream
pointCloud Reference to point where input is stored
Returns:
Input stream
Definition at line 174 of file PointCloud3D.cpp.
Member Data Documentation
boost::ptr_vector<Point3D>* brics_3d::PointCloud3D::pointCloud [protected]
Pointer to vector which represents a Cartesian point cloud.
Definition at line 141 of file PointCloud3D.h.
The documentation for this class was generated from the following files:
src/brics_3d/core/PointCloud3D.h
src/brics_3d/core/PointCloud3D.cpp