BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::ObjectModelNormalPlane Class Reference
brics_3d::ObjectModelNormalPlane Class Reference
Segmentation
#include <ObjectModelNormalPlane.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW ObjectModelNormalPlane ()
virtual ~ObjectModelNormalPlane ()
void setAxis (const Eigen::Vector3d &ax)
Set the axis along which we need to search for a plane perpendicular to.
void setEpsAngle (double ea)
Set the angle epsilon (delta) threshold.
void setDistanceFromOrigin (double d)
Set the distance we expect the plane to be from the origin.
double getDistanceFromOrigin ()
Get the distance of the plane from the origin.
void setEpsDist (double delta)
Set the distance epsilon (delta) threshold.
double getEpsDist ()
Get the distance epsilon (delta) threshold.
void getSamples (int &iterations, std::vector< int > &samples)
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXd &model_coefficients)
void optimizeModelCoefficients (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, Eigen::VectorXd &optimized_coefficients)
void getDistancesToModel (const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Compute all distances from the cloud data to a given model.
void selectWithinDistance (const Eigen::VectorXd &model_coefficients, double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
void getInlierDistance (std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, std::vector< double > &distances)
Select all the points which respect the given model coefficients as inliers.
void projectPoints (const std::vector< int > &inliers, const Eigen::VectorXd &model_coefficients, PointCloud3D *projectedPointCloud)
bool doSamplesVerifyModel (const std::set< int > &indices, const Eigen::VectorXd &model_coefficients, double threshold)
Verify whether a subset of indices verifies a given set of model coefficients.
void computeRandomModel (int &iterations, Eigen::VectorXd &model_coefficients, bool &isDegenerate, bool &modelFound)
Compute the model coefficients by generating some random samples.
int getNumberOfSamplesRequired ()
returns the minimum number of samples required for a object model generation
Private Attributes
Eigen::Vector4d axis
The axis along which we need to search for a plane perpendicular to.
double distanceFromOrigin
The distance from the template plane to the origin.
double epsAngle
The maximum allowed difference between the plane normal and the given axis.
double epsDistance
The maximum allowed deviation from the template distance from the origin.
Detailed Description
Note:
The implementation is reusing the object model implementation in ROS:PCl
Definition at line 33 of file ObjectModelNormalPlane.h.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW brics_3d::ObjectModelNormalPlane::ObjectModelNormalPlane () [inline]
Definition at line 54 of file ObjectModelNormalPlane.h.
virtual brics_3d::ObjectModelNormalPlane::~ObjectModelNormalPlane () [inline, virtual]
Definition at line 55 of file ObjectModelNormalPlane.h.
Member Function Documentation
bool brics_3d::ObjectModelNormalPlane::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXd & model_coefficients)
Definition at line 120 of file ObjectModelNormalPlane.cpp.
Referenced by computeRandomModel().
home alexey workspace BRICS_3d src brics_3d algorithm segmentation objectModels ObjectModelNormalPlane cpp void brics_3d::ObjectModelNormalPlane::computeRandomModel (int & iterations, Eigen::VectorXd & model_coefficients, bool & isDegenerate, bool & modelFound) [virtual]
Compute the model coefficients by generating some random samples.
Parameters:
model_coefficients,: the computed model coefficients
isDegenerate,: Whether degenerate samples are found from the input pointcloud or not
modelFound,: Whether a valid model is found from the sample or not
Implements brics_3d::IObjectModel.
Definition at line 25 of file ObjectModelNormalPlane.cpp.
References computeModelCoefficients(), and getSamples().
bool brics_3d::ObjectModelNormalPlane::doSamplesVerifyModel (const std::set< int > & indices, const Eigen::VectorXd & model_coefficients, double threshold) [virtual]
Verify whether a subset of indices verifies a given set of model coefficients.
Pure virtual.
Parameters:
indices the data indices that need to be tested against the model
model_coefficients the set of model coefficients
threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements brics_3d::IObjectModel.
Definition at line 182 of file ObjectModelNormalPlane.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
double brics_3d::ObjectModelNormalPlane::getDistanceFromOrigin () [inline]
Get the distance of the plane from the origin.
Definition at line 93 of file ObjectModelNormalPlane.h.
References distanceFromOrigin.
void brics_3d::ObjectModelNormalPlane::getDistancesToModel (const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Compute all distances from the cloud data to a given model.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
distances the resultant estimated distances
Implements brics_3d::IObjectModel.
Definition at line 264 of file ObjectModelNormalPlane.cpp.
References distanceFromOrigin, epsAngle, epsDistance, brics_3d::IObjectModel::getAngle3D(), brics_3d::NormalSet3D::getNormals(), brics_3d::PointCloud3D::getPointCloud(), brics_3d::PointCloud3D::getSize(), brics_3d::NormalSet3D::getSize(), brics_3d::IObjectModel::inputPointCloud, brics_3d::IObjectModelUsingNormals::normalDistanceWeight, and brics_3d::IObjectModelUsingNormals::normals.
double brics_3d::ObjectModelNormalPlane::getEpsDist () [inline]
Get the distance epsilon (delta) threshold.
Definition at line 110 of file ObjectModelNormalPlane.h.
References epsDistance.
void brics_3d::ObjectModelNormalPlane::getInlierDistance (std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, std::vector< double > & distances) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
distances of inliers from the model
Implements brics_3d::IObjectModel.
Definition at line 163 of file ObjectModelNormalPlane.cpp.
References brics_3d::PointCloud3D::getPointCloud(), and brics_3d::IObjectModel::inputPointCloud.
int brics_3d::ObjectModelNormalPlane::getNumberOfSamplesRequired () [inline, virtual]
returns the minimum number of samples required for a object model generation
Implements brics_3d::IObjectModel.
Definition at line 131 of file ObjectModelNormalPlane.h.
void brics_3d::ObjectModelNormalPlane::getSamples (int & iterations, std::vector< int > & samples)
Definition at line 51 of file ObjectModelNormalPlane.cpp.
Referenced by computeRandomModel().
void brics_3d::ObjectModelNormalPlane::optimizeModelCoefficients (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, Eigen::VectorXd & optimized_coefficients)
void brics_3d::ObjectModelNormalPlane::projectPoints (const std::vector< int > & inliers, const Eigen::VectorXd & model_coefficients, PointCloud3D * projectedPointCloud)
void brics_3d::ObjectModelNormalPlane::selectWithinDistance (const Eigen::VectorXd & model_coefficients, double threshold, std::vector< int > & inliers) [virtual]
Select all the points which respect the given model coefficients as inliers.
Pure virtual.
Parameters:
model_coefficients the coefficients of a model that we need to compute distances to
threshold a maximum admissible distance threshold for determining the inliers from the outliers
inliers the resultant model inliers
Implements brics_3d::IObjectModel.
Definition at line 199 of file ObjectModelNormalPlane.cpp.
void brics_3d::ObjectModelNormalPlane::setAxis (const Eigen::Vector3d & ax) [inline]
Set the axis along which we need to search for a plane perpendicular to.
Parameters:
ax the axis along which we need to search for a plane perpendicular to
Reimplemented from brics_3d::IObjectModelUsingNormals.
Definition at line 61 of file ObjectModelNormalPlane.h.
void brics_3d::ObjectModelNormalPlane::setDistanceFromOrigin (double d) [inline]
Set the distance we expect the plane to be from the origin.
Parameters:
d distance from the template plane to the origin
Definition at line 85 of file ObjectModelNormalPlane.h.
References distanceFromOrigin.
void brics_3d::ObjectModelNormalPlane::setEpsAngle (double ea) [inline]
Set the angle epsilon (delta) threshold.
Parameters:
ea the maximum allowed difference between the plane normal and the given axis.
Reimplemented from brics_3d::IObjectModelUsingNormals.
Definition at line 76 of file ObjectModelNormalPlane.h.
References epsAngle.
void brics_3d::ObjectModelNormalPlane::setEpsDist (double delta) [inline]
Set the distance epsilon (delta) threshold.
Parameters:
delta the maximum allowed deviation from the template distance from the origin
Definition at line 103 of file ObjectModelNormalPlane.h.
References epsDistance.
Member Data Documentation
Eigen::Vector4d brics_3d::ObjectModelNormalPlane::axis [private]
The axis along which we need to search for a plane perpendicular to.
Reimplemented from brics_3d::IObjectModelUsingNormals.
Definition at line 38 of file ObjectModelNormalPlane.h.
double brics_3d::ObjectModelNormalPlane::distanceFromOrigin [private]
The distance from the template plane to the origin.
Definition at line 41 of file ObjectModelNormalPlane.h.
Referenced by getDistanceFromOrigin(), getDistancesToModel(), and setDistanceFromOrigin().
double brics_3d::ObjectModelNormalPlane::epsAngle [private]
The maximum allowed difference between the plane normal and the given axis.
Reimplemented from brics_3d::IObjectModelUsingNormals.
Definition at line 44 of file ObjectModelNormalPlane.h.
Referenced by getDistancesToModel(), and setEpsAngle().
double brics_3d::ObjectModelNormalPlane::epsDistance [private]
The maximum allowed deviation from the template distance from the origin.
Definition at line 47 of file ObjectModelNormalPlane.h.
Referenced by getDistancesToModel(), getEpsDist(), and setEpsDist().
The documentation for this class was generated from the following files:
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelNormalPlane.h
src/brics_3d/algorithm/segmentation/objectModels/ObjectModelNormalPlane.cpp