BRICS_RN (Robust Navigation Library): Twist2D Class Reference
Twist2D Class Reference
Class represents twist 2D data.
#include <Twist2D.h>
Public Member Functions
Twist2D ()
Constructor.
Twist2D (float x, float y, float theta)
Constructor.
Twist2D (const Twist2D &orig)
Copy constructor.
const Twist2D & operator= (const Twist2D &orig)
Assignment operation.
virtual ~Twist2D ()
Destructor.
float getX () const
Getting x coordinate.
void setX (float x)
Setting x coordinate.
float getY () const
Getting y coordinate.
void setY (float y)
Setting y coordinate.
float getTheta () const
Getting theta coordinate.
void setTheta (float theta)
Setting theta coordinate.
Private Attributes
float x
x coordinate
float y
y coordinate
float theta
theta coordinate
Friends
Twist2D operator+ (const Twist2D &op1, const Twist2D &op2)
Summation.
Detailed Description
Class represents twist 2D data.
Definition at line 47 of file Twist2D.h.
Constructor & Destructor Documentation
Twist2D::Twist2D ()
Constructor.
Definition at line 42 of file Twist2D.cpp.
Twist2D::Twist2D (float x, float y, float theta)
Constructor.
Parameters
[in] x - coordinate
[in] y - coordinate
[in] theta - angle
Definition at line 46 of file Twist2D.cpp.
Twist2D::Twist2D (const Twist2D & orig)
Copy constructor.
Definition at line 49 of file Twist2D.cpp.
Twist2D::~Twist2D () virtual
Destructor.
Definition at line 52 of file Twist2D.cpp.
Member Function Documentation
float Twist2D::getTheta () const
Getting theta coordinate.
Definition at line 78 of file Twist2D.cpp.
References theta.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator+(), operator=(), twist2dToTwistKdl(), and twist2dToTwistRos().
float Twist2D::getX () const
Getting x coordinate.
Definition at line 62 of file Twist2D.cpp.
References x.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator+(), operator=(), twist2dToTwistKdl(), and twist2dToTwistRos().
float Twist2D::getY () const
Getting y coordinate.
Definition at line 70 of file Twist2D.cpp.
References y.
Referenced by OmniDrivePositionController::computeNewOdometry(), OmniDriveKinematicsModel::convertToGlobalReferenceFrame(), OmniDriveKinematicsModel::convertToLocalReferenceFrame(), operator+(), operator=(), twist2dToTwistKdl(), and twist2dToTwistRos().
const Twist2D & Twist2D::operator= (const Twist2D & orig)
Assignment operation.
Definition at line 55 of file Twist2D.cpp.
References getTheta(), getX(), getY(), theta, x, and y.
void Twist2D::setTheta (float theta)
Setting theta coordinate.
Definition at line 82 of file Twist2D.cpp.
References theta.
void Twist2D::setX (float x)
Setting x coordinate.
Definition at line 66 of file Twist2D.cpp.
void Twist2D::setY (float y)
Setting y coordinate.
Definition at line 74 of file Twist2D.cpp.
Friends And Related Function Documentation
Twist2D operator+ (const Twist2D & op1, const Twist2D & op2) friend
Summation.
Definition at line 86 of file Twist2D.cpp.
Member Data Documentation
float Twist2D::theta private
theta coordinate
Definition at line 128 of file Twist2D.h.
Referenced by getTheta(), operator=(), and setTheta().
float Twist2D::x private
x coordinate
Definition at line 118 of file Twist2D.h.
Referenced by getX(), and operator=().
float Twist2D::y private
y coordinate
Definition at line 123 of file Twist2D.h.
Referenced by getY(), and operator=().
The documentation for this class was generated from the following files:
navigation_trajectory_follower/src/omnidrive_controller/Twist2D.h
navigation_trajectory_follower/src/omnidrive_controller/Twist2D.cpp