BRICS_RN (Robust Navigation Library): OmniDriveTrajectoryGenerator Class Reference
OmniDriveTrajectoryGenerator Class Reference
Implementation of the interface class for trajectory generation for omnidrive mobile base.
#include <OmniDriveTrajectoryGenerator.h>
Public Member Functions
OmniDriveTrajectoryGenerator ()
Constructor.
OmniDriveTrajectoryGenerator (const OmniDriveTrajectoryGenerator &orig)
Copy constructor.
virtual ~OmniDriveTrajectoryGenerator ()
Destructor.
float getShortestAngle (float goalAngle, float actualAngle)
Computes shortest angle.
void computePathComposite (const std::vector< FrameWithId > &path, KDL::Path_Composite &pathComposite)
Converts vector of FrameWithId to KDL::Path_Composite.
void interpolateRotation (const std::vector< FrameWithId > &path, std::vector< FrameWithId > &pathWithRotation)
Calculates rotation.
void computeTrajectroy (const KDL::Path_Composite &path, KDL::Trajectory_Composite &trajectory)
Implementation if an interface for computing a trajectory.
void computeTrajectroy (const std::vector< FrameWithId > path, KDL::Trajectory_Composite &trajectory)
Computes trajectory given a path as a vector of FrameWithId.
Detailed Description
Implementation of the interface class for trajectory generation for omnidrive mobile base.
Definition at line 56 of file OmniDriveTrajectoryGenerator.h.
Constructor & Destructor Documentation
OmniDriveTrajectoryGenerator::OmniDriveTrajectoryGenerator ()
Constructor.
Definition at line 56 of file OmniDriveTrajectoryGenerator.cpp.
OmniDriveTrajectoryGenerator::OmniDriveTrajectoryGenerator (const OmniDriveTrajectoryGenerator & orig)
Copy constructor.
Definition at line 59 of file OmniDriveTrajectoryGenerator.cpp.
OmniDriveTrajectoryGenerator::~OmniDriveTrajectoryGenerator () virtual
Destructor.
Definition at line 62 of file OmniDriveTrajectoryGenerator.cpp.
Member Function Documentation
void OmniDriveTrajectoryGenerator::computePathComposite (const std::vector< FrameWithId > & path, KDL::Path_Composite & pathComposite)
Converts vector of FrameWithId to KDL::Path_Composite.
Parameters
[in] path - input path as a vector of FrameWithId.
[out] pathComposite - converted path to KDL::Path_Composite.
Definition at line 69 of file OmniDriveTrajectoryGenerator.cpp.
References FrameWithId::getFrame().
Referenced by computeTrajectroy().
void OmniDriveTrajectoryGenerator::computeTrajectroy (const KDL::Path_Composite & path, KDL::Trajectory_Composite & trajectory) virtual
Implementation if an interface for computing a trajectory.
Parameters
[in] path - input path, KDL::Path_Composite
[out] trajectory - computed trajectory
Implements ITrajectoryGenerator.
Definition at line 129 of file OmniDriveTrajectoryGenerator.cpp.
References path.
Referenced by computeTrajectroy(), and pathCallback().
void OmniDriveTrajectoryGenerator::computeTrajectroy (const std::vector< FrameWithId > path, KDL::Trajectory_Composite & trajectory)
Computes trajectory given a path as a vector of FrameWithId.
Parameters
[in] path - input path, a vector of FrameWithId
[out] trajectory - computed trajectory
Definition at line 145 of file OmniDriveTrajectoryGenerator.cpp.
References computePathComposite(), computeTrajectroy(), and interpolateRotation().
float OmniDriveTrajectoryGenerator::getShortestAngle (float goalAngle, float actualAngle)
Computes shortest angle.
Parameters
[in] goalAngle - 1st angle.
[in] actualAngle - 2nd angle.
Returns
shortest angle
Definition at line 65 of file OmniDriveTrajectoryGenerator.cpp.
Referenced by interpolateRotation().
void OmniDriveTrajectoryGenerator::interpolateRotation (const std::vector< FrameWithId > & path, std::vector< FrameWithId > & pathWithRotation)
Calculates rotation.
Parameters
[in] path - input path as a vector of FrameWithId
[out] pathWithRotation - output path with orientation in each path point.
Definition at line 95 of file OmniDriveTrajectoryGenerator.cpp.
References getShortestAngle().
Referenced by computeTrajectroy().
The documentation for this class was generated from the following files:
navigation_trajectory_follower/src/trajectory_generator/OmniDriveTrajectoryGenerator.h
navigation_trajectory_follower/src/trajectory_generator/OmniDriveTrajectoryGenerator.cpp