BRICS_RN_Robust_Navigation_Library(BRICS_RN): LinearInterpolation Class Reference
LinearInterpolation Class Reference
Implementation of the interface class for path interpolation algorithms, linear path interpolation algorithm.
#include <LinearInterpolation.h>
Public Member Functions
LinearInterpolation ()
Constructor.
LinearInterpolation (const LinearInterpolation &orig)
Copy constructor.
virtual ~LinearInterpolation ()
Destructor.
size_t interpolate (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out, double step, size_t numberOfSteps)
An interface for linear path approximation algorithms.
Private Member Functions
size_t linearInterpolation (const std::vector< FrameWithId > &in, std::vector< FrameWithId > &out, double step, size_t numberOfsteps)
An implementation of the linear path approximation algorithms.
Detailed Description
Implementation of the interface class for path interpolation algorithms, linear path interpolation algorithm.
Definition at line 50 of file LinearInterpolation.h.
Constructor & Destructor Documentation
LinearInterpolation::LinearInterpolation ()
Constructor.
Definition at line 51 of file LinearInterpolation.cpp.
LinearInterpolation::LinearInterpolation (const LinearInterpolation & orig)
Copy constructor.
Definition at line 55 of file LinearInterpolation.cpp.
LinearInterpolation::~LinearInterpolation () virtual
Destructor.
Definition at line 59 of file LinearInterpolation.cpp.
Member Function Documentation
size_t LinearInterpolation::interpolate (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out, double step, size_t numberOfSteps = 0) virtual
An interface for linear path approximation algorithms.
Parameters
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting interpolated path.
step - step size.
numberOfSteps - number of steps.
Implements IPathInterpolation.
Definition at line 63 of file LinearInterpolation.cpp.
References Stopwatch::getElapsedTime(), linearInterpolation(), LOG, Stopwatch::start(), and Stopwatch::stop().
Referenced by CollisionCheckingRos::collisionCheck().
size_t LinearInterpolation::linearInterpolation (const std::vector< FrameWithId > & in, std::vector< FrameWithId > & out, double step, size_t numberOfsteps = 0) private
An implementation of the linear path approximation algorithms.
Parameters
[in] in - std::vector <FrameWithId> input path.
[out] out - std::vector <FrameWithId> resulting interpolated path.
step - step size.
numberOfSteps - number of steps.
Definition at line 84 of file LinearInterpolation.cpp.
References LOG.
Referenced by interpolate().
The documentation for this class was generated from the following files:
navigation_trajectory_planner/include/navigation_trajectory_planner/LinearInterpolation.h
navigation_trajectory_planner/src/LinearInterpolation.cpp