BRICS_3D_Perception_and_Modeling_Library(BRICS_3D): brics_3d::PointCloud3DIterator Class Reference
brics_3d::PointCloud3DIterator Class Reference
Point iterator implementation for brics_3d::PointCloud3D.
#include <PointCloud3DIterator.h>
Public Member Functions
PointCloud3DIterator ()
Standard constructor.
virtual ~PointCloud3DIterator ()
Standard destructor.
void begin ()
Set the iterator to the begining of the point set.
void next ()
Advance to the next point.
bool end ()
Check whether the end has been reached or not.
virtual Coordinate getX ()
Get the x coordiante of the point.
virtual Coordinate getY ()
Get the y coordiante of the point.
virtual Coordinate getZ ()
Get the z coordiante of the point.
virtual Point3D * getRawData ()
Get the unmodified data (including x,y,z) from the ith point in the iteration.
void insert (PointCloud3D::PointCloud3DPtr pointCloud, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr associatedTransform)
Add a point cloud with its associated transform.
Protected Attributes
std::map
< PointCloud3D::PointCloud3DPtr,
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr > pointCloudsWithTransforms
The stored pointers to the point clouds with associated transforms.
std::map
< PointCloud3D::PointCloud3DPtr,
IHomogeneousMatrix44::IHomogeneousMatrix44Ptr >
::iterator pointCloudsIterator
Internal outer iteration handle.
unsigned int index
Internal inner iteration handle.
Point3D * currentTransformedPoint
The cached data.
Detailed Description
Point iterator implementation for brics_3d::PointCloud3D.
The PointCloud3DIterator can hold a list of point clouds with associated rigid transforms. While iterating and invocing getX(), getY() or getZ() the points will be multiplied with this is respective transforms. The raw data in the point clouds remains unmodified and could be accessed via the getRawData function.
        PointCloud3D::PointCloud3DPtr cloud1(new PointCloud3D());
        cloud1->addPoint(Point3D(1,2,3));
        cloud1->addPoint(Point3D(4,5,6));
        cloud1->addPoint(Point3D(7,8,9));
        PointCloud3DIterator* it = new PointCloud3DIterator();
        IHomogeneousMatrix44::IHomogeneousMatrix44Ptr shift100 (new HomogeneousMatrix44 (1,0,0, 0,1,0, 0,0,1, 100, 100, 100));
        it->insert(cloud1, shift100);
        for (it->begin(); !it->end(); it->next()){
                it->getX(); //transformed data (by "shift100")
                it->getY(); //transformed data (by "shift100")
                it->getZ(); //transformed data (by "shift100")
                Point3D* tmpPoint = it->getRawData();
                tmpPoint->getX(); // original data
                tmpPoint->getY(); // original data
                tmpPoint->getZ(); // original data
        }
        delete it;
Definition at line 61 of file PointCloud3DIterator.h.
Constructor & Destructor Documentation
home alexey workspace BRICS_3d src brics_3d core PointCloud3DIterator cpp brics_3d::PointCloud3DIterator::PointCloud3DIterator ()
Standard constructor.
Definition at line 26 of file PointCloud3DIterator.cpp.
brics_3d::PointCloud3DIterator::~PointCloud3DIterator () [virtual]
Standard destructor.
Definition at line 31 of file PointCloud3DIterator.cpp.
Member Function Documentation
void brics_3d::PointCloud3DIterator::begin () [virtual]
Set the iterator to the begining of the point set.
Implements brics_3d::IPoint3DIterator.
Definition at line 35 of file PointCloud3DIterator.cpp.
References currentTransformedPoint, brics_3d::Point3D::homogeneousTransformation(), index, and pointCloudsIterator.
bool brics_3d::PointCloud3DIterator::end () [virtual]
Check whether the end has been reached or not.
The "end" itself is not a valid element it self.
Returns:
True if end has been reached.
Implements brics_3d::IPoint3DIterator.
Definition at line 80 of file PointCloud3DIterator.cpp.
Referenced by next().
Point3D * brics_3d::PointCloud3DIterator::getRawData () [virtual]
Get the unmodified data (including x,y,z) from the ith point in the iteration.
Returns:
Pointer to the original point data. This will give acces to potential data in the decoration layers. cf. brics_3d::Point3DDecorator
Implements brics_3d::IPoint3DIterator.
Definition at line 99 of file PointCloud3DIterator.cpp.
Coordinate brics_3d::PointCloud3DIterator::getX () [virtual]
Get the x coordiante of the point.
This value might be transformed/modified depending the the iterator implementation.
Implements brics_3d::IPoint3DIterator.
Definition at line 87 of file PointCloud3DIterator.cpp.
Coordinate brics_3d::PointCloud3DIterator::getY () [virtual]
Get the y coordiante of the point.
This value might be transformed/modified depending the the iterator implementation.
Implements brics_3d::IPoint3DIterator.
Definition at line 91 of file PointCloud3DIterator.cpp.
Coordinate brics_3d::PointCloud3DIterator::getZ () [virtual]
Get the z coordiante of the point.
This value might be transformed/modified depending the the iterator implementation.
Implements brics_3d::IPoint3DIterator.
Definition at line 95 of file PointCloud3DIterator.cpp.
void brics_3d::PointCloud3DIterator::insert (PointCloud3D::PointCloud3DPtr pointCloud, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr associatedTransform)
Add a point cloud with its associated transform.
Parameters:
pointCloud The pont cloud to be added.
associatedTransform Transform theat will be automatically applied to all points od that point cloud when calling getX(), getY() or getZ().
Definition at line 103 of file PointCloud3DIterator.cpp.
Referenced by brics_3d::rsg::PointCloudAccumulator::visit().
void brics_3d::PointCloud3DIterator::next () [virtual]
Advance to the next point.
Implements brics_3d::IPoint3DIterator.
Definition at line 51 of file PointCloud3DIterator.cpp.
References currentTransformedPoint, end(), brics_3d::Point3D::homogeneousTransformation(), index, and pointCloudsIterator.
Member Data Documentation
Point3D* brics_3d::PointCloud3DIterator::currentTransformedPoint [protected]
The cached data.
Definition at line 112 of file PointCloud3DIterator.h.
Referenced by begin(), and next().
unsigned int brics_3d::PointCloud3DIterator::index [protected]
Internal inner iteration handle.
Definition at line 109 of file PointCloud3DIterator.h.
Referenced by begin(), and next().
std::map<PointCloud3D::PointCloud3DPtr, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr>::iterator brics_3d::PointCloud3DIterator::pointCloudsIterator [protected]
Internal outer iteration handle.
Definition at line 105 of file PointCloud3DIterator.h.
Referenced by begin(), and next().
std::map<PointCloud3D::PointCloud3DPtr, IHomogeneousMatrix44::IHomogeneousMatrix44Ptr> brics_3d::PointCloud3DIterator::pointCloudsWithTransforms [protected]
The stored pointers to the point clouds with associated transforms.
Destruction of the iterator will not delete the pointers.
Definition at line 100 of file PointCloud3DIterator.h.
The documentation for this class was generated from the following files:
src/brics_3d/core/PointCloud3DIterator.h
src/brics_3d/core/PointCloud3DIterator.cpp