BRICS_RN_Robust_Navigation_Library(BRICS_RN): navigation_trajectory_follower/src/omnidrive_controller/ConversionUtils.h File Reference
navigation_trajectory_follower/src/omnidrive_controller/ConversionUtils.h File Reference
#include "Pose2D.h"
#include "Twist2D.h"
#include "kdl/frames.hpp"
Functions
void pose2dToFrameKdl (const Pose2D &pose2d, KDL::Frame &pose)
void twist2dToTwistKdl (const Twist2D &twist2d, KDL::Twist &twist)
Function Documentation
void pose2dToFrameKdl (const Pose2D & pose2d, KDL::Frame & pose)
Definition at line 48 of file ConversionUtils.h.
References Pose2D::getTheta(), Pose2D::getX(), and Pose2D::getY().
void twist2dToTwistKdl (const Twist2D & twist2d, KDL::Twist & twist)
Definition at line 52 of file ConversionUtils.h.
References Twist2D::getTheta(), Twist2D::getX(), and Twist2D::getY().