BRICS_RN (Robust Navigation Library): conversions Namespace Reference
conversions Namespace Reference
Conversions between ROS, BRICS_RN and KDL data types.
Functions
void odometryRosToFrame (const nav_msgs::Odometry &odometry, FrameWithId &pose)
Conversion from nav_msgs::Odometry ROS message to FrameWithId data type (only pose is converted).
void odometryRosToTwist (const nav_msgs::Odometry &odometry, TwistWithId &twist)
Conversion from nav_msgs::Odometry ROS message to TwistWithId data type (only twist is converted).
void twistRosToTwist2d (const geometry_msgs::Twist &twist, Twist2D &twist2d)
Conversion from geometry_msgs::Twist ROS message to Twist2D data type.
void twist2dToTwistRos (const Twist2D &twist2d, geometry_msgs::Twist &twist)
Conversion from Twist2D data type to geometry_msgs::Twist ROS message.
void poseRosToFrameKdl (const geometry_msgs::Pose &poseRos, KDL::Frame &frame)
Conversion from geometry_msgs::Pose ROS message to KDL::Frame data type.
void poseRosToFrame (const geometry_msgs::Pose &poseRos, const std::string &id, FrameWithId &pose)
Conversion from geometry_msgs::Pose ROS message to FrameWithId data type.
void poseStampedRosToFrame (const geometry_msgs::PoseStamped &poseStamped, FrameWithId &pose)
Conversion from geometry_msgs::PoseStamped ROS message to FrameWithId data type.
void poseRosToPose2d (const geometry_msgs::Pose &pose, Pose2D &pose2d)
Conversion from geometry_msgs::Pose ROS message to Pose2D data type.
void frameKdlToPoseRos (const KDL::Frame &frame, geometry_msgs::Pose &poseRos)
Conversion from KDL::Frame data type to geometry_msgs::Pose ROS message.
void frameToPoseRos (const FrameWithId &pose, geometry_msgs::Pose &poseRos, std::string &id)
Conversion from FrameWithId data type to geometry_msgs::Pose ROS message.
void frameToPoseStampedRos (const FrameWithId &pose, geometry_msgs::PoseStamped &poseStamped)
Conversion from FrameWithId data type to geometry_msgs::PoseStamped ROS message.
void pose2dToPoseRos (const Pose2D &pose2d, geometry_msgs::Pose &pose)
Conversion from Pose2D type to geometry_msgs::Pose ROS message.
void pathToPathRos (const std::vector< FrameWithId > &path, std::vector< geometry_msgs::PoseStamped > &pathRos)
Conversion of a FrameWithId vector (a path) to vector of geometry_msgs::PoseStamped ROS messages.
void pathToPathRos (const std::vector< FrameWithId > &path, nav_msgs::Path &pathRos)
Conversion of a FrameWithId vector (a path) to nav_msgs::Path ROS message.
void pathRosToPath (const std::vector< geometry_msgs::PoseStamped > &pathRos, std::vector< FrameWithId > &path)
Conversion of a geometry_msgs::PoseStamped vector to FrameWithId vector (a path).
void pathRosToPath (const nav_msgs::Path &pathRos, std::vector< FrameWithId > &path)
Conversion of a nav_msgs::Path ROS message to FrameWithId vector (a path).
void pose2dToFrameKdl (const Pose2D &pose2d, KDL::Frame &pose)
Conversion of a Pose2D to a KDL::Frame.
void twist2dToTwistKdl (const Twist2D &twist2d, KDL::Twist &twist)
Conversion from Twist2D data type to KDL::Twist.
void pathRosToPathKdl (const nav_msgs::Path &pathRos, double eqradius, KDL::Path_Composite &path)
Conversion of a nav_msgs::Path ROS message to KDL::Path_Composite KDL path data type.
void pathToPathKdl (const std::vector< FrameWithId > &path, double eqradius, KDL::Path_Composite &pathKDL)
Conversion of a std::vector<FrameWithId> to KDL::Path_Composite KDL path data type.
void trajectoryKdlToRosKdlStream (const KDL::Trajectory_Composite &trajectory, navigation_trajectory_common::KdlStream &trajectoryMsg)
Conversion of a KDL::Trajectory_Composite to a ROS message.
void rosKdlStreamToTrajectoryKdl (const navigation_trajectory_common::KdlStream &trajectoryMsg, KDL::Trajectory_Composite &trajectory)
Conversion of a ROS KdlStream message to a KDL::Trajectory_Composite.
Detailed Description
Conversions between ROS, BRICS_RN and KDL data types.
Function Documentation
void conversions::frameKdlToPoseRos (const KDL::Frame & frame, geometry_msgs::Pose & poseRos) inline
Conversion from KDL::Frame data type to geometry_msgs::Pose ROS message.
Convert the KDL::Frame instance to a ROS geometry_msgs::Pose instance.
Parameters
[in] KDL::Frame - input frame, i.e. location and orientation.
[out] geometry_msgs::Pose - converted pose to a ROS message .
Definition at line 199 of file Conversions.h.
Referenced by frameToPoseRos().
void conversions::frameToPoseRos (const FrameWithId & pose, geometry_msgs::Pose & poseRos, std::string & id) inline
Conversion from FrameWithId data type to geometry_msgs::Pose ROS message.
Convert the FrameWithID instance to a ROS geometry_msgs::Pose instance and return the ID of the FrameWithId as a separate result parameter. Uses frameKdlToPoseRos().
Parameters
[in] FrameWithId - input frame, including frame id, location and orientation.
[out] geometry_msgs::Pose - converted pose to a ROS message .
[out] FrameWithId - converted id.
Definition at line 220 of file Conversions.h.
References frameKdlToPoseRos(), FrameWithId::getFrame(), and FrameWithId::id.
Referenced by frameToPoseStampedRos().
void conversions::frameToPoseStampedRos (const FrameWithId & pose, geometry_msgs::PoseStamped & poseStamped) inline
Conversion from FrameWithId data type to geometry_msgs::PoseStamped ROS message.
Convert the FrameWithID instance to a ROS geometry_msgs::PoseStamped instance. The FrameWithId::id member is copied to geometry_msgs::PoseStamped::header::frame_id. This uses frameToPoseRos().
Parameters
[in] FrameWithId - input frame, including frame id, location and orientation.
[out] geometry_msgs::PoseStamped - converted pose and frame id to a ROS message.
Definition at line 235 of file Conversions.h.
References frameToPoseRos().
Referenced by CollisionCheckingRos::collisionCheck(), PathPlannerRos::computePath(), and pathToPathRos().
void conversions::odometryRosToFrame (const nav_msgs::Odometry & odometry, FrameWithId & pose) inline
Conversion from nav_msgs::Odometry ROS message to FrameWithId data type (only pose is converted).
Convert the nav_msgs::Odometry::pose::pose member in a KDL::Frame instance and return the KDL::Frame wrapped in side a FrameWithID instance. The FrameWithId::id member is set to the nav_msgs::Odometry::header::frame_id value.
Parameters
[in] nav_msgs::Odometry - odometry ROS message.
[out] FrameWithId - converted pose from the odometry message.
Definition at line 74 of file Conversions.h.
References FrameWithId::getFrame(), and FrameWithId::id.
Referenced by odometryCallback().
void conversions::odometryRosToTwist (const nav_msgs::Odometry & odometry, TwistWithId & twist) inline
Conversion from nav_msgs::Odometry ROS message to TwistWithId data type (only twist is converted).
Convert the nav_msgs::Odometry::twist::twist member in two KDL::Twist instance and return the KDL::Twist wrapped in side a TwistWithID instance. The TwistWithId::id member is set to the nav_msgs::Odometry::header::frame_id value.
Parameters
[in] nav_msgs::Odometry - odometry ROS message.
[out] TwistWithId - converted twist from the odometry message.
Definition at line 93 of file Conversions.h.
References TwistWithId::getTwist(), and TwistWithId::id.
Referenced by odometryCallback().
void conversions::pathRosToPath (const std::vector< geometry_msgs::PoseStamped > & pathRos, std::vector< FrameWithId > & path) inline
Conversion of a geometry_msgs::PoseStamped vector to FrameWithId vector (a path).
See poseStampedRosToFrame() for details of the conversion process.
Parameters
[in] std::vector<geometry_msgs::PoseStamped> - input path.
[out] std::vector<FrameWithId> - result of conversion.
Definition at line 300 of file Conversions.h.
References poseStampedRosToFrame().
Referenced by PathPlannerRos::computePath(), pathCallback(), and pathRosToPath().
void conversions::pathRosToPath (const nav_msgs::Path & pathRos, std::vector< FrameWithId > & path) inline
Conversion of a nav_msgs::Path ROS message to FrameWithId vector (a path).
See poseStampedRosToFrame() for details of the conversion process.
Parameters
[in] nav_msgs::Path - input path.
[out] std::vector<FrameWithId> - result of conversion.
Definition at line 320 of file Conversions.h.
References pathRosToPath().
void conversions::pathRosToPathKdl (const nav_msgs::Path & pathRos, double eqradius, KDL::Path_Composite & path) inline
Conversion of a nav_msgs::Path ROS message to KDL::Path_Composite KDL path data type.
This function convertes an arbitrary ROS path (composed of poses, i.e. positions with associated orientations) to a KDL path. The ROS path can be any mixture of transaltional, rotational or compbined translational-roatational segments. Path segments that rotate on the spot are supported.
The parameter eqradius assigns rotational motions a "length". To be able to traverse the path, we need a way to parametrize the whole motion, translational and rotational combined as a 3D curve in the space of translation and orientation (x,y,theta), by a single monotonic parameter s, the generalized curve length. For purely translational motion, this is just the euclidian length of the path segment. For rotational motion, the change in orientation is translated in a curve length by taking the length of an arc spanning the angular change in orientation on a circle of radius eqradius. For a segment describing a simultaneous translation and rotation, the longer of the pure translational curve length and the rotational cureve length is taken, i.e. we do not calculate the true path integral.
Good values for eqradius depend on the intended use of the constructed path and possible on the kinematic constraints of the vehicle later executing the path. As a rule of thumb:
if you want to later (re)sample the path with an euclidian step size es and an angular step size of as, set eqradius such that as given an arc length of es: eq = es / as.
similar, if you know the maximum rotational and translational velocities of the vehicle, make the arc length at maximum turn rate tr in a time step match the translation distance at maximum speed ms in a time step: eq = ms / tr.
If no better information is available, try 0.5, matching 0.1 meter with roughly 10 degree.
Parameters
[in] nav_msgs::Path - input path.
[in] double eqradius - equivalence radius for rotational components, see details.
[out] KDL::Path_Composite - result of conversion.
Definition at line 388 of file Conversions.h.
References poseRosToFrameKdl().
Referenced by pathCallback().
void conversions::pathToPathKdl (const std::vector< FrameWithId > & path, double eqradius, KDL::Path_Composite & pathKDL) inline
Conversion of a std::vector<FrameWithId> to KDL::Path_Composite KDL path data type.
This function convertes an arbitrary path (composed of Frames, i.e. positions with associated orientations) to a KDL path. The path can be any mixture of transaltional, rotational or compbined translational-roatational segments. Path segments that rotate on the spot are supported.
The parameter eqradius assigns rotational motions a "length". See detailed description of pathRosToPathKdl() for in-depth discussion of this parameter.
Parameters
[in] nav_msgs::Path - input path.
[in] double eqradius - equivalence radius for rotational components, see details.
[out] KDL::Path_Composite - result of conversion.
Definition at line 437 of file Conversions.h.
References FrameWithId::getFrame().
void conversions::pathToPathRos (const std::vector< FrameWithId > & path, std::vector< geometry_msgs::PoseStamped > & pathRos) inline
Conversion of a FrameWithId vector (a path) to vector of geometry_msgs::PoseStamped ROS messages.
See frameToPoseStampedRos() for details of the conversion process.
Parameters
[in] std::vector<FrameWithId> - input path.
[out] std::vector<geometry_msgs::PoseStamped> - result of conversion.
Definition at line 264 of file Conversions.h.
References frameToPoseStampedRos().
Referenced by controlLoop(), and pathToPathRos().
void conversions::pathToPathRos (const std::vector< FrameWithId > & path, nav_msgs::Path & pathRos) inline
Conversion of a FrameWithId vector (a path) to nav_msgs::Path ROS message.
See frameToPoseStampedRos() for details of the conversion process.
Parameters
[in] std::vector<FrameWithId>& path - input path.
[out] nav_msgs::Path - result of conversion.
Definition at line 284 of file Conversions.h.
References pathToPathRos().
void conversions::pose2dToFrameKdl (const Pose2D & pose2d, KDL::Frame & pose) inline
Conversion of a Pose2D to a KDL::Frame.
Convert the Pose2D into a KDL::Frame instance. The generated KDL::Frame will have its Z coordinate and its roll and pitch rotation set to zero.
Parameters
[in] Pose2D - input pose.
[out] KDL::Frame - result of conversion.
Definition at line 333 of file Conversions.h.
References Pose2D::getTheta(), Pose2D::getX(), and Pose2D::getY().
void conversions::pose2dToPoseRos (const Pose2D & pose2d, geometry_msgs::Pose & pose) inline
Conversion from Pose2D type to geometry_msgs::Pose ROS message.
Convert the Pose2D instance to a ROS geometry_msgs::Pose instance.
Parameters
[in] Pose2D - input pose, including location and orientation.
[out] geometry_msgs::Pose - converted pose to a ROS message .
Definition at line 247 of file Conversions.h.
References Pose2D::getTheta(), Pose2D::getX(), and Pose2D::getY().
Referenced by publishOdometry().
void conversions::poseRosToFrame (const geometry_msgs::Pose & poseRos, const std::string & id, FrameWithId & pose) inline
Conversion from geometry_msgs::Pose ROS message to FrameWithId data type.
Convert the ROS pose in a KDL::Frame instance and return the KDL::Frame wrapped in side a FrameWithID instance. Uses poseRosToFrameKdl().
Parameters
[in] geometry_msgs::Pose - pose ROS message.
[in] std::string - frame id.
[out] FrameWithId - result of the conversion.
Definition at line 156 of file Conversions.h.
References FrameWithId::getFrame(), FrameWithId::id, and poseRosToFrameKdl().
Referenced by poseStampedRosToFrame().
void conversions::poseRosToFrameKdl (const geometry_msgs::Pose & poseRos, KDL::Frame & frame) inline
Conversion from geometry_msgs::Pose ROS message to KDL::Frame data type.
Convert the ROS pose in a KDL::Frame instance and return the KDL::Frame.
Parameters
[in] geometry_msgs::Pose - pose ROS message.
[out] KDL::Frame - result of the conversion.
Definition at line 139 of file Conversions.h.
Referenced by pathRosToPathKdl(), and poseRosToFrame().
void conversions::poseRosToPose2d (const geometry_msgs::Pose & pose, Pose2D & pose2d) inline
Conversion from geometry_msgs::Pose ROS message to Pose2D data type.
Convert the ROS pose in a Pose2D instance and return the Pose2D by assigning to the supplied pose2d.
Parameters
[in] geometry_msgs::Pose - pose ROS message.
[out] Pose2D - result of the conversion.
Definition at line 184 of file Conversions.h.
Referenced by odomCallback().
void conversions::poseStampedRosToFrame (const geometry_msgs::PoseStamped & poseStamped, FrameWithId & pose) inline
Conversion from geometry_msgs::PoseStamped ROS message to FrameWithId data type.
Convert the ROS pose in a KDL::Frame instance and return the KDL::Frame wrapped in side a FrameWithID instance. The FrameWithId::id member is set to the geometry_msgs::PoseStamped::header::frame_id value.
Parameters
[in] geometry_msgs::PoseStamped - pose ROS message with frame id.
[out] FrameWithId - result of the conversion.
Definition at line 171 of file Conversions.h.
References poseRosToFrame().
Referenced by goalCallback(), and pathRosToPath().
void conversions::rosKdlStreamToTrajectoryKdl (const navigation_trajectory_common::KdlStream & trajectoryMsg, KDL::Trajectory_Composite & trajectory) inline
Conversion of a ROS KdlStream message to a KDL::Trajectory_Composite.
This function convertes a ROS KdlStream message to a KDL trajectory. To be use with ROS node wrappers around BRICS_RN (or KDL) classes.
Parameters
[in] navigation_trajectory_common::KdlStream - input trajectory message.
[out] KDL::Trajectory_Composite - result of conversion.
Definition at line 487 of file Conversions.h.
void conversions::trajectoryKdlToRosKdlStream (const KDL::Trajectory_Composite & trajectory, navigation_trajectory_common::KdlStream & trajectoryMsg) inline
Conversion of a KDL::Trajectory_Composite to a ROS message.
This function convertes a KDL trajectory into a simple, string-based ROS message to use with ROS node wrappers around BRICS_RN (or KDL) classes.
Parameters
[in] KDL::Trajectory_Composite - input trajectory.
[out] navigation_trajectory_common::KdlStream - result of conversion.
Definition at line 472 of file Conversions.h.
Referenced by pathCallback().
void conversions::twist2dToTwistKdl (const Twist2D & twist2d, KDL::Twist & twist) inline
Conversion from Twist2D data type to KDL::Twist.
Convert the Twist2D into a KDL::Twist instance. The generated KDL::Twist will have its Z translation and its rotation around X and Y set to zero.
Parameters
[in] TwistWithId - twist object.
[out] KDL::Twist - converted twist object.
Definition at line 346 of file Conversions.h.
References Twist2D::getTheta(), Twist2D::getX(), and Twist2D::getY().
void conversions::twist2dToTwistRos (const Twist2D & twist2d, geometry_msgs::Twist & twist) inline
Conversion from Twist2D data type to geometry_msgs::Twist ROS message.
Convert the Twist2D into a geometry_msgs::Twist instance.
Parameters
[in] TwistWithId - twist object.
[out] geometry_msgs::Twist - converted twist ROS message.
Definition at line 125 of file Conversions.h.
References Twist2D::getTheta(), Twist2D::getX(), and Twist2D::getY().
Referenced by publishOdometry().
void conversions::twistRosToTwist2d (const geometry_msgs::Twist & twist, Twist2D & twist2d) inline
Conversion from geometry_msgs::Twist ROS message to Twist2D data type.
Convert the geometry_msgs::Twist into a Twist2D instance, returned by assignment to the suppliedd twist2d parametrer.
Parameters
[in] geometry_msgs::Twist - twist ROS message.
[out] TwistWithId - converted twist.
Definition at line 110 of file Conversions.h.
Referenced by odomCallback().