BRICS_RN_Robust_Navigation_Library(BRICS_RN): utilities Namespace Reference
utilities Namespace Reference
Some commonly used routines.
Functions
double perpendicularDistance (const FrameWithId &point, const FrameWithId &linePoint1, const FrameWithId &linePoint2)
Calculates and returns perpendicular distance form the given point to the line (for 2D space)
void prunePath (const std::vector< FrameWithId > &path, const FrameWithId &point, std::vector< FrameWithId > &prunedPath)
Calculates pruned path, builds perpendiculars to the original path.
Detailed Description
Some commonly used routines.
Function Documentation
double utilities::perpendicularDistance (const FrameWithId & point, const FrameWithId & linePoint1, const FrameWithId & linePoint2) inline
Calculates and returns perpendicular distance form the given point to the line (for 2D space)
This function operates only on the x and y coordinates of the supplied FrameWithIds.
Parameters
[in] point - FrameWithId coordinates of the point.
[in] linePoint1 - FrameWithId 1st coordinate of the line.
[in] linePoint2 - FrameWithId 2nd coordinate of the line.
Definition at line 63 of file Utilities.h.
References FrameWithId::getFrame().
Referenced by DouglasPeuckerApproximation::douglasPeucker(), and prunePath().
void utilities::prunePath (const std::vector< FrameWithId > & path, const FrameWithId & point, std::vector< FrameWithId > & prunedPath) inline
Calculates pruned path, builds perpendiculars to the original path.
This finds the path segmen s in the original path path with the shortests distance to point, measured perpendicular to s. The path segment s is defined as the straight line from waypoint s to waypoint s+1. The pruned path starts with point and continues with all waypoints in path starting with waypoint s+1.
If two or more segments in path have the same highest distance to point, then the segment which comes last in path is selected.
Parameters
[in] path - std::vector<FrameWithId> original path, a vector of FrameWithId.
[in] point - FrameWithId trimming point.
[out] prunedPath - std::vector<FrameWithId> resulting pruned path.
Definition at line 99 of file Utilities.h.
References path, and perpendicularDistance().
Referenced by CollisionCheckingRos::collisionCheck().