BRICS_RN_Robust_Navigation_Library(BRICS_RN): navigation_trajectory_planner/include/navigation_trajectory_planner/PathUtilities.h File Reference
navigation_trajectory_planner/include/navigation_trajectory_planner/PathUtilities.h File Reference
#include <navigation_trajectory_common/FrameWithId.h>
#include <vector>
Functions
double perpendicularDistance (const FrameWithId &point, const FrameWithId &linePoint1, const FrameWithId &linePoint2)
void prunePath (const std::vector< FrameWithId > &path, const FrameWithId &point, std::vector< FrameWithId > &prunedPath)
Function Documentation
double perpendicularDistance (const FrameWithId & point, const FrameWithId & linePoint1, const FrameWithId & linePoint2) [inline]
Definition at line 46 of file PathUtilities.h.
Referenced by DouglasPeuckerApproximation::douglasPeucker(), and prunePath().
void prunePath (const std::vector< FrameWithId > & path, const FrameWithId & point, std::vector< FrameWithId > & prunedPath) [inline]
Definition at line 65 of file PathUtilities.h.
References path, and perpendicularDistance().
Referenced by CollisionCheckingRos::collisionCheck().