BRICS_RN_Robust_Navigation_Library(BRICS_RN): navigation_trajectory_planner/src/TrajectoryAdapterNode.cpp File Reference
navigation_trajectory_planner/src/TrajectoryAdapterNode.cpp File Reference
#include <ros/ros.h>
#include <nav_msgs/Path.h>
#include <nav_msgs/Odometry.h>
#include <pluginlib/class_loader.h>
#include <costmap_2d/costmap_2d_ros.h>
#include <nav_core/base_global_planner.h>
#include <kdl/trajectory_composite.hpp>
#include "navigation_trajectory_common/FrameWithId.h"
#include "navigation_trajectory_common/TwistWithId.h"
#include "navigation_trajectory_common/Conversions.h"
#include "navigation_trajectory_planner/TrajectoryAdapter.h"
#include "navigation_trajectory_planner/TrajectoryAdapterObserver.h"
#include "navigation_trajectory_planner/PathPlannerRos.h"
#include "navigation_trajectory_planner/DouglasPeuckerApproximation.h"
#include "navigation_trajectory_planner/ChaikinCurveApproximation.h"
#include "navigation_trajectory_planner/CollisionCheckingRos.h"
Classes
class TrajectoryAdapterObserverROS
class TrajectoryAdapterNodeState
Functions
void odometryCallback (const nav_msgs::Odometry &odometry)
void goalCallback (const geometry_msgs::PoseStamped &goal)
double controlLoop ()
int main (int argc, char **argv)
Variables
TrajectoryAdapter * trajectoryAdapter
TrajectoryAdapterNodeState actualState
ros::Publisher pathPublisher
ros::Publisher simplifiedPathPublisher
TwistWithId actualTwist
FrameWithId actualPose
FrameWithId goalPose
PathPlanner * pathPlanner
CollisionChecking * collisionChecker
std::vector< FrameWithId > path
std::vector< FrameWithId > simplifiedPath
Function Documentation
double controlLoop ()
Definition at line 126 of file TrajectoryAdapterNode.cpp.
References actualPose, actualState, actualTwist, DouglasPeuckerApproximation::approximate(), CollisionChecking::check(), TrajectoryAdapterNodeState::COLLISION_CHECKING, collisionChecker, PathPlanner::computePath(), TrajectoryAdapterNodeState::get(), goalPose, TrajectoryAdapterNodeState::IDLING, path, pathPlanner, pathPublisher, conversions::pathToPathRos(), TrajectoryAdapterNodeState::PLANNING, TrajectoryAdapterNodeState::set(), simplifiedPath, simplifiedPathPublisher, trajectoryAdapter, and TrajectoryAdapter::updateOdometry().
Referenced by main().
void goalCallback (const geometry_msgs::PoseStamped & goal)
Definition at line 115 of file TrajectoryAdapterNode.cpp.
References actualState, goalPose, TrajectoryAdapterNodeState::PLANNING, conversions::poseStampedRosToFrame(), and TrajectoryAdapterNodeState::set().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 177 of file TrajectoryAdapterNode.cpp.
References actualState, collisionChecker, controlLoop(), goalCallback(), TrajectoryAdapterNodeState::IDLING, odometryCallback(), pathPlanner, pathPublisher, TrajectoryAdapterNodeState::set(), simplifiedPathPublisher, and trajectoryAdapter.
void odometryCallback (const nav_msgs::Odometry & odometry)
Definition at line 108 of file TrajectoryAdapterNode.cpp.
References actualPose, actualTwist, conversions::odometryRosToFrame(), and conversions::odometryRosToTwist().
Referenced by main().
Variable Documentation
FrameWithId actualPose
Definition at line 104 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), odometryCallback(), OmniDrivePositionController::setTargetTrajectory(), and OmniDrivePositionController::targetReached().
TrajectoryAdapterNodeState actualState
Definition at line 100 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), goalCallback(), and main().
TwistWithId actualTwist
Definition at line 103 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and odometryCallback().
CollisionChecking* collisionChecker
Definition at line 106 of file TrajectoryAdapterNode.cpp.
Referenced by CollisionCheckingRos::collisionCheck(), controlLoop(), and main().
FrameWithId goalPose
Definition at line 104 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and goalCallback().
std::vector<FrameWithId> path
Definition at line 124 of file TrajectoryAdapterNode.cpp.
Referenced by OmniDriveTrajectoryGenerator::computeTrajectoryComposite(), controlLoop(), prunePath(), OmniDrivePositionController::setTargetTrajectory(), and trajectoryCallback().
PathPlanner* pathPlanner
Definition at line 105 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and main().
ros::Publisher pathPublisher
Definition at line 102 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and main().
std::vector<FrameWithId> simplifiedPath
Definition at line 124 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop().
ros::Publisher simplifiedPathPublisher
Definition at line 102 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and main().
TrajectoryAdapter* trajectoryAdapter
Definition at line 99 of file TrajectoryAdapterNode.cpp.
Referenced by controlLoop(), and main().