BRICS_RN (Robust Navigation Library): navigation_trajectory_follower/src/TrajectoryGeneratorNode.cpp File Reference
TrajectoryGeneratorNode.cpp File Reference
Implementation of a ROS wrapper around ITrajectoryGenerator interface.
#include <ros/ros.h>
#include "trajectory_generator/OmniDriveTrajectoryGenerator.h"
#include "navigation_trajectory_common/Conversions.h"
#include "tf/transform_datatypes.h"
#include "nav_msgs/Path.h"
#include "navigation_trajectory_common/KdlStream.h"
#include "kdl/trajectory_composite.hpp"
Functions
void pathCallback (const nav_msgs::Path &path)
int main (int argc, char **argv)
Variables
ros::Publisher trajectoryPublisher
ITrajectoryGenerator * generator
Detailed Description
Implementation of a ROS wrapper around ITrajectoryGenerator interface.
This file contains a complete ROS node offering trajectory generation. It listens on a configurable topic, defautl "rn_path" for ROS path messages and converts such a path into a KDL trajectory using the ITrajectoryGenerator interface. The algorithm used can be change in the main() function by instantiating a different implementation of that interface. The generated trajectory is send to a configurable topic, by default rn_trajectory.
Definition in file TrajectoryGeneratorNode.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 90 of file TrajectoryGeneratorNode.cpp.
References generator, pathCallback(), and trajectoryPublisher.
void pathCallback (const nav_msgs::Path & path)
Definition at line 74 of file TrajectoryGeneratorNode.cpp.
References ITrajectoryGenerator::computeTrajectroy(), generator, conversions::pathRosToPathKdl(), conversions::trajectoryKdlToRosKdlStream(), and trajectoryPublisher.
Variable Documentation
ITrajectoryGenerator* generator
Definition at line 71 of file TrajectoryGeneratorNode.cpp.
Referenced by main(), and pathCallback().
ros::Publisher trajectoryPublisher
Definition at line 70 of file TrajectoryGeneratorNode.cpp.
Referenced by main(), and pathCallback().