BRICS_RN_Robust_Navigation_Library(BRICS_RN): navigation_trajectory_follower/src/TrajectoryFollowerNode.cpp File Reference
navigation_trajectory_follower/src/TrajectoryFollowerNode.cpp File Reference
#include "trajectory_generator/OmniDriveTrajectoryGenerator.h"
#include "navigation_trajectory_common/Conversions.h"
#include "omnidrive_controller/OmniDrivePositionController.h"
#include "navigation_trajectory_follower/TrajectoryFollowerNode.h"
#include "tf/transform_datatypes.h"
#include "nav_msgs/Odometry.h"
#include "nav_msgs/Path.h"
#include "geometry_msgs/Twist.h"
#include <navigation_trajectory_follower/ConversionUtils.h>
Functions
void poseRosToPose2d (const geometry_msgs::Pose &pose, Pose2D &pose2d)
void twistRosToTwist2d (const geometry_msgs::Twist &twist, Twist2D &twist2d)
void pose2dToPoseRos (const Pose2D &pose2d, geometry_msgs::Pose &pose)
void trajectoryRosToOdomVector (const navigation_trajectory_msgs::Trajectory &trajectoryROS, std::vector< Odometry > &odometryVector)
void twist2dToTwistRos (const Twist2D &twist2d, geometry_msgs::Twist &twist)
void odomCallback (const nav_msgs::Odometry &odometry)
void pathCallback (const nav_msgs::Path &path)
void trajectoryCallback (const navigation_trajectory_msgs::Trajectory &trajectory)
void publishOdometry (const Odometry &odometry)
void controlLoop ()
int main (int argc, char **argv)
Variables
ros::Publisher twistPublisher
Odometry actualOdometry
PositionController * controller
ros::Time startTime
ros::Publisher debugPath
Function Documentation
void controlLoop ()
Definition at line 183 of file TrajectoryFollowerNode.cpp.
References actualOdometry, PositionController::computeNewOdometry(), controller, publishOdometry(), and startTime.
int main (int argc, char ** argv)
Definition at line 191 of file TrajectoryFollowerNode.cpp.
References controller, controlLoop(), debugPath, odomCallback(), trajectoryCallback(), and twistPublisher.
void odomCallback (const nav_msgs::Odometry & odometry)
Definition at line 116 of file TrajectoryFollowerNode.cpp.
References actualOdometry, poseRosToPose2d(), and twistRosToTwist2d().
Referenced by main().
void pathCallback (const nav_msgs::Path & path)
Definition at line 131 of file TrajectoryFollowerNode.cpp.
References OmniDriveTrajectoryGenerator::computeTrajectroy(), and conversions::pathRosToPath().
void pose2dToPoseRos (const Pose2D & pose2d, geometry_msgs::Pose & pose)
Definition at line 79 of file TrajectoryFollowerNode.cpp.
References Pose2D::getTheta(), Pose2D::getX(), and Pose2D::getY().
Referenced by publishOdometry().
void poseRosToPose2d (const geometry_msgs::Pose & pose, Pose2D & pose2d)
Definition at line 60 of file TrajectoryFollowerNode.cpp.
Referenced by odomCallback(), and trajectoryRosToOdomVector().
void publishOdometry (const Odometry & odometry)
Definition at line 167 of file TrajectoryFollowerNode.cpp.
References Odometry::getPose2D(), Odometry::getTwist2D(), pose2dToPoseRos(), twist2dToTwistRos(), and twistPublisher.
Referenced by controlLoop().
void trajectoryCallback (const navigation_trajectory_msgs::Trajectory & trajectory)
Definition at line 139 of file TrajectoryFollowerNode.cpp.
References controller, debugPath, path, PositionController::setTargetTrajectory(), startTime, and trajectoryRosToOdomVector().
Referenced by main().
void trajectoryRosToOdomVector (const navigation_trajectory_msgs::Trajectory & trajectoryROS, std::vector< Odometry > & odometryVector)
Definition at line 90 of file TrajectoryFollowerNode.cpp.
References poseRosToPose2d(), and twistRosToTwist2d().
Referenced by trajectoryCallback().
void twist2dToTwistRos (const Twist2D & twist2d, geometry_msgs::Twist & twist)
Definition at line 108 of file TrajectoryFollowerNode.cpp.
References Twist2D::getTheta(), Twist2D::getX(), and Twist2D::getY().
Referenced by publishOdometry().
void twistRosToTwist2d (const geometry_msgs::Twist & twist, Twist2D & twist2d)
Definition at line 69 of file TrajectoryFollowerNode.cpp.
Referenced by odomCallback(), and trajectoryRosToOdomVector().
Variable Documentation
Odometry actualOdometry
Definition at line 54 of file TrajectoryFollowerNode.cpp.
Referenced by controlLoop(), and odomCallback().
PositionController* controller
Definition at line 55 of file TrajectoryFollowerNode.cpp.
Referenced by controlLoop(), main(), and trajectoryCallback().
ros::Publisher debugPath
Definition at line 58 of file TrajectoryFollowerNode.cpp.
Referenced by main(), and trajectoryCallback().
ros::Time startTime
Definition at line 56 of file TrajectoryFollowerNode.cpp.
Referenced by controlLoop(), and trajectoryCallback().
ros::Publisher twistPublisher
Definition at line 53 of file TrajectoryFollowerNode.cpp.
Referenced by main(), and publishOdometry().