BRICS_RN_Robust_Navigation_Library(BRICS_RN): navigation_trajectory_follower/src/omnidrive_controller/Twist2D.cpp File Reference
navigation_trajectory_follower/src/omnidrive_controller/Twist2D.cpp File Reference
#include "Twist2D.h"
Functions
Twist2D operator+ (const Twist2D &op1, const Twist2D &op2)
Function Documentation
Twist2D operator+ (const Twist2D & op1, const Twist2D & op2)
Definition at line 87 of file Twist2D.cpp.
References Twist2D::getTheta(), Twist2D::getX(), and Twist2D::getY().